// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalAssessmentRokov.Data;

#nullable disable

namespace TechnicalAssessmentRokov.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240619041105_InitializeDates")]
    partial class InitializeDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUTHOR");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORY");

                    b.Property<int?>("CheckedOutById")
                        .HasColumnType("int")
                        .HasColumnName("CHECKED_OUT_BY");

                    b.Property<DateTime?>("CheckedOutDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CHECKED_OUT_DATE");

                    b.Property<string>("CoverPage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COVER_PAGE");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DUE_DATE");

                    b.Property<int>("ISBN")
                        .HasColumnType("int")
                        .HasColumnName("ISBN");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("PAGE_COUNT");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PUBLICATION_DATE");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PUBLISHER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.HasKey("ID");

                    b.HasIndex("CheckedOutById");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Zella Waters",
                            Category = "reprehenderit",
                            CoverPage = "https://picsum.photos/50/50/?image=951",
                            Description = "Totam omnis nam animi hic earum dolores omnis labore magnam possimus natus hic beatae ab et veritatis nobis ea et.",
                            ISBN = 404662840,
                            PageCount = 370,
                            PublicationDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Green - Satterfield",
                            Title = "Oklahoma driver Handmade Cotton Ball"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Hassan Green",
                            Category = "impedit",
                            CoverPage = "https://picsum.photos/50/50/?image=457",
                            Description = "Ipsa est magnam incidunt sit quia eveniet quibusdam recusandae asperiores voluptate est dolores dolores consequatur et nobis iste doloremque et.",
                            ISBN = 347719743,
                            PageCount = 826,
                            PublicationDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Wehner - Cormier",
                            Title = "Albania disintermediate Analyst"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Kenneth Brakus",
                            Category = "molestias",
                            CoverPage = "https://picsum.photos/50/50/?image=27",
                            Description = "Sint reiciendis assumenda dolores molestiae modi nisi soluta non sunt ut a voluptatem maxime aut exercitationem minima eos pariatur saepe.",
                            ISBN = 785997234,
                            PageCount = 591,
                            PublicationDate = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "MacGyver, Morar and Daniel",
                            Title = "dynamic Forest Metal"
                        },
                        new
                        {
                            ID = 4,
                            Author = "Maynard Wehner",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=840",
                            Description = "Molestiae veritatis quidem ea deleniti saepe labore voluptatem non consequatur voluptatem eius corporis atque dicta rerum blanditiis veritatis qui non.",
                            ISBN = 358401009,
                            PageCount = 489,
                            PublicationDate = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lind and Sons",
                            Title = "French Southern Territories brand Crest"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Randal Gulgowski",
                            Category = "placeat",
                            CoverPage = "https://picsum.photos/50/50/?image=1081",
                            Description = "A aliquid maxime provident cum ut consectetur sit commodi omnis tempore et non iusto dignissimos voluptas magnam ullam aperiam ut.",
                            ISBN = 571354335,
                            PageCount = 986,
                            PublicationDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schaden, Aufderhar and Borer",
                            Title = "Officer Views synthesize"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Monty D'Amore",
                            Category = "illum",
                            CoverPage = "https://picsum.photos/50/50/?image=845",
                            Description = "Est omnis consectetur amet recusandae eius quis rerum blanditiis illo tempore eaque eaque voluptatem error quia sequi perspiciatis cupiditate corrupti.",
                            ISBN = 250736792,
                            PageCount = 644,
                            PublicationDate = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gerlach - Schulist",
                            Title = "next generation Tunnel Extension"
                        },
                        new
                        {
                            ID = 7,
                            Author = "Katlyn Rogahn",
                            Category = "autem",
                            CoverPage = "https://picsum.photos/50/50/?image=272",
                            Description = "Expedita unde vero dolores nemo rerum sint facere et inventore aperiam mollitia delectus consequatur et et sed quia in praesentium.",
                            ISBN = 241698682,
                            PageCount = 531,
                            PublicationDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kihn, Leffler and Hickle",
                            Title = "Sleek Plastic Mouse collaboration dedicated"
                        },
                        new
                        {
                            ID = 8,
                            Author = "Marlon Frami",
                            Category = "minima",
                            CoverPage = "https://picsum.photos/50/50/?image=13",
                            Description = "Qui et qui dolorum voluptas et nihil commodi quae ea aut praesentium odio cumque tempore repellat laboriosam est ipsam velit.",
                            ISBN = 300991162,
                            PageCount = 932,
                            PublicationDate = new DateTime(2024, 5, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schmeler Inc",
                            Title = "Colorado backing up Arkansas"
                        },
                        new
                        {
                            ID = 9,
                            Author = "Olga Shields",
                            Category = "cupiditate",
                            CoverPage = "https://picsum.photos/50/50/?image=1081",
                            Description = "Voluptatum doloribus sit rerum officiis deleniti magnam molestiae nulla ut voluptatibus odit ratione harum a voluptas id dignissimos sunt sit.",
                            ISBN = 497401294,
                            PageCount = 694,
                            PublicationDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Padberg, Jenkins and Nicolas",
                            Title = "Interactions SSL Refined Concrete Tuna"
                        },
                        new
                        {
                            ID = 10,
                            Author = "Romaine Rowe",
                            Category = "at",
                            CoverPage = "https://picsum.photos/50/50/?image=286",
                            Description = "Quo voluptate vero harum maxime occaecati debitis necessitatibus fugit dolorum doloribus numquam at debitis quis vel unde modi vel commodi.",
                            ISBN = 956390999,
                            PageCount = 107,
                            PublicationDate = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Zboncak LLC",
                            Title = "invoice Clothing & Games encryption"
                        },
                        new
                        {
                            ID = 11,
                            Author = "Hyman Hills",
                            Category = "quidem",
                            CoverPage = "https://picsum.photos/50/50/?image=186",
                            Description = "Nemo nemo nulla culpa voluptate ut eos id molestiae beatae rem et quia eveniet enim aut nulla molestiae omnis quos.",
                            ISBN = 467552270,
                            PageCount = 479,
                            PublicationDate = new DateTime(2023, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "VonRueden, Bauch and Prohaska",
                            Title = "deliver Hawaii Associate"
                        },
                        new
                        {
                            ID = 12,
                            Author = "Sister Smitham",
                            Category = "eaque",
                            CoverPage = "https://picsum.photos/50/50/?image=113",
                            Description = "Alias velit provident aut quas et reiciendis labore molestiae quia amet doloribus dicta id vero unde tenetur beatae nobis doloremque.",
                            ISBN = 662027752,
                            PageCount = 800,
                            PublicationDate = new DateTime(2023, 9, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Wyman - Quitzon",
                            Title = "Knolls Liaison Planner"
                        },
                        new
                        {
                            ID = 13,
                            Author = "Mike Torphy",
                            Category = "est",
                            CoverPage = "https://picsum.photos/50/50/?image=287",
                            Description = "Voluptatem quibusdam omnis iusto et ut in quibusdam eligendi dignissimos officia dolore libero et dolorem rerum omnis natus consequatur amet.",
                            ISBN = 116969906,
                            PageCount = 363,
                            PublicationDate = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lubowitz - Bosco",
                            Title = "transmit deposit copying"
                        },
                        new
                        {
                            ID = 14,
                            Author = "Maryse Hammes",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=307",
                            Description = "Qui dolores quis velit unde voluptatem voluptas quia voluptates quis voluptates numquam eum voluptatem officiis excepturi error odit ex aut.",
                            ISBN = 345078156,
                            PageCount = 268,
                            PublicationDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hintz, Koss and Kerluke",
                            Title = "Borders Gibraltar Pound SCSI"
                        },
                        new
                        {
                            ID = 15,
                            Author = "Camron Blick",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=613",
                            Description = "Quae mollitia et magni repellat sed autem impedit ab architecto molestias dolorem vero ut ipsa est assumenda mollitia deleniti laudantium.",
                            ISBN = 402544114,
                            PageCount = 752,
                            PublicationDate = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Cole Inc",
                            Title = "sticky radical software"
                        },
                        new
                        {
                            ID = 16,
                            Author = "Thora Erdman",
                            Category = "nam",
                            CoverPage = "https://picsum.photos/50/50/?image=200",
                            Description = "Nemo minus saepe similique esse iste velit tempore rem qui corrupti omnis est et voluptatem veniam delectus consequatur et labore.",
                            ISBN = 879952106,
                            PageCount = 828,
                            PublicationDate = new DateTime(2023, 11, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hayes, Raynor and Mosciski",
                            Title = "quantifying Small Plastic Keyboard Handmade Concrete Chicken"
                        },
                        new
                        {
                            ID = 17,
                            Author = "Thad Mueller",
                            Category = "voluptatem",
                            CoverPage = "https://picsum.photos/50/50/?image=828",
                            Description = "Enim perspiciatis nam omnis id ipsam quo blanditiis placeat est ut sed quidem ea qui nostrum explicabo sit recusandae iste.",
                            ISBN = 170590521,
                            PageCount = 612,
                            PublicationDate = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Shanahan, Botsford and Kautzer",
                            Title = "Drive input Technician"
                        },
                        new
                        {
                            ID = 18,
                            Author = "Lenny Barrows",
                            Category = "possimus",
                            CoverPage = "https://picsum.photos/50/50/?image=790",
                            Description = "Sint consequatur maiores eligendi iste incidunt in ea laudantium sed quaerat minus aspernatur a quod voluptate et rerum qui animi.",
                            ISBN = 778499631,
                            PageCount = 274,
                            PublicationDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Wisozk, Weimann and Ortiz",
                            Title = "repurpose Books & Tools Falls"
                        },
                        new
                        {
                            ID = 19,
                            Author = "Merlin Gleichner",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=802",
                            Description = "Molestias ut sint inventore omnis rerum accusantium perferendis earum quos assumenda adipisci sed necessitatibus veritatis qui est dignissimos qui blanditiis.",
                            ISBN = 509532997,
                            PageCount = 274,
                            PublicationDate = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hyatt and Sons",
                            Title = "Macao Avon compelling"
                        },
                        new
                        {
                            ID = 20,
                            Author = "Elmore Williamson",
                            Category = "qui",
                            CoverPage = "https://picsum.photos/50/50/?image=374",
                            Description = "Cum exercitationem atque enim sed ut non sit voluptas nostrum expedita praesentium et est pariatur nihil porro iure soluta velit.",
                            ISBN = 317663697,
                            PageCount = 992,
                            PublicationDate = new DateTime(2023, 6, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Olson - Schowalter",
                            Title = "backing up SMS withdrawal"
                        },
                        new
                        {
                            ID = 21,
                            Author = "Chad Langworth",
                            Category = "animi",
                            CoverPage = "https://picsum.photos/50/50/?image=885",
                            Description = "Ad ipsum dolor est aut et quae mollitia maxime eum quia aut illum blanditiis fuga iusto praesentium aut eos nulla.",
                            ISBN = 844610351,
                            PageCount = 857,
                            PublicationDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kirlin, Schamberger and Klein",
                            Title = "Markets Investment Account deposit"
                        },
                        new
                        {
                            ID = 22,
                            Author = "Stuart Satterfield",
                            Category = "nihil",
                            CoverPage = "https://picsum.photos/50/50/?image=689",
                            Description = "Alias et nulla facilis consequatur autem illo eius est aspernatur ipsam consequatur aliquam eius culpa et est consequuntur accusamus aliquid.",
                            ISBN = 357537050,
                            PageCount = 303,
                            PublicationDate = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Huel, Kuphal and Kertzmann",
                            Title = "Incredible Rubber Fish action-items IB"
                        },
                        new
                        {
                            ID = 23,
                            Author = "Abby Hansen",
                            Category = "voluptatem",
                            CoverPage = "https://picsum.photos/50/50/?image=513",
                            Description = "Sed omnis dolorem sed dolor asperiores libero et impedit dolor alias adipisci quam cumque et quis et rerum sint est.",
                            ISBN = 906546955,
                            PageCount = 189,
                            PublicationDate = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kutch, Hickle and Shields",
                            Title = "implementation Refined Fresh Table local"
                        },
                        new
                        {
                            ID = 24,
                            Author = "Obie Pollich",
                            Category = "corporis",
                            CoverPage = "https://picsum.photos/50/50/?image=805",
                            Description = "Maiores reprehenderit unde qui voluptatem dignissimos nisi sunt sapiente hic sunt voluptas adipisci eum iste harum nesciunt iure ipsam quisquam.",
                            ISBN = 833109605,
                            PageCount = 928,
                            PublicationDate = new DateTime(2023, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hand, Jacobs and Torphy",
                            Title = "compressing Buckinghamshire Industrial & Shoes"
                        },
                        new
                        {
                            ID = 25,
                            Author = "Imani Runolfsson",
                            Category = "autem",
                            CoverPage = "https://picsum.photos/50/50/?image=314",
                            Description = "Esse autem et numquam veritatis ex eum numquam aut at harum magni quis temporibus odio impedit consequatur ullam facilis sint.",
                            ISBN = 789019651,
                            PageCount = 408,
                            PublicationDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Watsica, Rau and Jacobi",
                            Title = "XSS Paradigm Practical Cotton Car"
                        },
                        new
                        {
                            ID = 26,
                            Author = "Dewitt Dooley",
                            Category = "officia",
                            CoverPage = "https://picsum.photos/50/50/?image=1046",
                            Description = "Aut molestias incidunt numquam aspernatur tempora ad nobis dolor repellendus vero molestias officia tenetur officia tenetur repudiandae et accusamus aspernatur.",
                            ISBN = 342527640,
                            PageCount = 77,
                            PublicationDate = new DateTime(2023, 12, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Pfannerstill Group",
                            Title = "Licensed Steel Table tertiary scalable"
                        },
                        new
                        {
                            ID = 27,
                            Author = "Berenice Crona",
                            Category = "autem",
                            CoverPage = "https://picsum.photos/50/50/?image=877",
                            Description = "Mollitia quam tempore accusantium et expedita tempora laudantium eum error laborum quis iusto aut et placeat est asperiores ut consequuntur.",
                            ISBN = 271056711,
                            PageCount = 475,
                            PublicationDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ullrich, Walter and Kertzmann",
                            Title = "circuit calculate Minnesota"
                        },
                        new
                        {
                            ID = 28,
                            Author = "Devon Marquardt",
                            Category = "voluptatum",
                            CoverPage = "https://picsum.photos/50/50/?image=410",
                            Description = "Tempora aliquam sunt ea dolorum error repudiandae autem corrupti hic doloribus in quam molestias porro voluptatem velit nesciunt laboriosam voluptas.",
                            ISBN = 277208709,
                            PageCount = 975,
                            PublicationDate = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mayert - Raynor",
                            Title = "Refined Steel Chair project Spring"
                        },
                        new
                        {
                            ID = 29,
                            Author = "Leonardo Rutherford",
                            Category = "at",
                            CoverPage = "https://picsum.photos/50/50/?image=164",
                            Description = "Ad cumque quia quam minima repellat sequi sed omnis ut fuga architecto veritatis nihil iure adipisci temporibus fugit quae necessitatibus.",
                            ISBN = 680303239,
                            PageCount = 510,
                            PublicationDate = new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Durgan, Ferry and Hettinger",
                            Title = "Progressive Platinum Avon"
                        },
                        new
                        {
                            ID = 30,
                            Author = "Macy Maggio",
                            Category = "dolore",
                            CoverPage = "https://picsum.photos/50/50/?image=703",
                            Description = "Debitis est vero quis beatae et quaerat occaecati beatae eius praesentium distinctio nihil reiciendis tenetur deleniti harum similique animi optio.",
                            ISBN = 577470796,
                            PageCount = 308,
                            PublicationDate = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Denesik, Berge and Bergnaum",
                            Title = "Associate Credit Card Account Prairie"
                        },
                        new
                        {
                            ID = 31,
                            Author = "Gavin Orn",
                            Category = "exercitationem",
                            CoverPage = "https://picsum.photos/50/50/?image=1018",
                            Description = "Amet explicabo magnam suscipit possimus porro autem sed aut a aperiam eos ipsa sapiente atque odit est nihil molestiae inventore.",
                            ISBN = 381114935,
                            PageCount = 93,
                            PublicationDate = new DateTime(2023, 10, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Carter, Fritsch and Hagenes",
                            Title = "Marketing CFA Franc BEAC secondary"
                        },
                        new
                        {
                            ID = 32,
                            Author = "Kirk Hand",
                            Category = "incidunt",
                            CoverPage = "https://picsum.photos/50/50/?image=64",
                            Description = "Est nobis optio enim eius et et deleniti nemo officiis tenetur minus vel accusamus autem perferendis et sequi consequatur accusamus.",
                            ISBN = 124411772,
                            PageCount = 276,
                            PublicationDate = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Dare - Goodwin",
                            Title = "New Hampshire New Hampshire Product"
                        },
                        new
                        {
                            ID = 33,
                            Author = "Harrison Cummerata",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=999",
                            Description = "Eum repellat ut quos quae et expedita nam sint sit omnis distinctio velit libero esse modi vitae est occaecati ducimus.",
                            ISBN = 710059717,
                            PageCount = 561,
                            PublicationDate = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Quigley, Larson and Veum",
                            Title = "Streamlined parsing microchip"
                        },
                        new
                        {
                            ID = 34,
                            Author = "Oliver Bashirian",
                            Category = "cupiditate",
                            CoverPage = "https://picsum.photos/50/50/?image=68",
                            Description = "Autem tenetur ratione sunt sint rerum saepe culpa ab molestiae sed eos earum asperiores voluptatum mollitia qui qui qui eaque.",
                            ISBN = 931781546,
                            PageCount = 843,
                            PublicationDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Heathcote, Tremblay and Jones",
                            Title = "distributed Generic Plastic Soap sticky"
                        },
                        new
                        {
                            ID = 35,
                            Author = "Grayson Gleason",
                            Category = "rerum",
                            CoverPage = "https://picsum.photos/50/50/?image=667",
                            Description = "Dignissimos adipisci aliquam natus quos ea magnam dolor quae assumenda est saepe similique repellendus esse eligendi et maxime voluptatum necessitatibus.",
                            ISBN = 546833936,
                            PageCount = 638,
                            PublicationDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Howe, Mitchell and Raynor",
                            Title = "cross-media Cambridgeshire invoice"
                        },
                        new
                        {
                            ID = 36,
                            Author = "Reed Carter",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=917",
                            Description = "Velit culpa itaque vitae velit unde perferendis ex in aliquid vel impedit accusamus consequatur et molestiae tempore ratione corrupti placeat.",
                            ISBN = 353546359,
                            PageCount = 198,
                            PublicationDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Becker, Schroeder and Marquardt",
                            Title = "Handmade Granite Chair payment PCI"
                        },
                        new
                        {
                            ID = 37,
                            Author = "Hettie Schaefer",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=1049",
                            Description = "Reprehenderit quasi earum sit et sint culpa dolorum qui consequatur amet quaerat iste sapiente quaerat deleniti sit cumque illum aut.",
                            ISBN = 298756451,
                            PageCount = 151,
                            PublicationDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Oberbrunner Group",
                            Title = "XML Savings Account cultivate"
                        },
                        new
                        {
                            ID = 38,
                            Author = "Camron Corkery",
                            Category = "quisquam",
                            CoverPage = "https://picsum.photos/50/50/?image=124",
                            Description = "Mollitia fugiat necessitatibus qui enim sed omnis eaque in ipsam nobis hic amet ut saepe qui optio labore assumenda error.",
                            ISBN = 766857883,
                            PageCount = 767,
                            PublicationDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Weimann, Muller and Schumm",
                            Title = "District Director action-items"
                        },
                        new
                        {
                            ID = 39,
                            Author = "Leanne Witting",
                            Category = "voluptatem",
                            CoverPage = "https://picsum.photos/50/50/?image=156",
                            Description = "Iusto dicta et deleniti tempore laudantium quidem laborum exercitationem quae impedit aut voluptas beatae veritatis harum nihil officiis nobis soluta.",
                            ISBN = 539984792,
                            PageCount = 944,
                            PublicationDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Monahan and Sons",
                            Title = "Sleek Guam Unbranded Soft Ball"
                        },
                        new
                        {
                            ID = 40,
                            Author = "Elody Anderson",
                            Category = "id",
                            CoverPage = "https://picsum.photos/50/50/?image=658",
                            Description = "Iste error autem reprehenderit et possimus minima dignissimos asperiores modi eos quod delectus ut sint nulla temporibus sequi vel quia.",
                            ISBN = 553050214,
                            PageCount = 810,
                            PublicationDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Wolff and Sons",
                            Title = "HTTP Berkshire white"
                        },
                        new
                        {
                            ID = 41,
                            Author = "Paxton Douglas",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=344",
                            Description = "Necessitatibus nisi consequatur molestias enim neque aut sed aut et repudiandae ut repudiandae ut similique explicabo amet exercitationem est ut.",
                            ISBN = 511612810,
                            PageCount = 494,
                            PublicationDate = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Abbott, Zemlak and Hermann",
                            Title = "Ramp Handmade real-time"
                        },
                        new
                        {
                            ID = 42,
                            Author = "Elody Erdman",
                            Category = "ullam",
                            CoverPage = "https://picsum.photos/50/50/?image=617",
                            Description = "Et dicta quia sed maiores aut rerum maiores tempore magni inventore fugit nihil autem fuga ut facilis voluptas voluptate illo.",
                            ISBN = 221155203,
                            PageCount = 977,
                            PublicationDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hills - Green",
                            Title = "panel Accountability Via"
                        },
                        new
                        {
                            ID = 43,
                            Author = "Rubye Wiza",
                            Category = "voluptatem",
                            CoverPage = "https://picsum.photos/50/50/?image=455",
                            Description = "Eius aliquid deleniti odit est aut veniam id dignissimos ratione velit aspernatur eligendi illum est qui sit quae omnis et.",
                            ISBN = 368778812,
                            PageCount = 651,
                            PublicationDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Veum - Toy",
                            Title = "Money Market Account Ergonomic Steel Computer Rubber"
                        },
                        new
                        {
                            ID = 44,
                            Author = "Malinda Von",
                            Category = "id",
                            CoverPage = "https://picsum.photos/50/50/?image=89",
                            Description = "Sint dolorem sapiente et similique sunt dolor voluptatem aut ut explicabo eos doloremque iure aut et voluptatem porro nihil nam.",
                            ISBN = 592284455,
                            PageCount = 587,
                            PublicationDate = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Cole Group",
                            Title = "Soft Agent Kina"
                        },
                        new
                        {
                            ID = 45,
                            Author = "Kaylie Sipes",
                            Category = "odio",
                            CoverPage = "https://picsum.photos/50/50/?image=1009",
                            Description = "Voluptatibus et nobis nihil aspernatur libero et quasi impedit voluptate tenetur totam tempore non maxime doloremque aperiam quis consequuntur debitis.",
                            ISBN = 226214301,
                            PageCount = 443,
                            PublicationDate = new DateTime(2023, 7, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Nienow Inc",
                            Title = "Expanded envisioneer encoding"
                        },
                        new
                        {
                            ID = 46,
                            Author = "Katarina Rutherford",
                            Category = "facilis",
                            CoverPage = "https://picsum.photos/50/50/?image=428",
                            Description = "Sapiente soluta quam cupiditate quia ratione id aliquam aliquam temporibus quam facilis porro est eum odit maxime ipsa quae ea.",
                            ISBN = 784685452,
                            PageCount = 367,
                            PublicationDate = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Borer LLC",
                            Title = "revolutionary actuating scale"
                        },
                        new
                        {
                            ID = 47,
                            Author = "Beaulah Bahringer",
                            Category = "quia",
                            CoverPage = "https://picsum.photos/50/50/?image=1063",
                            Description = "Officia ipsa rerum fuga ut aut repellendus id debitis aut fugiat at non autem necessitatibus accusamus culpa aut alias fugit.",
                            ISBN = 474793337,
                            PageCount = 852,
                            PublicationDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Adams, Gleichner and Wisoky",
                            Title = "user-facing Street Representative"
                        },
                        new
                        {
                            ID = 48,
                            Author = "Ivory Collier",
                            Category = "odit",
                            CoverPage = "https://picsum.photos/50/50/?image=765",
                            Description = "Et non beatae soluta ab qui voluptates quis a et perspiciatis dignissimos sunt placeat sequi officia eveniet beatae nobis ducimus.",
                            ISBN = 697891789,
                            PageCount = 877,
                            PublicationDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Graham LLC",
                            Title = "models next generation New York"
                        },
                        new
                        {
                            ID = 49,
                            Author = "Jennie Spencer",
                            Category = "sequi",
                            CoverPage = "https://picsum.photos/50/50/?image=493",
                            Description = "Et perspiciatis sed consectetur ad vero tenetur unde similique dolorum expedita aut assumenda itaque quos nam perspiciatis et est facilis.",
                            ISBN = 755904235,
                            PageCount = 276,
                            PublicationDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Wintheiser LLC",
                            Title = "Frozen Rustic Fresh Hat Incredible"
                        },
                        new
                        {
                            ID = 50,
                            Author = "Oscar Price",
                            Category = "sit",
                            CoverPage = "https://picsum.photos/50/50/?image=926",
                            Description = "Dicta totam et quam cumque ipsam iusto tempora accusamus omnis error quis in rerum dolor suscipit voluptatem consequatur est cumque.",
                            ISBN = 655707415,
                            PageCount = 715,
                            PublicationDate = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Zboncak Inc",
                            Title = "input syndicate Officer"
                        },
                        new
                        {
                            ID = 51,
                            Author = "Drew Cremin",
                            Category = "occaecati",
                            CoverPage = "https://picsum.photos/50/50/?image=468",
                            Description = "Perspiciatis perspiciatis deleniti aperiam et exercitationem quibusdam ex occaecati voluptatum fuga qui molestiae vero ex occaecati optio saepe perspiciatis non.",
                            ISBN = 874571550,
                            PageCount = 71,
                            PublicationDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Balistreri - McLaughlin",
                            Title = "Unbranded Village Plastic"
                        },
                        new
                        {
                            ID = 52,
                            Author = "Bianka Ortiz",
                            Category = "eos",
                            CoverPage = "https://picsum.photos/50/50/?image=198",
                            Description = "Laudantium omnis sequi a reiciendis impedit vel dolor sed quas occaecati doloremque ratione et sit praesentium ullam repudiandae omnis qui.",
                            ISBN = 896607343,
                            PageCount = 66,
                            PublicationDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Cummings Inc",
                            Title = "Usability Handcrafted Fresh Bike Illinois"
                        },
                        new
                        {
                            ID = 53,
                            Author = "June Jast",
                            Category = "qui",
                            CoverPage = "https://picsum.photos/50/50/?image=32",
                            Description = "Ea ut occaecati ut doloribus tenetur veritatis et occaecati laborum voluptate quod accusantium recusandae laudantium molestias veniam omnis ducimus quia.",
                            ISBN = 205017409,
                            PageCount = 533,
                            PublicationDate = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schoen - Harber",
                            Title = "Licensed leverage National"
                        },
                        new
                        {
                            ID = 54,
                            Author = "Melyssa Ortiz",
                            Category = "expedita",
                            CoverPage = "https://picsum.photos/50/50/?image=370",
                            Description = "Autem ut dolorem odit quae et voluptas sit minus quibusdam nihil deserunt non earum similique error est dolorem sint dolores.",
                            ISBN = 675981395,
                            PageCount = 324,
                            PublicationDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kunde, Oberbrunner and Weimann",
                            Title = "Hills tangible Refined Plastic Chair"
                        },
                        new
                        {
                            ID = 55,
                            Author = "Brown Hamill",
                            Category = "sunt",
                            CoverPage = "https://picsum.photos/50/50/?image=742",
                            Description = "Sed qui rem unde cupiditate rerum et veritatis nihil autem omnis est maxime qui aut repellat placeat sit saepe dolore.",
                            ISBN = 960387125,
                            PageCount = 525,
                            PublicationDate = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bailey, Crist and Zemlak",
                            Title = "Mall Mauritius Isle"
                        },
                        new
                        {
                            ID = 56,
                            Author = "Sage Miller",
                            Category = "vel",
                            CoverPage = "https://picsum.photos/50/50/?image=743",
                            Description = "Ut magni sapiente exercitationem molestiae ipsam itaque est ea voluptatum nesciunt et necessitatibus officiis expedita beatae et praesentium corrupti et.",
                            ISBN = 473815878,
                            PageCount = 391,
                            PublicationDate = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rutherford - Swift",
                            Title = "Springs plum Buckinghamshire"
                        },
                        new
                        {
                            ID = 57,
                            Author = "Keenan Kirlin",
                            Category = "molestias",
                            CoverPage = "https://picsum.photos/50/50/?image=92",
                            Description = "Ipsa magni dolore doloribus iusto non porro soluta ipsum incidunt aperiam repellendus dolores cupiditate velit nihil et sequi libero quos.",
                            ISBN = 468778975,
                            PageCount = 806,
                            PublicationDate = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mraz Inc",
                            Title = "Pula Berkshire salmon"
                        },
                        new
                        {
                            ID = 58,
                            Author = "Maegan Yundt",
                            Category = "iusto",
                            CoverPage = "https://picsum.photos/50/50/?image=789",
                            Description = "Eum placeat sint illum hic quidem perferendis delectus nam ut aperiam voluptatem est et totam voluptatem consequatur unde officiis et.",
                            ISBN = 509562149,
                            PageCount = 302,
                            PublicationDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mertz LLC",
                            Title = "Rustic Fantastic Wooden Gloves Persevering"
                        },
                        new
                        {
                            ID = 59,
                            Author = "Lonnie Fadel",
                            Category = "tempora",
                            CoverPage = "https://picsum.photos/50/50/?image=202",
                            Description = "Suscipit velit deleniti nesciunt sit sed aliquam magnam sapiente eum quasi impedit aut nulla quia veritatis blanditiis libero et aut.",
                            ISBN = 713484920,
                            PageCount = 172,
                            PublicationDate = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lakin, Ankunding and King",
                            Title = "initiatives Identity Extended"
                        },
                        new
                        {
                            ID = 60,
                            Author = "Dimitri Hyatt",
                            Category = "vel",
                            CoverPage = "https://picsum.photos/50/50/?image=39",
                            Description = "Magni velit accusantium debitis aperiam aliquam est est cumque autem voluptates rerum aut ullam odio corporis suscipit non officia in.",
                            ISBN = 736472718,
                            PageCount = 293,
                            PublicationDate = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Waelchi Group",
                            Title = "Handmade Granite Keyboard infomediaries Intelligent"
                        },
                        new
                        {
                            ID = 61,
                            Author = "Ernest Kautzer",
                            Category = "nisi",
                            CoverPage = "https://picsum.photos/50/50/?image=980",
                            Description = "Corporis ut voluptate aliquid cumque necessitatibus officiis ullam sunt assumenda ullam occaecati et quam veniam ipsam aut tempora dolores praesentium.",
                            ISBN = 693300994,
                            PageCount = 316,
                            PublicationDate = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mann - Dickinson",
                            Title = "optimize Accountability Synchronised"
                        },
                        new
                        {
                            ID = 62,
                            Author = "Clemmie Howe",
                            Category = "neque",
                            CoverPage = "https://picsum.photos/50/50/?image=911",
                            Description = "Maiores quam possimus quia quasi sequi sint aut exercitationem aut maiores perferendis qui provident in nam sit voluptatibus numquam aut.",
                            ISBN = 797742581,
                            PageCount = 785,
                            PublicationDate = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rodriguez, Ortiz and Wunsch",
                            Title = "invoice green payment"
                        },
                        new
                        {
                            ID = 63,
                            Author = "Pierce Harris",
                            Category = "quia",
                            CoverPage = "https://picsum.photos/50/50/?image=189",
                            Description = "Magni dolorum unde aut quo quis dignissimos excepturi enim iure qui eum aut aliquam eos eos tempora officiis praesentium provident.",
                            ISBN = 802344686,
                            PageCount = 868,
                            PublicationDate = new DateTime(2023, 10, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Stiedemann, Davis and Lowe",
                            Title = "Avon Officer Metal"
                        },
                        new
                        {
                            ID = 64,
                            Author = "Wilmer Hilll",
                            Category = "similique",
                            CoverPage = "https://picsum.photos/50/50/?image=651",
                            Description = "In hic ratione totam et quae dolores consequuntur quia est et velit delectus consequatur aut aperiam laudantium sint temporibus impedit.",
                            ISBN = 475049559,
                            PageCount = 819,
                            PublicationDate = new DateTime(2023, 9, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Oberbrunner LLC",
                            Title = "Facilitator port Savings Account"
                        },
                        new
                        {
                            ID = 65,
                            Author = "Kristopher Stamm",
                            Category = "cum",
                            CoverPage = "https://picsum.photos/50/50/?image=806",
                            Description = "Aspernatur dicta ipsum sed quibusdam consequatur eius ea ut cumque dolorum ut ea neque non sit delectus odio officia cum.",
                            ISBN = 118270136,
                            PageCount = 684,
                            PublicationDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Heaney Inc",
                            Title = "Computers & Music Fields connect"
                        },
                        new
                        {
                            ID = 66,
                            Author = "Kyleigh Goyette",
                            Category = "assumenda",
                            CoverPage = "https://picsum.photos/50/50/?image=963",
                            Description = "Temporibus voluptatum numquam fuga id dolorum nihil quia nostrum aut accusantium earum adipisci omnis cupiditate veritatis assumenda et et sed.",
                            ISBN = 238111530,
                            PageCount = 335,
                            PublicationDate = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "O'Reilly, Waters and Prosacco",
                            Title = "Facilitator Pines Internal"
                        },
                        new
                        {
                            ID = 67,
                            Author = "Talon Jones",
                            Category = "est",
                            CoverPage = "https://picsum.photos/50/50/?image=600",
                            Description = "Saepe non iste esse veniam nostrum aut voluptatibus est non perferendis nesciunt porro ab neque molestiae in occaecati minima pariatur.",
                            ISBN = 343004797,
                            PageCount = 922,
                            PublicationDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Little, Huel and Weissnat",
                            Title = "Summit Auto Loan Account Realigned"
                        },
                        new
                        {
                            ID = 68,
                            Author = "Daron Stark",
                            Category = "quo",
                            CoverPage = "https://picsum.photos/50/50/?image=521",
                            Description = "Corrupti ipsa aut dignissimos aut est cumque porro et saepe velit quis rerum a adipisci temporibus vel quia sunt fugit.",
                            ISBN = 395441830,
                            PageCount = 957,
                            PublicationDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Fay - Bradtke",
                            Title = "Chad Nuevo Sol portals"
                        },
                        new
                        {
                            ID = 69,
                            Author = "Trey McDermott",
                            Category = "architecto",
                            CoverPage = "https://picsum.photos/50/50/?image=437",
                            Description = "Qui qui et at minus cupiditate nemo quidem quae veniam similique porro ipsam vero ducimus rerum deserunt dicta dolorem ut.",
                            ISBN = 565510663,
                            PageCount = 950,
                            PublicationDate = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kulas Group",
                            Title = "multi-byte regional Synergized"
                        },
                        new
                        {
                            ID = 70,
                            Author = "Sarah Dibbert",
                            Category = "magni",
                            CoverPage = "https://picsum.photos/50/50/?image=294",
                            Description = "Iure rerum natus sit eos quibusdam ipsum sed sed numquam accusamus soluta quae fuga autem porro praesentium laudantium dolor et.",
                            ISBN = 832986762,
                            PageCount = 698,
                            PublicationDate = new DateTime(2024, 5, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lebsack and Sons",
                            Title = "payment Radial Road"
                        },
                        new
                        {
                            ID = 71,
                            Author = "Alysa Abshire",
                            Category = "nobis",
                            CoverPage = "https://picsum.photos/50/50/?image=513",
                            Description = "Perspiciatis rem aperiam officiis possimus aut similique voluptatem dolorem sapiente delectus voluptatum officia occaecati quia nobis est fugit et dolorem.",
                            ISBN = 500603008,
                            PageCount = 748,
                            PublicationDate = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Parisian, Rice and Shanahan",
                            Title = "Stravenue Manager Burundi Franc"
                        },
                        new
                        {
                            ID = 72,
                            Author = "Wallace White",
                            Category = "vel",
                            CoverPage = "https://picsum.photos/50/50/?image=824",
                            Description = "Ratione nobis ut asperiores et qui vitae amet atque et dolorem voluptates aperiam ipsam perferendis non similique nam autem quo.",
                            ISBN = 460109063,
                            PageCount = 638,
                            PublicationDate = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Nicolas Inc",
                            Title = "Metrics Principal backing up"
                        },
                        new
                        {
                            ID = 73,
                            Author = "Leslie Heidenreich",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=891",
                            Description = "Culpa ut dolorem ea minima voluptatum repellat sint itaque sapiente dolor blanditiis praesentium facilis dicta ea fuga adipisci enim est.",
                            ISBN = 772908609,
                            PageCount = 926,
                            PublicationDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Haag - Kuvalis",
                            Title = "seize bypassing Practical Fresh Chicken"
                        },
                        new
                        {
                            ID = 74,
                            Author = "Jessica Runte",
                            Category = "minima",
                            CoverPage = "https://picsum.photos/50/50/?image=935",
                            Description = "Voluptate veniam sed pariatur ut ex vero dignissimos aliquid quos et repellendus in et nulla est ea dolor voluptate sunt.",
                            ISBN = 168349717,
                            PageCount = 879,
                            PublicationDate = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Durgan - Tromp",
                            Title = "monitoring hack IB"
                        },
                        new
                        {
                            ID = 75,
                            Author = "Winifred Prosacco",
                            Category = "non",
                            CoverPage = "https://picsum.photos/50/50/?image=847",
                            Description = "Debitis fugiat exercitationem omnis et ab ipsa delectus recusandae officia autem non itaque nisi omnis non tempore ut quam nihil.",
                            ISBN = 451447592,
                            PageCount = 516,
                            PublicationDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rutherford - Abbott",
                            Title = "fuchsia Danish Krone bypassing"
                        },
                        new
                        {
                            ID = 76,
                            Author = "Vena Ryan",
                            Category = "qui",
                            CoverPage = "https://picsum.photos/50/50/?image=915",
                            Description = "Laboriosam qui voluptatem adipisci consequatur quo magni atque ut doloremque cum provident quia numquam ex numquam qui odio earum rerum.",
                            ISBN = 157794222,
                            PageCount = 752,
                            PublicationDate = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Nienow and Sons",
                            Title = "syndicate Incredible Arizona"
                        },
                        new
                        {
                            ID = 77,
                            Author = "Reba Graham",
                            Category = "est",
                            CoverPage = "https://picsum.photos/50/50/?image=562",
                            Description = "Est rerum adipisci et quae laboriosam praesentium asperiores quibusdam sit blanditiis et aut magnam possimus quas in ut et voluptas.",
                            ISBN = 793766180,
                            PageCount = 157,
                            PublicationDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ledner Inc",
                            Title = "Facilitator Practical Frozen Fish deposit"
                        },
                        new
                        {
                            ID = 78,
                            Author = "Lew Grant",
                            Category = "quo",
                            CoverPage = "https://picsum.photos/50/50/?image=569",
                            Description = "Itaque optio omnis aut dolor magni libero laboriosam asperiores et nulla voluptate facilis molestiae cum rerum laboriosam facilis eveniet molestiae.",
                            ISBN = 307978537,
                            PageCount = 575,
                            PublicationDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Romaguera Inc",
                            Title = "program enhance primary"
                        },
                        new
                        {
                            ID = 79,
                            Author = "Giuseppe Dach",
                            Category = "molestiae",
                            CoverPage = "https://picsum.photos/50/50/?image=601",
                            Description = "Incidunt modi et nam sapiente repudiandae quibusdam unde sapiente voluptate modi consequatur aperiam nisi commodi molestiae libero et ut repellendus.",
                            ISBN = 382742816,
                            PageCount = 94,
                            PublicationDate = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Dicki - Adams",
                            Title = "reciprocal Ville Data"
                        },
                        new
                        {
                            ID = 80,
                            Author = "Pablo Bergnaum",
                            Category = "totam",
                            CoverPage = "https://picsum.photos/50/50/?image=515",
                            Description = "Maxime et quis officiis et earum possimus quibusdam sed sint quidem possimus deleniti fuga illum suscipit possimus porro nisi incidunt.",
                            ISBN = 295458134,
                            PageCount = 341,
                            PublicationDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Douglas - Simonis",
                            Title = "monetize Clothing, Shoes & Movies Legacy"
                        },
                        new
                        {
                            ID = 81,
                            Author = "Mariane Blick",
                            Category = "sint",
                            CoverPage = "https://picsum.photos/50/50/?image=762",
                            Description = "Officia quos sapiente optio non similique quidem sed totam nemo labore cumque ex voluptate error et quos omnis reprehenderit vel.",
                            ISBN = 306146836,
                            PageCount = 205,
                            PublicationDate = new DateTime(2023, 7, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Armstrong, Dare and Jones",
                            Title = "matrix Creative synthesize"
                        },
                        new
                        {
                            ID = 82,
                            Author = "Rocio Kozey",
                            Category = "nostrum",
                            CoverPage = "https://picsum.photos/50/50/?image=820",
                            Description = "Vel nihil magni earum ducimus debitis qui non aspernatur blanditiis est aut aliquid reiciendis facilis sit sequi voluptatum eum cumque.",
                            ISBN = 573983630,
                            PageCount = 744,
                            PublicationDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Zemlak, Simonis and Walter",
                            Title = "system Fresh invoice"
                        },
                        new
                        {
                            ID = 83,
                            Author = "Heber Grant",
                            Category = "quibusdam",
                            CoverPage = "https://picsum.photos/50/50/?image=376",
                            Description = "Tempora hic harum aut voluptatibus eaque totam sed nihil voluptate iure quia rerum expedita ea et esse nemo velit exercitationem.",
                            ISBN = 814353219,
                            PageCount = 976,
                            PublicationDate = new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Abernathy - Kuhn",
                            Title = "index bluetooth Realigned"
                        },
                        new
                        {
                            ID = 84,
                            Author = "Helena Conroy",
                            Category = "sint",
                            CoverPage = "https://picsum.photos/50/50/?image=797",
                            Description = "Rerum consequatur non sed aut beatae laudantium cum qui ut repellat eum nobis commodi impedit eos enim voluptatum dignissimos blanditiis.",
                            ISBN = 379589015,
                            PageCount = 467,
                            PublicationDate = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Jones - Lebsack",
                            Title = "SDR Burgs Berkshire"
                        },
                        new
                        {
                            ID = 85,
                            Author = "Elva Stamm",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=142",
                            Description = "Fugiat dignissimos earum quos voluptatem ut repellat sit eveniet excepturi illum ab voluptatem facilis explicabo libero quo sint optio enim.",
                            ISBN = 307761354,
                            PageCount = 445,
                            PublicationDate = new DateTime(2023, 11, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Emard, Cruickshank and Senger",
                            Title = "cross-platform Fantastic Soft Sausages object-oriented"
                        },
                        new
                        {
                            ID = 86,
                            Author = "Norwood Yost",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=22",
                            Description = "Expedita nihil soluta accusamus sint dolores sed omnis earum et est distinctio expedita ut voluptate asperiores quam accusantium et cupiditate.",
                            ISBN = 510941172,
                            PageCount = 899,
                            PublicationDate = new DateTime(2023, 10, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Maggio, Wiza and Klein",
                            Title = "bluetooth Sri Lanka Rupee Engineer"
                        },
                        new
                        {
                            ID = 87,
                            Author = "Marlon Schiller",
                            Category = "quos",
                            CoverPage = "https://picsum.photos/50/50/?image=345",
                            Description = "A esse consequatur voluptatem odit voluptatem recusandae dolore repellat consequatur error non facere accusamus non vel dicta ea possimus nulla.",
                            ISBN = 333163989,
                            PageCount = 285,
                            PublicationDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Harris - Jacobson",
                            Title = "encoding Mauritius Grocery"
                        },
                        new
                        {
                            ID = 88,
                            Author = "Cedrick Baumbach",
                            Category = "dolor",
                            CoverPage = "https://picsum.photos/50/50/?image=825",
                            Description = "Iste non consequuntur et labore excepturi aliquid similique dignissimos repudiandae odit voluptatem vel facilis optio necessitatibus unde nesciunt sed eligendi.",
                            ISBN = 473272699,
                            PageCount = 861,
                            PublicationDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Sanford - Leannon",
                            Title = "plug-and-play Computers Product"
                        },
                        new
                        {
                            ID = 89,
                            Author = "Imogene Crona",
                            Category = "nobis",
                            CoverPage = "https://picsum.photos/50/50/?image=174",
                            Description = "Ducimus veniam dolorum vel omnis velit sed quia voluptatibus rem consequuntur aut quibusdam ipsum sit repudiandae voluptatem quia aut rem.",
                            ISBN = 119315221,
                            PageCount = 251,
                            PublicationDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Predovic, Wolff and Veum",
                            Title = "Borders Automotive THX"
                        },
                        new
                        {
                            ID = 90,
                            Author = "Gillian Dach",
                            Category = "ad",
                            CoverPage = "https://picsum.photos/50/50/?image=906",
                            Description = "Est veniam itaque laborum culpa officia iure commodi odit cupiditate blanditiis maiores vitae necessitatibus atque quia corrupti et necessitatibus optio.",
                            ISBN = 930872869,
                            PageCount = 458,
                            PublicationDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mitchell Group",
                            Title = "definition Glen Throughway"
                        },
                        new
                        {
                            ID = 91,
                            Author = "Alvera Padberg",
                            Category = "rem",
                            CoverPage = "https://picsum.photos/50/50/?image=739",
                            Description = "Ad minima nobis rerum amet laborum illo nam dicta sed cupiditate est ea eius beatae quis corporis rerum dolor repellat.",
                            ISBN = 386792259,
                            PageCount = 71,
                            PublicationDate = new DateTime(2023, 11, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Friesen and Sons",
                            Title = "Tasty Steel Sausages Function-based invoice"
                        },
                        new
                        {
                            ID = 92,
                            Author = "Jimmie Collier",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=944",
                            Description = "Quia asperiores repudiandae sunt doloremque vel inventore laudantium ipsum ut expedita consequatur sequi quo quia ipsum quaerat dicta facere occaecati.",
                            ISBN = 400378476,
                            PageCount = 794,
                            PublicationDate = new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Altenwerth and Sons",
                            Title = "cross-platform utilize Tasty"
                        },
                        new
                        {
                            ID = 93,
                            Author = "Claudine Gottlieb",
                            Category = "repellat",
                            CoverPage = "https://picsum.photos/50/50/?image=787",
                            Description = "Repellendus voluptatem sit ut aut laboriosam hic quia praesentium non non amet ut quisquam quos vel esse temporibus eius eum.",
                            ISBN = 732084787,
                            PageCount = 704,
                            PublicationDate = new DateTime(2023, 9, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rohan - Stehr",
                            Title = "Designer Generic Granite Cheese software"
                        },
                        new
                        {
                            ID = 94,
                            Author = "Ervin Collins",
                            Category = "ad",
                            CoverPage = "https://picsum.photos/50/50/?image=96",
                            Description = "Voluptatem et ut magnam aut ratione et est dicta ut pariatur placeat quaerat tempore accusantium voluptatem exercitationem fugiat modi hic.",
                            ISBN = 595649082,
                            PageCount = 117,
                            PublicationDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Dietrich Group",
                            Title = "Architect reintermediate foreground"
                        },
                        new
                        {
                            ID = 95,
                            Author = "Myrtle Bergstrom",
                            Category = "voluptatum",
                            CoverPage = "https://picsum.photos/50/50/?image=786",
                            Description = "Voluptatem maiores sequi voluptas earum aliquid et delectus et totam voluptatem et est ut commodi minima quae minus amet exercitationem.",
                            ISBN = 137684781,
                            PageCount = 195,
                            PublicationDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gutmann - Kerluke",
                            Title = "maximize Tasty Rubber Soap Berkshire"
                        },
                        new
                        {
                            ID = 96,
                            Author = "Kirstin Davis",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=1001",
                            Description = "Omnis qui ducimus sunt placeat veritatis itaque voluptatem accusamus maxime impedit enim ipsa dolore ab nihil officia aut ex incidunt.",
                            ISBN = 676273621,
                            PageCount = 572,
                            PublicationDate = new DateTime(2023, 10, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Zieme - Franecki",
                            Title = "synthesizing indexing disintermediate"
                        },
                        new
                        {
                            ID = 97,
                            Author = "Julia Rau",
                            Category = "aperiam",
                            CoverPage = "https://picsum.photos/50/50/?image=270",
                            Description = "Ea accusamus ea nam quia esse iure id id voluptatum vero natus magnam odio ad libero asperiores quo facilis doloremque.",
                            ISBN = 541963400,
                            PageCount = 383,
                            PublicationDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schinner - Wisozk",
                            Title = "Incredible Frozen Gloves International Wisconsin"
                        },
                        new
                        {
                            ID = 98,
                            Author = "Zackery Hudson",
                            Category = "voluptatum",
                            CoverPage = "https://picsum.photos/50/50/?image=696",
                            Description = "Similique et debitis esse sit natus veniam veritatis est placeat incidunt ducimus ea inventore consequatur qui libero et nisi mollitia.",
                            ISBN = 729986581,
                            PageCount = 672,
                            PublicationDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Abshire - Torp",
                            Title = "Latvia Decentralized Handcrafted Soft Sausages"
                        },
                        new
                        {
                            ID = 99,
                            Author = "Moses Konopelski",
                            Category = "excepturi",
                            CoverPage = "https://picsum.photos/50/50/?image=623",
                            Description = "Voluptatem architecto nobis nostrum nulla harum ex laboriosam mollitia assumenda voluptatum repellat quisquam fugiat quia inventore voluptates sit deserunt iste.",
                            ISBN = 983101595,
                            PageCount = 881,
                            PublicationDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kub, Nolan and Walter",
                            Title = "capability Total contingency"
                        },
                        new
                        {
                            ID = 100,
                            Author = "Jailyn Heathcote",
                            Category = "libero",
                            CoverPage = "https://picsum.photos/50/50/?image=833",
                            Description = "Culpa ea placeat cumque labore tenetur non ut nobis temporibus numquam nihil unde ratione repudiandae voluptatem quasi fuga debitis quia.",
                            ISBN = 374593803,
                            PageCount = 232,
                            PublicationDate = new DateTime(2024, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Jacobson, O'Conner and Lubowitz",
                            Title = "Product Licensed Soft Chair Hill"
                        });
                });

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.UserAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ROLE");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("ID");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.Book", b =>
                {
                    b.HasOne("TechnicalAssessmentRokov.Entities.UserAccount", "CheckedOutBy")
                        .WithMany()
                        .HasForeignKey("CheckedOutById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CheckedOutBy");
                });
#pragma warning restore 612, 618
        }
    }
}
