// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalAssessmentRokov.Data;

#nullable disable

namespace TechnicalAssessmentRokov.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240619171357_UpdateAspNetUserBuilder")]
    partial class UpdateAspNetUserBuilder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUTHOR");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORY");

                    b.Property<int?>("CheckedOutById")
                        .HasColumnType("int")
                        .HasColumnName("CHECKED_OUT_BY");

                    b.Property<DateTime?>("CheckedOutDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CHECKED_OUT_DATE");

                    b.Property<string>("CoverPage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COVER_PAGE");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DUE_DATE");

                    b.Property<int>("ISBN")
                        .HasColumnType("int")
                        .HasColumnName("ISBN");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("PAGE_COUNT");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PUBLICATION_DATE");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PUBLISHER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.HasKey("ID");

                    b.HasIndex("CheckedOutById");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Julian Larkin",
                            Category = "eos",
                            CoverPage = "https://picsum.photos/50/50/?image=608",
                            Description = "Itaque temporibus et corporis officia distinctio et rerum architecto voluptatem vitae quo alias incidunt tempore aut qui provident nisi ut.",
                            ISBN = 378302538,
                            PageCount = 335,
                            PublicationDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kirlin - Kozey",
                            Title = "Mall sensor Rustic Granite Ball"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Sarina Conn",
                            Category = "occaecati",
                            CoverPage = "https://picsum.photos/50/50/?image=226",
                            Description = "Debitis esse inventore sed omnis sint unde molestiae beatae blanditiis quia nemo laudantium aut repellat consectetur aut illo accusantium vel.",
                            ISBN = 929327994,
                            PageCount = 202,
                            PublicationDate = new DateTime(2023, 7, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "White Inc",
                            Title = "compress front-end pink"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Mable O'Reilly",
                            Category = "error",
                            CoverPage = "https://picsum.photos/50/50/?image=52",
                            Description = "Deserunt doloremque ut quo mollitia iusto fugiat qui aut sit sapiente adipisci ex minus nam modi eius sapiente omnis aliquid.",
                            ISBN = 464735430,
                            PageCount = 214,
                            PublicationDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Graham - Grimes",
                            Title = "calculate infomediaries Frozen"
                        },
                        new
                        {
                            ID = 4,
                            Author = "Ian Wisozk",
                            Category = "voluptas",
                            CoverPage = "https://picsum.photos/50/50/?image=682",
                            Description = "Molestias quia omnis minima aut ipsum voluptatem facilis sed deserunt vel tempora cupiditate ut quia commodi nihil quia nulla aliquid.",
                            ISBN = 987456834,
                            PageCount = 650,
                            PublicationDate = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bogisich - Wolff",
                            Title = "firewall killer Turnpike"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Jayne Nienow",
                            Category = "omnis",
                            CoverPage = "https://picsum.photos/50/50/?image=993",
                            Description = "Consectetur voluptatem autem qui minus vel ipsum aliquam repellat sint est alias rerum velit quia tenetur quam repellendus tempore possimus.",
                            ISBN = 184673319,
                            PageCount = 129,
                            PublicationDate = new DateTime(2023, 12, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Reichert LLC",
                            Title = "Island Future Land"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Meredith Heidenreich",
                            Category = "quia",
                            CoverPage = "https://picsum.photos/50/50/?image=264",
                            Description = "Voluptatem rerum velit sed maiores rerum aut veniam repellendus aut in facere culpa aliquid ut nam molestias commodi est quidem.",
                            ISBN = 333902878,
                            PageCount = 318,
                            PublicationDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ryan Inc",
                            Title = "superstructure Group Concrete"
                        },
                        new
                        {
                            ID = 7,
                            Author = "Sammie Dach",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=1026",
                            Description = "Et aut non rem explicabo ratione exercitationem mollitia maxime voluptates et aut beatae dolorum cum in iusto et ducimus nihil.",
                            ISBN = 218501139,
                            PageCount = 641,
                            PublicationDate = new DateTime(2023, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Durgan, Stokes and King",
                            Title = "Handmade client-driven Savings Account"
                        },
                        new
                        {
                            ID = 8,
                            Author = "Rose Kub",
                            Category = "quod",
                            CoverPage = "https://picsum.photos/50/50/?image=379",
                            Description = "Sed eum pariatur minus explicabo maiores non eum dignissimos eius molestiae facilis ducimus consequatur odit est possimus qui ea non.",
                            ISBN = 534815811,
                            PageCount = 450,
                            PublicationDate = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "O'Conner, Gusikowski and Cremin",
                            Title = "Grocery, Sports & Clothing bypassing Chief"
                        },
                        new
                        {
                            ID = 9,
                            Author = "Luisa Feest",
                            Category = "iusto",
                            CoverPage = "https://picsum.photos/50/50/?image=614",
                            Description = "Voluptates eum totam voluptatibus non omnis quia repellat magni vel ut voluptatem sit rerum expedita est necessitatibus dignissimos modi in.",
                            ISBN = 330524164,
                            PageCount = 644,
                            PublicationDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Braun - Jerde",
                            Title = "envisioneer Mississippi systemic"
                        },
                        new
                        {
                            ID = 10,
                            Author = "Giles Shields",
                            Category = "corrupti",
                            CoverPage = "https://picsum.photos/50/50/?image=900",
                            Description = "Magnam consequuntur suscipit non incidunt unde corrupti velit voluptatibus facere delectus facere voluptatibus molestias ad quos officia quibusdam tempora at.",
                            ISBN = 644586473,
                            PageCount = 434,
                            PublicationDate = new DateTime(2023, 7, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schiller - Batz",
                            Title = "interface Infrastructure Rue"
                        },
                        new
                        {
                            ID = 11,
                            Author = "Clifton Wilderman",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=252",
                            Description = "Maxime autem perferendis temporibus rerum non fuga aliquam fuga veniam omnis voluptatibus asperiores ullam voluptate ab accusantium sed quos eos.",
                            ISBN = 666294381,
                            PageCount = 98,
                            PublicationDate = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schmidt Group",
                            Title = "Pennsylvania tan compressing"
                        },
                        new
                        {
                            ID = 12,
                            Author = "Maria Labadie",
                            Category = "quisquam",
                            CoverPage = "https://picsum.photos/50/50/?image=994",
                            Description = "Amet dolores libero facilis quis quo veritatis est sit deleniti sit ratione repellendus nesciunt laboriosam est dolorum iure quod a.",
                            ISBN = 579623285,
                            PageCount = 125,
                            PublicationDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kuhn LLC",
                            Title = "infomediaries Home Loan Account Small Wooden Shirt"
                        },
                        new
                        {
                            ID = 13,
                            Author = "Myrtie McKenzie",
                            Category = "soluta",
                            CoverPage = "https://picsum.photos/50/50/?image=853",
                            Description = "Provident dolores ut soluta tenetur sed vel quos voluptas ut explicabo cum sint corrupti aut eum sed harum sed doloremque.",
                            ISBN = 448895106,
                            PageCount = 168,
                            PublicationDate = new DateTime(2023, 12, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Nicolas Inc",
                            Title = "encryption Prairie cross-platform"
                        },
                        new
                        {
                            ID = 14,
                            Author = "Philip McGlynn",
                            Category = "quo",
                            CoverPage = "https://picsum.photos/50/50/?image=403",
                            Description = "Enim rem ut debitis aut et aut ut recusandae provident et ut est at est est quidem voluptatum aliquid non.",
                            ISBN = 494114575,
                            PageCount = 460,
                            PublicationDate = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Cormier - Zemlak",
                            Title = "Utah reciprocal Research"
                        },
                        new
                        {
                            ID = 15,
                            Author = "Demetrius Weimann",
                            Category = "rerum",
                            CoverPage = "https://picsum.photos/50/50/?image=796",
                            Description = "Totam id animi quasi cum praesentium vero quis distinctio beatae tenetur consequatur laboriosam iste vel adipisci et cum cumque laboriosam.",
                            ISBN = 226842779,
                            PageCount = 963,
                            PublicationDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schamberger Inc",
                            Title = "Courts static alarm"
                        },
                        new
                        {
                            ID = 16,
                            Author = "Arvilla Tromp",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=621",
                            Description = "Omnis molestiae dolores laudantium delectus similique consequatur quaerat dolores architecto non delectus sed debitis autem consequatur qui aspernatur aut et.",
                            ISBN = 517229614,
                            PageCount = 871,
                            PublicationDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Greenfelder, Prosacco and Heller",
                            Title = "Utah customized Belize Dollar"
                        },
                        new
                        {
                            ID = 17,
                            Author = "May Jacobi",
                            Category = "hic",
                            CoverPage = "https://picsum.photos/50/50/?image=899",
                            Description = "Ratione sequi eos ratione quae qui voluptas ex dolor ut sint repellendus earum cum et et quia omnis consectetur quod.",
                            ISBN = 296538957,
                            PageCount = 376,
                            PublicationDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Jast - Miller",
                            Title = "integrate Garden & Health Grocery, Jewelery & Shoes"
                        },
                        new
                        {
                            ID = 18,
                            Author = "Magdalen Gerhold",
                            Category = "veritatis",
                            CoverPage = "https://picsum.photos/50/50/?image=733",
                            Description = "Rem iure neque quidem eos quo aut facilis quod nesciunt voluptates temporibus sapiente ad natus non nesciunt voluptatibus quo rerum.",
                            ISBN = 284020309,
                            PageCount = 716,
                            PublicationDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Nolan Group",
                            Title = "Regional Incredible Soft Chips object-oriented"
                        },
                        new
                        {
                            ID = 19,
                            Author = "Royal Dietrich",
                            Category = "officiis",
                            CoverPage = "https://picsum.photos/50/50/?image=14",
                            Description = "Vel quia eum et ea eum voluptatem enim aspernatur est mollitia quis ut id ad similique esse quo recusandae explicabo.",
                            ISBN = 757066939,
                            PageCount = 789,
                            PublicationDate = new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "O'Keefe - Ankunding",
                            Title = "Granite Mobility interfaces"
                        },
                        new
                        {
                            ID = 20,
                            Author = "Dayna Buckridge",
                            Category = "omnis",
                            CoverPage = "https://picsum.photos/50/50/?image=274",
                            Description = "Maxime ex distinctio eos magni et quisquam omnis nostrum nulla est optio aut sit et vel similique rerum nostrum incidunt.",
                            ISBN = 277667559,
                            PageCount = 123,
                            PublicationDate = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hackett Inc",
                            Title = "AI Credit Card Account hacking"
                        },
                        new
                        {
                            ID = 21,
                            Author = "Rosalyn Prosacco",
                            Category = "praesentium",
                            CoverPage = "https://picsum.photos/50/50/?image=1051",
                            Description = "Voluptatum aliquid atque distinctio beatae non optio repellat itaque accusantium delectus fugiat eos neque dolor quas numquam temporibus dolor maxime.",
                            ISBN = 955494434,
                            PageCount = 291,
                            PublicationDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kreiger - Kreiger",
                            Title = "France Group Refined"
                        },
                        new
                        {
                            ID = 22,
                            Author = "Sim Zemlak",
                            Category = "tenetur",
                            CoverPage = "https://picsum.photos/50/50/?image=600",
                            Description = "Nihil rerum libero quaerat illo cum blanditiis explicabo nostrum quos qui suscipit molestiae pariatur eligendi maxime dicta illo hic repudiandae.",
                            ISBN = 199137979,
                            PageCount = 910,
                            PublicationDate = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Collier, Stiedemann and Marvin",
                            Title = "Island dynamic green"
                        },
                        new
                        {
                            ID = 23,
                            Author = "Brenden Schuster",
                            Category = "eveniet",
                            CoverPage = "https://picsum.photos/50/50/?image=324",
                            Description = "Velit in sit a harum enim ut magni velit enim qui optio iusto quam et excepturi aut iure animi sint.",
                            ISBN = 816890063,
                            PageCount = 571,
                            PublicationDate = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lindgren - Ward",
                            Title = "open-source Beauty JSON"
                        },
                        new
                        {
                            ID = 24,
                            Author = "Rodger Zieme",
                            Category = "facilis",
                            CoverPage = "https://picsum.photos/50/50/?image=987",
                            Description = "Doloremque dolorem velit sint fugiat quas praesentium pariatur saepe accusamus repudiandae officia temporibus aspernatur quas culpa dolorum qui maxime consequatur.",
                            ISBN = 143632190,
                            PageCount = 659,
                            PublicationDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ankunding Group",
                            Title = "monitor green navigate"
                        },
                        new
                        {
                            ID = 25,
                            Author = "Mya Kassulke",
                            Category = "eos",
                            CoverPage = "https://picsum.photos/50/50/?image=265",
                            Description = "Et aperiam voluptas perferendis consequatur et tenetur repudiandae itaque placeat eum et at veritatis eos sint consequatur consequuntur debitis sit.",
                            ISBN = 810216456,
                            PageCount = 274,
                            PublicationDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Pollich, Gutmann and Barrows",
                            Title = "Planner Health & Computers Bouvet Island (Bouvetoya)"
                        },
                        new
                        {
                            ID = 26,
                            Author = "Madaline Romaguera",
                            Category = "magni",
                            CoverPage = "https://picsum.photos/50/50/?image=302",
                            Description = "Accusamus incidunt quia vel rerum quidem at quae dolores officia alias tempore nesciunt consequatur explicabo provident maxime voluptatem deserunt soluta.",
                            ISBN = 782745621,
                            PageCount = 827,
                            PublicationDate = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schowalter - Lehner",
                            Title = "Surinam Dollar connecting RSS"
                        },
                        new
                        {
                            ID = 27,
                            Author = "Janick Brown",
                            Category = "quibusdam",
                            CoverPage = "https://picsum.photos/50/50/?image=537",
                            Description = "Tempora ut est totam quisquam nihil deleniti et ullam provident et minus fugit odio impedit aut possimus possimus minima temporibus.",
                            ISBN = 573708375,
                            PageCount = 937,
                            PublicationDate = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Will - Zboncak",
                            Title = "Village aggregate Coordinator"
                        },
                        new
                        {
                            ID = 28,
                            Author = "Chanelle Haag",
                            Category = "soluta",
                            CoverPage = "https://picsum.photos/50/50/?image=399",
                            Description = "Occaecati qui fugit consequatur enim eveniet nam voluptas in atque amet iure veniam aut quis sit repellendus animi enim aut.",
                            ISBN = 519569482,
                            PageCount = 577,
                            PublicationDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Labadie - Hansen",
                            Title = "parse Multi-tiered functionalities"
                        },
                        new
                        {
                            ID = 29,
                            Author = "Aimee Pacocha",
                            Category = "eius",
                            CoverPage = "https://picsum.photos/50/50/?image=618",
                            Description = "Adipisci aut ut quisquam rerum ut vitae praesentium consectetur dolore voluptas rerum excepturi iusto nostrum voluptas amet consequatur sint odio.",
                            ISBN = 595563017,
                            PageCount = 873,
                            PublicationDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Goyette - Runolfsdottir",
                            Title = "Checking Account Intelligent Frozen Cheese monitor"
                        },
                        new
                        {
                            ID = 30,
                            Author = "Ron Wolf",
                            Category = "beatae",
                            CoverPage = "https://picsum.photos/50/50/?image=337",
                            Description = "Recusandae eum cupiditate quidem dignissimos ipsum porro quia minus quidem suscipit optio in alias consectetur nostrum dignissimos qui et ut.",
                            ISBN = 630970495,
                            PageCount = 750,
                            PublicationDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schaden, Leffler and Paucek",
                            Title = "Kuwait incubate Bolivia"
                        },
                        new
                        {
                            ID = 31,
                            Author = "Edison Lindgren",
                            Category = "eius",
                            CoverPage = "https://picsum.photos/50/50/?image=1007",
                            Description = "Facilis porro sit aut molestiae nihil magnam ut ullam labore nam animi ea perspiciatis et quam molestias doloremque repudiandae sunt.",
                            ISBN = 378412378,
                            PageCount = 876,
                            PublicationDate = new DateTime(2023, 9, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Roberts Inc",
                            Title = "Central engage bypass"
                        },
                        new
                        {
                            ID = 32,
                            Author = "Arthur Lakin",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=989",
                            Description = "Nihil tenetur quo qui autem architecto voluptatem aut itaque cumque ad maiores et ut amet repellendus delectus error facere cupiditate.",
                            ISBN = 545911813,
                            PageCount = 394,
                            PublicationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Murazik - Connelly",
                            Title = "Awesome web-enabled monetize"
                        },
                        new
                        {
                            ID = 33,
                            Author = "Jarrod Botsford",
                            Category = "voluptatem",
                            CoverPage = "https://picsum.photos/50/50/?image=691",
                            Description = "Consequuntur fugit quisquam et officiis necessitatibus quod inventore molestiae ut minima dolorum assumenda et et rerum eius est dolorem tempore.",
                            ISBN = 395169364,
                            PageCount = 746,
                            PublicationDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kuhn, Leuschke and Nienow",
                            Title = "seize client-driven SMTP"
                        },
                        new
                        {
                            ID = 34,
                            Author = "Treva Emard",
                            Category = "consequuntur",
                            CoverPage = "https://picsum.photos/50/50/?image=952",
                            Description = "Neque sed corporis velit dolore quas earum similique dolor dicta velit quis harum minima velit quidem qui aut odio dolores.",
                            ISBN = 880662422,
                            PageCount = 322,
                            PublicationDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ratke - Huels",
                            Title = "AGP Small Cotton Chips Awesome"
                        },
                        new
                        {
                            ID = 35,
                            Author = "Lucas Mitchell",
                            Category = "iure",
                            CoverPage = "https://picsum.photos/50/50/?image=284",
                            Description = "Quas eum sint voluptatibus nisi sed dolor corporis nihil dicta voluptatem molestiae voluptate delectus amet magni praesentium fuga ea enim.",
                            ISBN = 681788852,
                            PageCount = 458,
                            PublicationDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mann, Kuhn and Tremblay",
                            Title = "XSS parallelism New Caledonia"
                        },
                        new
                        {
                            ID = 36,
                            Author = "Mitchell Vandervort",
                            Category = "consectetur",
                            CoverPage = "https://picsum.photos/50/50/?image=212",
                            Description = "In non dicta dolores aliquam asperiores omnis est nam doloremque et ipsam a enim magni occaecati nulla eum inventore occaecati.",
                            ISBN = 401590970,
                            PageCount = 110,
                            PublicationDate = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Thompson - Kuphal",
                            Title = "Mandatory quantifying bottom-line"
                        },
                        new
                        {
                            ID = 37,
                            Author = "Clair Donnelly",
                            Category = "ullam",
                            CoverPage = "https://picsum.photos/50/50/?image=524",
                            Description = "Expedita est qui labore non cupiditate voluptatem numquam voluptatem praesentium voluptatem dolores recusandae dolores minima hic aut dolores et accusamus.",
                            ISBN = 255018820,
                            PageCount = 491,
                            PublicationDate = new DateTime(2024, 4, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Cummings Inc",
                            Title = "New Israeli Sheqel olive Analyst"
                        },
                        new
                        {
                            ID = 38,
                            Author = "Alexandro Welch",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=655",
                            Description = "Veritatis consectetur animi et perspiciatis explicabo qui est a nostrum ducimus mollitia ratione et non assumenda odit reprehenderit rerum unde.",
                            ISBN = 356697747,
                            PageCount = 112,
                            PublicationDate = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Jakubowski, Marvin and McLaughlin",
                            Title = "Sri Lanka Rupee Fantastic Wooden Shoes incremental"
                        },
                        new
                        {
                            ID = 39,
                            Author = "Jerrod Jast",
                            Category = "provident",
                            CoverPage = "https://picsum.photos/50/50/?image=530",
                            Description = "Commodi assumenda porro aliquid cumque asperiores voluptatem architecto eos voluptatem numquam et et quia vitae harum impedit iste dolorum est.",
                            ISBN = 424901638,
                            PageCount = 278,
                            PublicationDate = new DateTime(2024, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kris and Sons",
                            Title = "Human communities silver"
                        },
                        new
                        {
                            ID = 40,
                            Author = "Julie Hegmann",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=937",
                            Description = "Rerum minus in eveniet necessitatibus ut sed optio quasi placeat et in hic molestiae voluptas praesentium sed dolorum quibusdam facilis.",
                            ISBN = 741816976,
                            PageCount = 470,
                            PublicationDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rohan - Yost",
                            Title = "Home Loan Account quantify Investment Account"
                        },
                        new
                        {
                            ID = 41,
                            Author = "Amos Hodkiewicz",
                            Category = "voluptas",
                            CoverPage = "https://picsum.photos/50/50/?image=277",
                            Description = "Sit dolorem sit necessitatibus facilis animi quasi vero vitae ex et sit ullam eos repellat quia recusandae qui nulla qui.",
                            ISBN = 747318060,
                            PageCount = 185,
                            PublicationDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Halvorson Inc",
                            Title = "National calculating Solomon Islands"
                        },
                        new
                        {
                            ID = 42,
                            Author = "Maeve Bins",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=687",
                            Description = "Vel consectetur ea architecto in consequatur modi nemo nulla maiores tempora quia ut ipsa earum error voluptas quisquam inventore enim.",
                            ISBN = 243065495,
                            PageCount = 945,
                            PublicationDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Stracke, Labadie and Bechtelar",
                            Title = "Handmade Fresh Soap projection copying"
                        },
                        new
                        {
                            ID = 43,
                            Author = "Price Rohan",
                            Category = "maxime",
                            CoverPage = "https://picsum.photos/50/50/?image=668",
                            Description = "Quia voluptate similique perspiciatis libero praesentium quia quas et consequatur voluptatem impedit voluptatum rerum excepturi sed eius consectetur at ad.",
                            ISBN = 195605755,
                            PageCount = 989,
                            PublicationDate = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rogahn, Ziemann and Fay",
                            Title = "well-modulated extend Analyst"
                        },
                        new
                        {
                            ID = 44,
                            Author = "Melany Padberg",
                            Category = "saepe",
                            CoverPage = "https://picsum.photos/50/50/?image=687",
                            Description = "Rerum ducimus ut sit repellat non consequuntur non possimus aut officia quia voluptas cumque quia quam facere eveniet et omnis.",
                            ISBN = 122213458,
                            PageCount = 327,
                            PublicationDate = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Watsica, Hamill and Kassulke",
                            Title = "gold Savings Account schemas"
                        },
                        new
                        {
                            ID = 45,
                            Author = "Vita Jaskolski",
                            Category = "laboriosam",
                            CoverPage = "https://picsum.photos/50/50/?image=623",
                            Description = "Aperiam aspernatur tempora ut doloremque nesciunt velit et ab ea deleniti commodi veniam et eius quos hic consequatur rerum sed.",
                            ISBN = 880634414,
                            PageCount = 155,
                            PublicationDate = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Dare - Hegmann",
                            Title = "Licensed Buckinghamshire Plastic"
                        },
                        new
                        {
                            ID = 46,
                            Author = "Sheldon Medhurst",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=494",
                            Description = "Nisi ab vero dolor soluta et debitis quam eum illum odio mollitia nisi iure amet velit dolore tempora recusandae quo.",
                            ISBN = 223890778,
                            PageCount = 146,
                            PublicationDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bergnaum LLC",
                            Title = "quantifying 4th generation Personal Loan Account"
                        },
                        new
                        {
                            ID = 47,
                            Author = "Emilio Lesch",
                            Category = "reprehenderit",
                            CoverPage = "https://picsum.photos/50/50/?image=63",
                            Description = "Et eos distinctio doloremque molestiae accusamus cupiditate nulla quidem commodi quo architecto voluptas voluptate harum omnis quia ducimus voluptas aliquam.",
                            ISBN = 817876164,
                            PageCount = 437,
                            PublicationDate = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Franecki and Sons",
                            Title = "Hawaii XML radical"
                        },
                        new
                        {
                            ID = 48,
                            Author = "Coy Abbott",
                            Category = "sit",
                            CoverPage = "https://picsum.photos/50/50/?image=112",
                            Description = "Nam necessitatibus et et assumenda modi enim impedit blanditiis dignissimos ut molestias eum id fugit quas error ipsum totam eos.",
                            ISBN = 726259145,
                            PageCount = 826,
                            PublicationDate = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Strosin - Considine",
                            Title = "Lead Down-sized Internal"
                        },
                        new
                        {
                            ID = 49,
                            Author = "Javon Beer",
                            Category = "maxime",
                            CoverPage = "https://picsum.photos/50/50/?image=808",
                            Description = "Quaerat id voluptatem cum sunt soluta perspiciatis officia ea nihil quisquam dolorem doloremque minima vel sed maiores totam impedit commodi.",
                            ISBN = 266029729,
                            PageCount = 478,
                            PublicationDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kuhlman Inc",
                            Title = "silver Computers, Baby & Beauty networks"
                        },
                        new
                        {
                            ID = 50,
                            Author = "Allan Wintheiser",
                            Category = "dignissimos",
                            CoverPage = "https://picsum.photos/50/50/?image=1031",
                            Description = "Omnis corporis eveniet saepe ut facilis officiis quae repudiandae quia eos impedit vel deserunt adipisci qui ullam qui quam eligendi.",
                            ISBN = 851319794,
                            PageCount = 416,
                            PublicationDate = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gerhold - Cremin",
                            Title = "Compatible deploy European Unit of Account 17(E.U.A.-17)"
                        },
                        new
                        {
                            ID = 51,
                            Author = "Jeromy Barrows",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=525",
                            Description = "Veritatis rerum excepturi cupiditate autem nobis quasi eligendi officiis dolore vel nostrum eos dolores reprehenderit voluptatem laboriosam aperiam laudantium ex.",
                            ISBN = 227133854,
                            PageCount = 940,
                            PublicationDate = new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Becker - Borer",
                            Title = "next-generation Officer Fresh"
                        },
                        new
                        {
                            ID = 52,
                            Author = "Gail Brakus",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=452",
                            Description = "Dolorem odio est explicabo quibusdam quos sunt a veritatis quis nihil officia dolores illum repudiandae delectus distinctio consequatur magni sint.",
                            ISBN = 372206607,
                            PageCount = 720,
                            PublicationDate = new DateTime(2023, 11, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hahn LLC",
                            Title = "Optimization Credit Card Account system engine"
                        },
                        new
                        {
                            ID = 53,
                            Author = "Estella Lesch",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=914",
                            Description = "Tempora voluptatem dicta iure ea aperiam nulla numquam velit dicta molestiae accusantium ea quia rerum dolorem aut qui rem repudiandae.",
                            ISBN = 998758096,
                            PageCount = 749,
                            PublicationDate = new DateTime(2023, 11, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Heller, Crist and Haley",
                            Title = "RSS Refined Cotton Ball Steel"
                        },
                        new
                        {
                            ID = 54,
                            Author = "Jamir Mertz",
                            Category = "sit",
                            CoverPage = "https://picsum.photos/50/50/?image=611",
                            Description = "Qui atque voluptate consequatur aut sit ab temporibus quo culpa minus quasi saepe deleniti sed unde unde expedita est vitae.",
                            ISBN = 640770888,
                            PageCount = 768,
                            PublicationDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Wolf, Schuppe and Terry",
                            Title = "Kina focus group Personal Loan Account"
                        },
                        new
                        {
                            ID = 55,
                            Author = "Kevin Nitzsche",
                            Category = "nihil",
                            CoverPage = "https://picsum.photos/50/50/?image=924",
                            Description = "Quaerat explicabo id magnam id sint quia sequi et ex nobis ut tempora ut sit aut libero aperiam est pariatur.",
                            ISBN = 213056899,
                            PageCount = 308,
                            PublicationDate = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Robel, Welch and Russel",
                            Title = "Baby cutting-edge Awesome"
                        },
                        new
                        {
                            ID = 56,
                            Author = "Ashleigh Rice",
                            Category = "nulla",
                            CoverPage = "https://picsum.photos/50/50/?image=277",
                            Description = "Mollitia omnis et facilis accusamus mollitia cupiditate suscipit accusamus maxime optio autem veniam officia doloribus recusandae beatae qui iste sit.",
                            ISBN = 581973747,
                            PageCount = 144,
                            PublicationDate = new DateTime(2023, 11, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bauch Inc",
                            Title = "auxiliary Music Ferry"
                        },
                        new
                        {
                            ID = 57,
                            Author = "Fay DuBuque",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=538",
                            Description = "Maxime unde voluptatem culpa est unde temporibus illo sit perspiciatis et velit velit quibusdam sit voluptatem nisi dolor omnis quas.",
                            ISBN = 837777195,
                            PageCount = 418,
                            PublicationDate = new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Watsica, Cummerata and Fay",
                            Title = "microchip New York Fantastic Concrete Chicken"
                        },
                        new
                        {
                            ID = 58,
                            Author = "Nyasia McClure",
                            Category = "similique",
                            CoverPage = "https://picsum.photos/50/50/?image=305",
                            Description = "Quibusdam quam est esse fugiat et animi veniam cumque illum qui et enim omnis aliquid eveniet voluptas totam aut dignissimos.",
                            ISBN = 618020891,
                            PageCount = 444,
                            PublicationDate = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Sporer - Smith",
                            Title = "input Unions payment"
                        },
                        new
                        {
                            ID = 59,
                            Author = "Angelo Cruickshank",
                            Category = "nisi",
                            CoverPage = "https://picsum.photos/50/50/?image=992",
                            Description = "Commodi ab quis numquam et maxime est ea repudiandae reiciendis quia ut dolores commodi earum et voluptas corrupti non asperiores.",
                            ISBN = 684950801,
                            PageCount = 746,
                            PublicationDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bogan, Sawayn and Ratke",
                            Title = "Fresh Synergistic program"
                        },
                        new
                        {
                            ID = 60,
                            Author = "Georgette Harris",
                            Category = "quis",
                            CoverPage = "https://picsum.photos/50/50/?image=873",
                            Description = "Eos reiciendis nobis tenetur voluptates sequi veniam aut nihil nostrum accusantium et rem et omnis quaerat dignissimos voluptatum ex tenetur.",
                            ISBN = 308250414,
                            PageCount = 625,
                            PublicationDate = new DateTime(2023, 10, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bayer - Grimes",
                            Title = "Rubber Shoal North Carolina"
                        },
                        new
                        {
                            ID = 61,
                            Author = "Aaliyah Kutch",
                            Category = "nam",
                            CoverPage = "https://picsum.photos/50/50/?image=532",
                            Description = "Voluptatem debitis qui est sed odit rem atque unde commodi modi dolorem occaecati sit alias velit voluptatem ipsa quidem laboriosam.",
                            ISBN = 529367694,
                            PageCount = 242,
                            PublicationDate = new DateTime(2024, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Flatley - Sporer",
                            Title = "Wooden transition Throughway"
                        },
                        new
                        {
                            ID = 62,
                            Author = "Bell Rippin",
                            Category = "sit",
                            CoverPage = "https://picsum.photos/50/50/?image=307",
                            Description = "Quis dicta fugit est ea exercitationem optio magnam nemo animi unde repellat hic dicta nam totam debitis ut laudantium aliquid.",
                            ISBN = 718403275,
                            PageCount = 934,
                            PublicationDate = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rodriguez and Sons",
                            Title = "fuchsia Regional Cambridgeshire"
                        },
                        new
                        {
                            ID = 63,
                            Author = "Jeffrey Purdy",
                            Category = "excepturi",
                            CoverPage = "https://picsum.photos/50/50/?image=108",
                            Description = "Similique omnis laudantium libero sint excepturi non vero eum fugit iure qui cupiditate inventore tempora placeat itaque rem eos dolorem.",
                            ISBN = 637885396,
                            PageCount = 515,
                            PublicationDate = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mertz, Considine and Hills",
                            Title = "generating Data Drive"
                        },
                        new
                        {
                            ID = 64,
                            Author = "Salma Treutel",
                            Category = "veritatis",
                            CoverPage = "https://picsum.photos/50/50/?image=300",
                            Description = "Qui aut corporis rerum voluptatem officia consequatur occaecati et fuga laborum earum aut ut eaque cum atque ut dolores quidem.",
                            ISBN = 875980996,
                            PageCount = 767,
                            PublicationDate = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mertz - Nitzsche",
                            Title = "ADP didactic Tasty Steel Towels"
                        },
                        new
                        {
                            ID = 65,
                            Author = "Reinhold Reynolds",
                            Category = "asperiores",
                            CoverPage = "https://picsum.photos/50/50/?image=909",
                            Description = "Ut quis sed aut libero a eos saepe consequatur nulla quo eos magnam voluptatem sit et veniam ipsum corporis reprehenderit.",
                            ISBN = 999150930,
                            PageCount = 269,
                            PublicationDate = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Reichert - Flatley",
                            Title = "Nakfa hack Intelligent Cotton Mouse"
                        },
                        new
                        {
                            ID = 66,
                            Author = "Sean Zboncak",
                            Category = "molestias",
                            CoverPage = "https://picsum.photos/50/50/?image=63",
                            Description = "Quo velit repellendus id mollitia rerum aperiam iusto sit nisi saepe est labore et quidem harum ut natus ab voluptatem.",
                            ISBN = 288829798,
                            PageCount = 142,
                            PublicationDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Beer - Jerde",
                            Title = "firewall cutting-edge back-end"
                        },
                        new
                        {
                            ID = 67,
                            Author = "Kaleigh Mills",
                            Category = "id",
                            CoverPage = "https://picsum.photos/50/50/?image=948",
                            Description = "Qui inventore aut debitis ad occaecati in deserunt sit nobis quia repellat voluptates tenetur nam ratione eaque dolores pariatur error.",
                            ISBN = 302353386,
                            PageCount = 151,
                            PublicationDate = new DateTime(2023, 7, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Zboncak, Toy and Ledner",
                            Title = "Awesome Rubber Chicken Diverse Ville"
                        },
                        new
                        {
                            ID = 68,
                            Author = "Bobbie Veum",
                            Category = "molestias",
                            CoverPage = "https://picsum.photos/50/50/?image=473",
                            Description = "Eum magnam saepe sint et sed fugiat distinctio quae quia illum eos explicabo doloremque incidunt ea excepturi nemo est voluptatibus.",
                            ISBN = 226104486,
                            PageCount = 602,
                            PublicationDate = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "VonRueden and Sons",
                            Title = "wireless Small Tala"
                        },
                        new
                        {
                            ID = 69,
                            Author = "Lynn Hammes",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=946",
                            Description = "Iure omnis et rem eos asperiores libero ut sit est expedita rerum consequatur iste qui iste non dolorem dolor quas.",
                            ISBN = 240101214,
                            PageCount = 891,
                            PublicationDate = new DateTime(2024, 5, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Abshire - Gutmann",
                            Title = "International Automotive, Health & Games deposit"
                        },
                        new
                        {
                            ID = 70,
                            Author = "Jamison Walter",
                            Category = "iusto",
                            CoverPage = "https://picsum.photos/50/50/?image=375",
                            Description = "Ut iure sint voluptatem doloribus sed velit tempore voluptatem tempore illum consectetur reprehenderit adipisci iusto voluptas est cum reprehenderit quos.",
                            ISBN = 488836942,
                            PageCount = 496,
                            PublicationDate = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Walsh and Sons",
                            Title = "Maldives upward-trending reinvent"
                        },
                        new
                        {
                            ID = 71,
                            Author = "Alana Hettinger",
                            Category = "rerum",
                            CoverPage = "https://picsum.photos/50/50/?image=777",
                            Description = "Non consequatur velit a sequi eos ut molestias et vel qui non possimus aperiam aut qui sint est odio libero.",
                            ISBN = 401155886,
                            PageCount = 370,
                            PublicationDate = new DateTime(2023, 7, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kerluke LLC",
                            Title = "Investment Account Movies orange"
                        },
                        new
                        {
                            ID = 72,
                            Author = "Hettie Ruecker",
                            Category = "recusandae",
                            CoverPage = "https://picsum.photos/50/50/?image=847",
                            Description = "Assumenda blanditiis totam fugit nihil quos aut quod est recusandae dolores ex ipsum delectus soluta voluptatem maiores et hic praesentium.",
                            ISBN = 711944708,
                            PageCount = 604,
                            PublicationDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Reinger - Wolff",
                            Title = "portals bluetooth Nebraska"
                        },
                        new
                        {
                            ID = 73,
                            Author = "Alexandria Lockman",
                            Category = "sunt",
                            CoverPage = "https://picsum.photos/50/50/?image=214",
                            Description = "Omnis quia nemo aliquam quasi qui corporis animi ea dolore velit qui quia ut odit nisi amet a modi quisquam.",
                            ISBN = 606474207,
                            PageCount = 586,
                            PublicationDate = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Pfannerstill, Kozey and Rolfson",
                            Title = "Buckinghamshire web-enabled Buckinghamshire"
                        },
                        new
                        {
                            ID = 74,
                            Author = "Margaretta Flatley",
                            Category = "quaerat",
                            CoverPage = "https://picsum.photos/50/50/?image=313",
                            Description = "Voluptates enim neque atque libero fugit qui laudantium cupiditate rerum odit explicabo similique voluptatem neque doloribus cum occaecati aut tenetur.",
                            ISBN = 533030625,
                            PageCount = 261,
                            PublicationDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hessel, Crist and MacGyver",
                            Title = "withdrawal bandwidth Belarus"
                        },
                        new
                        {
                            ID = 75,
                            Author = "Nikolas Dibbert",
                            Category = "beatae",
                            CoverPage = "https://picsum.photos/50/50/?image=130",
                            Description = "Natus minus at cupiditate nihil sint omnis voluptatem repudiandae ut delectus architecto consequatur et ut tenetur quo et harum nisi.",
                            ISBN = 498414962,
                            PageCount = 234,
                            PublicationDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Aufderhar - Fay",
                            Title = "synergies SCSI e-tailers"
                        },
                        new
                        {
                            ID = 76,
                            Author = "Annamarie Abshire",
                            Category = "non",
                            CoverPage = "https://picsum.photos/50/50/?image=842",
                            Description = "Officiis sunt dolorum voluptatibus voluptatem repellat et explicabo possimus commodi eum aut ad excepturi sit sunt quia fugit voluptatem at.",
                            ISBN = 865961591,
                            PageCount = 493,
                            PublicationDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Greenfelder - Steuber",
                            Title = "multi-byte Developer Intelligent Metal Soap"
                        },
                        new
                        {
                            ID = 77,
                            Author = "Viviane Bruen",
                            Category = "nisi",
                            CoverPage = "https://picsum.photos/50/50/?image=887",
                            Description = "Rerum et possimus corporis cum voluptatem ratione ducimus est voluptatum fuga aut quisquam sit deserunt quia aut aut ullam quo.",
                            ISBN = 126119447,
                            PageCount = 456,
                            PublicationDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bergstrom Group",
                            Title = "Savings Account Wooden Generic"
                        },
                        new
                        {
                            ID = 78,
                            Author = "Jorge Fahey",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=298",
                            Description = "Maiores consequatur fugiat id sunt voluptatem quis veritatis natus dolor quia in aut hic ipsum rerum et non et ut.",
                            ISBN = 719499635,
                            PageCount = 950,
                            PublicationDate = new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Wolff - Osinski",
                            Title = "Liaison Unbranded Granite Tuna Unbranded"
                        },
                        new
                        {
                            ID = 79,
                            Author = "Kian Kozey",
                            Category = "nihil",
                            CoverPage = "https://picsum.photos/50/50/?image=58",
                            Description = "Sit est aliquid alias quae aut id ab dolor nesciunt velit sunt ipsa minima fugit error aut autem repellendus distinctio.",
                            ISBN = 947617071,
                            PageCount = 712,
                            PublicationDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Okuneva, Koepp and Schamberger",
                            Title = "New Mexico Markets backing up"
                        },
                        new
                        {
                            ID = 80,
                            Author = "Golda Wiza",
                            Category = "cumque",
                            CoverPage = "https://picsum.photos/50/50/?image=446",
                            Description = "A laborum harum consectetur alias beatae autem blanditiis accusamus voluptatem maxime saepe qui velit amet voluptates neque et minima dolorum.",
                            ISBN = 247573154,
                            PageCount = 296,
                            PublicationDate = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Walter and Sons",
                            Title = "Web Strategist neural-net"
                        },
                        new
                        {
                            ID = 81,
                            Author = "Jessie Hilll",
                            Category = "quia",
                            CoverPage = "https://picsum.photos/50/50/?image=60",
                            Description = "Corrupti dolorum harum atque aspernatur et cumque velit nulla deserunt aspernatur sed tempore maiores quas quas iusto sunt aliquid laudantium.",
                            ISBN = 892515306,
                            PageCount = 59,
                            PublicationDate = new DateTime(2023, 8, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rohan Group",
                            Title = "Hawaii International Steel"
                        },
                        new
                        {
                            ID = 82,
                            Author = "Stefan Dibbert",
                            Category = "quidem",
                            CoverPage = "https://picsum.photos/50/50/?image=922",
                            Description = "Qui inventore qui est optio aut voluptatibus molestias voluptatibus sint perferendis ipsum reiciendis consectetur impedit ratione qui voluptatem et praesentium.",
                            ISBN = 539583066,
                            PageCount = 728,
                            PublicationDate = new DateTime(2023, 10, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Zemlak, Konopelski and Waelchi",
                            Title = "CSS Multi-layered Argentine Peso"
                        },
                        new
                        {
                            ID = 83,
                            Author = "Cameron Feest",
                            Category = "quaerat",
                            CoverPage = "https://picsum.photos/50/50/?image=698",
                            Description = "Delectus exercitationem nisi amet eveniet ut eum ipsum reiciendis et voluptas quos magnam quia libero a cum rerum voluptatem debitis.",
                            ISBN = 772770043,
                            PageCount = 76,
                            PublicationDate = new DateTime(2023, 11, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Larson LLC",
                            Title = "Generic Steel Chair Self-enabling Handmade Plastic Towels"
                        },
                        new
                        {
                            ID = 84,
                            Author = "Derrick Conn",
                            Category = "harum",
                            CoverPage = "https://picsum.photos/50/50/?image=759",
                            Description = "Dicta quasi officia et voluptas amet similique dolorem rerum voluptatem ea quisquam ex voluptatibus dolorum natus et soluta delectus dolor.",
                            ISBN = 557029111,
                            PageCount = 980,
                            PublicationDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Jakubowski Group",
                            Title = "Massachusetts red Checking Account"
                        },
                        new
                        {
                            ID = 85,
                            Author = "Lelia Welch",
                            Category = "dolor",
                            CoverPage = "https://picsum.photos/50/50/?image=393",
                            Description = "Et voluptates corrupti libero ut eius voluptatem dolorem et natus sed soluta dolor enim non quo nostrum sit quia eaque.",
                            ISBN = 329114307,
                            PageCount = 493,
                            PublicationDate = new DateTime(2023, 8, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Predovic LLC",
                            Title = "Berkshire orchid monitor"
                        },
                        new
                        {
                            ID = 86,
                            Author = "Ethelyn McDermott",
                            Category = "ducimus",
                            CoverPage = "https://picsum.photos/50/50/?image=1010",
                            Description = "Ut fugiat optio esse velit natus quo nulla qui ea ut repellat error quia illo facilis assumenda quibusdam iste perferendis.",
                            ISBN = 888895289,
                            PageCount = 413,
                            PublicationDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gislason Group",
                            Title = "Money Market Account blockchains Digitized"
                        },
                        new
                        {
                            ID = 87,
                            Author = "Ashleigh Bailey",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=537",
                            Description = "Molestias laborum placeat earum enim vel blanditiis nihil fugit vel eos esse dolores ipsa quis pariatur laboriosam qui ea at.",
                            ISBN = 675077053,
                            PageCount = 180,
                            PublicationDate = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rosenbaum - Renner",
                            Title = "Eritrea open-source bandwidth"
                        },
                        new
                        {
                            ID = 88,
                            Author = "Mabel Adams",
                            Category = "voluptas",
                            CoverPage = "https://picsum.photos/50/50/?image=189",
                            Description = "Rerum provident incidunt officiis tempore sed aliquam debitis nulla id vel fugit inventore eveniet beatae ratione sed nemo adipisci expedita.",
                            ISBN = 734827750,
                            PageCount = 394,
                            PublicationDate = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ondricka, Mraz and Heidenreich",
                            Title = "applications 6th generation Configuration"
                        },
                        new
                        {
                            ID = 89,
                            Author = "Amalia Stamm",
                            Category = "sunt",
                            CoverPage = "https://picsum.photos/50/50/?image=356",
                            Description = "Et perferendis officia corrupti iste vel consequatur provident alias quo amet assumenda magni nihil molestias distinctio laborum consequatur perferendis quia.",
                            ISBN = 375730775,
                            PageCount = 486,
                            PublicationDate = new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Morissette, Koelpin and Carter",
                            Title = "TCP input Swaziland"
                        },
                        new
                        {
                            ID = 90,
                            Author = "Tito Moore",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=961",
                            Description = "Consectetur dignissimos at nobis iste ab commodi velit non tenetur perspiciatis tempore illo cum voluptatem autem deleniti ut labore quis.",
                            ISBN = 309037554,
                            PageCount = 343,
                            PublicationDate = new DateTime(2023, 11, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bernhard - Altenwerth",
                            Title = "Awesome 1080p pixel"
                        },
                        new
                        {
                            ID = 91,
                            Author = "Carmelo Schroeder",
                            Category = "dignissimos",
                            CoverPage = "https://picsum.photos/50/50/?image=1017",
                            Description = "Sapiente maxime deleniti consequatur recusandae laudantium necessitatibus maxime nam delectus aut explicabo quo quo vel explicabo ea consequatur et sequi.",
                            ISBN = 628770958,
                            PageCount = 83,
                            PublicationDate = new DateTime(2023, 9, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "White, Spinka and Hodkiewicz",
                            Title = "Ergonomic Principal Borders"
                        },
                        new
                        {
                            ID = 92,
                            Author = "Shannon Gislason",
                            Category = "quo",
                            CoverPage = "https://picsum.photos/50/50/?image=513",
                            Description = "Est omnis rem animi hic laboriosam optio repellendus vel quidem molestiae iusto nostrum quia animi quis accusamus autem aspernatur qui.",
                            ISBN = 508022041,
                            PageCount = 641,
                            PublicationDate = new DateTime(2023, 9, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Langosh, O'Kon and Streich",
                            Title = "sky blue hack Architect"
                        },
                        new
                        {
                            ID = 93,
                            Author = "Emelia Gleason",
                            Category = "quasi",
                            CoverPage = "https://picsum.photos/50/50/?image=220",
                            Description = "Corrupti et provident quidem consequatur sapiente dolorem earum non rerum repudiandae doloremque et ullam qui iusto et sed et quaerat.",
                            ISBN = 124461513,
                            PageCount = 285,
                            PublicationDate = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Runolfsdottir - Champlin",
                            Title = "mesh Unbranded Frozen Fish Berkshire"
                        },
                        new
                        {
                            ID = 94,
                            Author = "Ryann Considine",
                            Category = "voluptas",
                            CoverPage = "https://picsum.photos/50/50/?image=70",
                            Description = "Et et dolores et consequuntur voluptas at eveniet sint unde hic facilis numquam qui autem vel quae quis aut ex.",
                            ISBN = 445667150,
                            PageCount = 935,
                            PublicationDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Raynor - Hand",
                            Title = "Oklahoma Idaho green"
                        },
                        new
                        {
                            ID = 95,
                            Author = "Bailee Legros",
                            Category = "veritatis",
                            CoverPage = "https://picsum.photos/50/50/?image=524",
                            Description = "Laboriosam et non sunt et quis voluptas repudiandae et aut velit non et fuga aliquam eum quis harum totam at.",
                            ISBN = 208651134,
                            PageCount = 957,
                            PublicationDate = new DateTime(2023, 11, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rosenbaum, Dibbert and Towne",
                            Title = "withdrawal bandwidth-monitored Dong"
                        },
                        new
                        {
                            ID = 96,
                            Author = "Daniella Gutkowski",
                            Category = "sit",
                            CoverPage = "https://picsum.photos/50/50/?image=501",
                            Description = "Repellendus libero qui quia ut consectetur beatae ipsa magnam maiores ut praesentium quod qui veritatis officiis quia harum dolorem repudiandae.",
                            ISBN = 558059465,
                            PageCount = 91,
                            PublicationDate = new DateTime(2023, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gaylord - Moen",
                            Title = "productize pricing structure Island"
                        },
                        new
                        {
                            ID = 97,
                            Author = "Evangeline Lemke",
                            Category = "architecto",
                            CoverPage = "https://picsum.photos/50/50/?image=810",
                            Description = "Qui velit velit deleniti sequi nulla consequatur fugit nesciunt voluptates laborum autem placeat corporis quia dolorem libero debitis est quae.",
                            ISBN = 699140167,
                            PageCount = 193,
                            PublicationDate = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Halvorson LLC",
                            Title = "National Architect Ohio"
                        },
                        new
                        {
                            ID = 98,
                            Author = "Adriana Klein",
                            Category = "facilis",
                            CoverPage = "https://picsum.photos/50/50/?image=77",
                            Description = "Dolores voluptates blanditiis reiciendis vitae vero et animi harum deserunt eaque molestiae ipsam architecto et in voluptate eligendi cupiditate soluta.",
                            ISBN = 930105116,
                            PageCount = 659,
                            PublicationDate = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lemke Inc",
                            Title = "Auto Loan Account AGP responsive"
                        },
                        new
                        {
                            ID = 99,
                            Author = "Avis Swift",
                            Category = "quae",
                            CoverPage = "https://picsum.photos/50/50/?image=215",
                            Description = "Soluta quia impedit ut aut accusamus et occaecati facere quia alias nihil est perferendis voluptatum dolore maiores iste deleniti veritatis.",
                            ISBN = 916930372,
                            PageCount = 114,
                            PublicationDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lowe, Farrell and Sauer",
                            Title = "incubate invoice granular"
                        },
                        new
                        {
                            ID = 100,
                            Author = "Daisha Schowalter",
                            Category = "in",
                            CoverPage = "https://picsum.photos/50/50/?image=1071",
                            Description = "Qui repudiandae iusto fugit dolores non assumenda id iusto sit et neque voluptas et cupiditate consequatur a incidunt ipsam voluptate.",
                            ISBN = 413259557,
                            PageCount = 347,
                            PublicationDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "McDermott Group",
                            Title = "neural Checking Account Tasty"
                        });
                });

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.UserAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ROLE");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("ID");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.Book", b =>
                {
                    b.HasOne("TechnicalAssessmentRokov.Entities.UserAccount", "CheckedOutBy")
                        .WithMany()
                        .HasForeignKey("CheckedOutById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CheckedOutBy");
                });
#pragma warning restore 612, 618
        }
    }
}
