// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalAssessmentRokov.Data;

#nullable disable

namespace TechnicalAssessmentRokov.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240617222022_ResetStructure")]
    partial class ResetStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUTHOR");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("CoverPage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COVER_PAGE");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("ISBN")
                        .HasColumnType("int")
                        .HasColumnName("ISBN");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("PAGE_COUNT");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PUBLICATION_DATE");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PUBLISHER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Madge Lang",
                            Category = "totam",
                            CoverPage = "https://picsum.photos/50/50/?image=516",
                            Description = "Aliquid eum laborum quis sunt non eligendi ullam deleniti debitis doloremque unde perspiciatis laudantium voluptas molestiae ad odio quasi voluptatem.",
                            ISBN = 371573908,
                            PageCount = 521,
                            PublicationDate = new DateTime(2023, 11, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Leuschke - Cormier",
                            Title = "Electronics & Tools bypassing California"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Mireya McCullough",
                            Category = "laudantium",
                            CoverPage = "https://picsum.photos/50/50/?image=438",
                            Description = "Enim distinctio quia commodi dolores consequuntur nisi consequuntur doloribus deleniti quidem qui qui saepe iusto eum est sequi molestias reiciendis.",
                            ISBN = 743899247,
                            PageCount = 403,
                            PublicationDate = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Berge - Terry",
                            Title = "communities withdrawal Frozen"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Kayla Halvorson",
                            Category = "nulla",
                            CoverPage = "https://picsum.photos/50/50/?image=365",
                            Description = "Doloremque possimus atque quam sunt inventore vel quibusdam nemo iure culpa quo eligendi sed rerum saepe sit quaerat sint vel.",
                            ISBN = 204433492,
                            PageCount = 62,
                            PublicationDate = new DateTime(2023, 10, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Morar, Willms and Schowalter",
                            Title = "infrastructures web-readiness protocol"
                        },
                        new
                        {
                            ID = 4,
                            Author = "Edward Kiehn",
                            Category = "dolor",
                            CoverPage = "https://picsum.photos/50/50/?image=553",
                            Description = "Dolorem praesentium occaecati necessitatibus voluptas repellendus dolore sed temporibus quod ut qui repellat voluptatem labore et molestiae accusantium maxime alias.",
                            ISBN = 146470699,
                            PageCount = 664,
                            PublicationDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Glover - Hermann",
                            Title = "payment integrated Home Loan Account"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Bettye Wisozk",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=795",
                            Description = "Est quos voluptatem dolores adipisci sapiente dolorum corporis recusandae laudantium et possimus nisi autem et amet beatae unde in tempora.",
                            ISBN = 702131600,
                            PageCount = 176,
                            PublicationDate = new DateTime(2023, 8, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Daugherty, Shanahan and Lebsack",
                            Title = "pixel Avon holistic"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Malcolm Shields",
                            Category = "hic",
                            CoverPage = "https://picsum.photos/50/50/?image=223",
                            Description = "Molestias ut alias et qui reprehenderit ducimus qui odio non illo quas dolores neque consequatur quam quia quis delectus non.",
                            ISBN = 707457854,
                            PageCount = 321,
                            PublicationDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Connelly, Kerluke and Nikolaus",
                            Title = "Personal Loan Account Pitcairn Islands Forge"
                        },
                        new
                        {
                            ID = 7,
                            Author = "Emilie Swaniawski",
                            Category = "accusamus",
                            CoverPage = "https://picsum.photos/50/50/?image=783",
                            Description = "Illo in sit in pariatur voluptatem enim tempora rerum pariatur voluptatum quia in asperiores deleniti possimus maxime iste repellendus officiis.",
                            ISBN = 790781708,
                            PageCount = 467,
                            PublicationDate = new DateTime(2023, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mayer, Quigley and Rippin",
                            Title = "Plastic Pike ubiquitous"
                        },
                        new
                        {
                            ID = 8,
                            Author = "Luis Krajcik",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=699",
                            Description = "Repellat rerum molestiae est qui sint et et assumenda aut corrupti minima veniam fuga est fuga vero cupiditate eaque voluptatem.",
                            ISBN = 902883336,
                            PageCount = 356,
                            PublicationDate = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Wiza, Cummerata and Weber",
                            Title = "overriding deliver Chief"
                        },
                        new
                        {
                            ID = 9,
                            Author = "Odell Schimmel",
                            Category = "corporis",
                            CoverPage = "https://picsum.photos/50/50/?image=747",
                            Description = "Adipisci libero est distinctio maiores nesciunt sint facilis beatae facilis rem voluptatum aperiam reprehenderit voluptatem unde ut quaerat molestiae magnam.",
                            ISBN = 979979712,
                            PageCount = 565,
                            PublicationDate = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Keeling, McKenzie and Gorczany",
                            Title = "National white quantify"
                        },
                        new
                        {
                            ID = 10,
                            Author = "Paige Feeney",
                            Category = "est",
                            CoverPage = "https://picsum.photos/50/50/?image=842",
                            Description = "Non quas omnis ducimus consequatur deleniti quod labore asperiores quia magni atque voluptatem rerum neque odio sed esse ea aut.",
                            ISBN = 735164012,
                            PageCount = 340,
                            PublicationDate = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bailey and Sons",
                            Title = "Liechtenstein withdrawal software"
                        },
                        new
                        {
                            ID = 11,
                            Author = "Cleta Price",
                            Category = "commodi",
                            CoverPage = "https://picsum.photos/50/50/?image=386",
                            Description = "Incidunt adipisci inventore voluptatem amet non sit aliquid facere maiores voluptatem et facilis eius culpa iusto sit odio libero iure.",
                            ISBN = 494481323,
                            PageCount = 994,
                            PublicationDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Boehm - Glover",
                            Title = "Handcrafted Rubber Mouse Cotton matrix"
                        },
                        new
                        {
                            ID = 12,
                            Author = "Alyson Walter",
                            Category = "fugiat",
                            CoverPage = "https://picsum.photos/50/50/?image=403",
                            Description = "Ut officiis a perferendis qui veniam molestias harum qui dolorum temporibus quis asperiores culpa id ducimus recusandae nulla veniam fuga.",
                            ISBN = 129015943,
                            PageCount = 484,
                            PublicationDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Langworth and Sons",
                            Title = "SSL Liaison Gorgeous"
                        },
                        new
                        {
                            ID = 13,
                            Author = "Catalina Emard",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=379",
                            Description = "Aperiam a ut similique placeat voluptates sequi deleniti quisquam ratione est velit impedit consequuntur et quia cupiditate qui quod voluptatum.",
                            ISBN = 418736660,
                            PageCount = 501,
                            PublicationDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Little, O'Kon and Willms",
                            Title = "Rustic Metal Gloves Cotton Metrics"
                        },
                        new
                        {
                            ID = 14,
                            Author = "Shania Pacocha",
                            Category = "voluptate",
                            CoverPage = "https://picsum.photos/50/50/?image=137",
                            Description = "Facilis quia possimus modi animi et voluptas harum natus quidem doloremque sint temporibus corrupti non autem facilis autem iste quia.",
                            ISBN = 770407573,
                            PageCount = 292,
                            PublicationDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kshlerin and Sons",
                            Title = "alarm Buckinghamshire backing up"
                        },
                        new
                        {
                            ID = 15,
                            Author = "Marie Feeney",
                            Category = "ut",
                            CoverPage = "https://picsum.photos/50/50/?image=1049",
                            Description = "Consequatur sunt quos sit sapiente soluta deleniti blanditiis et quidem architecto consectetur ut vitae omnis in sit ad voluptate molestiae.",
                            ISBN = 411179307,
                            PageCount = 601,
                            PublicationDate = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Jaskolski, Hirthe and Keeling",
                            Title = "optical bluetooth cyan"
                        },
                        new
                        {
                            ID = 16,
                            Author = "Lane Bartoletti",
                            Category = "quam",
                            CoverPage = "https://picsum.photos/50/50/?image=841",
                            Description = "Asperiores corporis aut ut et perspiciatis odio deserunt eveniet quod impedit numquam ut voluptatem fugiat excepturi et autem laborum asperiores.",
                            ISBN = 715948820,
                            PageCount = 225,
                            PublicationDate = new DateTime(2023, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Abbott, Jones and Schaefer",
                            Title = "Credit Card Account Movies Virginia"
                        },
                        new
                        {
                            ID = 17,
                            Author = "Tressa Streich",
                            Category = "voluptas",
                            CoverPage = "https://picsum.photos/50/50/?image=471",
                            Description = "Deleniti qui ut accusamus quasi non dolores possimus et eos doloribus odit omnis nihil nam repellendus ullam aliquid praesentium aperiam.",
                            ISBN = 297886920,
                            PageCount = 588,
                            PublicationDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gorczany Group",
                            Title = "Chief Personal Loan Account Mississippi"
                        },
                        new
                        {
                            ID = 18,
                            Author = "Ebony Dicki",
                            Category = "repudiandae",
                            CoverPage = "https://picsum.photos/50/50/?image=95",
                            Description = "Earum quam eum consequatur unde blanditiis temporibus magni et fugit adipisci rerum quibusdam aperiam sed iusto animi quidem voluptatibus eos.",
                            ISBN = 890654102,
                            PageCount = 912,
                            PublicationDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Cummerata - Franecki",
                            Title = "Ports Station synergies"
                        },
                        new
                        {
                            ID = 19,
                            Author = "Elmore Nicolas",
                            Category = "adipisci",
                            CoverPage = "https://picsum.photos/50/50/?image=155",
                            Description = "Aperiam cupiditate est veniam inventore tempora ipsa et qui consequatur qui quis similique explicabo odit ea rerum consequatur eos similique.",
                            ISBN = 539165734,
                            PageCount = 830,
                            PublicationDate = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Goodwin, McClure and Langosh",
                            Title = "Street pixel Fantastic Concrete Fish"
                        },
                        new
                        {
                            ID = 20,
                            Author = "Vivien Leffler",
                            Category = "aspernatur",
                            CoverPage = "https://picsum.photos/50/50/?image=1011",
                            Description = "Est eum dolorem voluptatem excepturi eum molestiae laborum doloremque inventore fuga in qui eum illum unde praesentium officia ad aut.",
                            ISBN = 333451232,
                            PageCount = 634,
                            PublicationDate = new DateTime(2023, 9, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bergnaum and Sons",
                            Title = "Court strategic Garden & Garden"
                        },
                        new
                        {
                            ID = 21,
                            Author = "Cindy Adams",
                            Category = "ipsum",
                            CoverPage = "https://picsum.photos/50/50/?image=438",
                            Description = "Consequatur quam corrupti voluptates debitis cupiditate dolorum quia neque et ut ea in velit porro qui asperiores omnis et qui.",
                            ISBN = 473914166,
                            PageCount = 560,
                            PublicationDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Romaguera, Bruen and McCullough",
                            Title = "Lebanese Pound Sports & Health Berkshire"
                        },
                        new
                        {
                            ID = 22,
                            Author = "Geoffrey Huels",
                            Category = "vero",
                            CoverPage = "https://picsum.photos/50/50/?image=711",
                            Description = "In consequatur perspiciatis qui fuga et quo molestiae et consequatur esse iste sed atque magnam nihil asperiores voluptatem voluptas sed.",
                            ISBN = 479846557,
                            PageCount = 376,
                            PublicationDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kuvalis, Herman and Lynch",
                            Title = "Rustic Fresh Shirt Haiti XSS"
                        },
                        new
                        {
                            ID = 23,
                            Author = "Barney Windler",
                            Category = "vel",
                            CoverPage = "https://picsum.photos/50/50/?image=226",
                            Description = "Enim fugiat eveniet in sapiente rerum qui id id expedita libero voluptate et molestias quis deleniti fugiat nisi minus autem.",
                            ISBN = 149570147,
                            PageCount = 875,
                            PublicationDate = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Pfeffer - Nolan",
                            Title = "Serbia parse Directives"
                        },
                        new
                        {
                            ID = 24,
                            Author = "Chauncey Jones",
                            Category = "eveniet",
                            CoverPage = "https://picsum.photos/50/50/?image=777",
                            Description = "Qui est quae beatae quia unde sit voluptas rem voluptatem voluptatum voluptas ut et voluptatum occaecati dicta et qui aut.",
                            ISBN = 760666234,
                            PageCount = 461,
                            PublicationDate = new DateTime(2024, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Steuber, Murazik and Kshlerin",
                            Title = "River Papua New Guinea Circle"
                        },
                        new
                        {
                            ID = 25,
                            Author = "Cayla Witting",
                            Category = "assumenda",
                            CoverPage = "https://picsum.photos/50/50/?image=560",
                            Description = "Est sed repellendus sint et et corporis possimus illo dolores saepe sequi eum quas repellendus cumque velit error quos earum.",
                            ISBN = 857676432,
                            PageCount = 392,
                            PublicationDate = new DateTime(2023, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Stark - Hermiston",
                            Title = "silver interactive architecture"
                        },
                        new
                        {
                            ID = 26,
                            Author = "Everardo Ullrich",
                            Category = "dolorem",
                            CoverPage = "https://picsum.photos/50/50/?image=437",
                            Description = "Corporis ut enim veniam et dolore et velit ad distinctio quidem qui vel ab error similique dolorum aperiam voluptatem neque.",
                            ISBN = 428495078,
                            PageCount = 238,
                            PublicationDate = new DateTime(2023, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schinner - Batz",
                            Title = "visualize intuitive program"
                        },
                        new
                        {
                            ID = 27,
                            Author = "Juliana Haag",
                            Category = "eaque",
                            CoverPage = "https://picsum.photos/50/50/?image=72",
                            Description = "Culpa exercitationem vel dolores assumenda et inventore quam delectus minus dicta aliquid ut dolores repudiandae eveniet sit in ab accusamus.",
                            ISBN = 561983063,
                            PageCount = 421,
                            PublicationDate = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Walsh LLC",
                            Title = "Dong SSL Ukraine"
                        },
                        new
                        {
                            ID = 28,
                            Author = "Milford Schroeder",
                            Category = "reiciendis",
                            CoverPage = "https://picsum.photos/50/50/?image=710",
                            Description = "Quia sint iste voluptatem minus qui odit qui iusto sunt exercitationem odio et dignissimos consectetur ullam placeat aperiam doloremque qui.",
                            ISBN = 216229626,
                            PageCount = 806,
                            PublicationDate = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Berge, Jacobs and Botsford",
                            Title = "Texas magenta Awesome Soft Pizza"
                        },
                        new
                        {
                            ID = 29,
                            Author = "Kathryn Bode",
                            Category = "explicabo",
                            CoverPage = "https://picsum.photos/50/50/?image=851",
                            Description = "Alias corrupti ea unde modi aut voluptas quia est nulla et nulla qui nihil ullam qui harum voluptatem dolorem et.",
                            ISBN = 112829357,
                            PageCount = 338,
                            PublicationDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schroeder, Schuster and Mills",
                            Title = "parsing e-markets Human"
                        },
                        new
                        {
                            ID = 30,
                            Author = "Rusty Yost",
                            Category = "sint",
                            CoverPage = "https://picsum.photos/50/50/?image=5",
                            Description = "Rerum laudantium sit rem velit vel ex et autem sed fuga doloribus laborum animi omnis et fuga ex eligendi ex.",
                            ISBN = 784882285,
                            PageCount = 290,
                            PublicationDate = new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Reichert Inc",
                            Title = "Plastic Paradigm Horizontal"
                        },
                        new
                        {
                            ID = 31,
                            Author = "Karen Feest",
                            Category = "quibusdam",
                            CoverPage = "https://picsum.photos/50/50/?image=914",
                            Description = "Accusantium fugiat amet libero molestiae quos accusamus quos fuga iste ducimus enim sint veniam nam et magnam odio recusandae et.",
                            ISBN = 509052475,
                            PageCount = 858,
                            PublicationDate = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Satterfield, Labadie and Hamill",
                            Title = "Fantastic Rubber Pants Beauty process improvement"
                        },
                        new
                        {
                            ID = 32,
                            Author = "Alejandrin Lubowitz",
                            Category = "quaerat",
                            CoverPage = "https://picsum.photos/50/50/?image=170",
                            Description = "Dolores veniam est rerum atque temporibus aliquam aliquam illo quasi debitis non nihil et facilis et quis id laborum voluptatem.",
                            ISBN = 167597620,
                            PageCount = 930,
                            PublicationDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Block, Kulas and Bosco",
                            Title = "Sleek Credit Card Account compressing"
                        },
                        new
                        {
                            ID = 33,
                            Author = "Marley McCullough",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=940",
                            Description = "Non et repellendus temporibus et minima consequatur soluta consequuntur culpa cum facilis quae ipsum rem ut nobis non deserunt ut.",
                            ISBN = 903590152,
                            PageCount = 441,
                            PublicationDate = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rice - Nikolaus",
                            Title = "Ergonomic Cameroon Developer"
                        },
                        new
                        {
                            ID = 34,
                            Author = "Danielle Cole",
                            Category = "officiis",
                            CoverPage = "https://picsum.photos/50/50/?image=794",
                            Description = "Occaecati itaque nulla repellat ut non incidunt vero sint repellat consequatur eum similique explicabo eaque temporibus et et autem voluptatem.",
                            ISBN = 542005903,
                            PageCount = 558,
                            PublicationDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Pagac, Blanda and Walker",
                            Title = "Checking Account Granite Unbranded"
                        },
                        new
                        {
                            ID = 35,
                            Author = "Eula Conn",
                            Category = "nihil",
                            CoverPage = "https://picsum.photos/50/50/?image=901",
                            Description = "Qui vel occaecati voluptatem occaecati sint architecto qui dolorem quae optio cum autem nulla sed non nesciunt nisi quae eos.",
                            ISBN = 624722456,
                            PageCount = 339,
                            PublicationDate = new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Dooley, Ward and Schinner",
                            Title = "bluetooth Ergonomic Regional"
                        },
                        new
                        {
                            ID = 36,
                            Author = "Nyah Homenick",
                            Category = "exercitationem",
                            CoverPage = "https://picsum.photos/50/50/?image=193",
                            Description = "Totam quas debitis voluptas adipisci atque commodi molestiae nisi quam qui natus dolore pariatur aperiam et aut deleniti aut dolorem.",
                            ISBN = 847386727,
                            PageCount = 884,
                            PublicationDate = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gulgowski - Hilpert",
                            Title = "SDD synthesizing success"
                        },
                        new
                        {
                            ID = 37,
                            Author = "Shaylee Hane",
                            Category = "tempora",
                            CoverPage = "https://picsum.photos/50/50/?image=7",
                            Description = "Excepturi eveniet quibusdam optio amet enim repudiandae non officia id aspernatur maxime sed repudiandae officiis delectus accusamus dolor vel ut.",
                            ISBN = 155619421,
                            PageCount = 731,
                            PublicationDate = new DateTime(2023, 10, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Beatty LLC",
                            Title = "brand end-to-end Analyst"
                        },
                        new
                        {
                            ID = 38,
                            Author = "Rylee Stroman",
                            Category = "nemo",
                            CoverPage = "https://picsum.photos/50/50/?image=139",
                            Description = "Enim aut repudiandae exercitationem a maiores voluptas consequatur minus consequatur amet quia mollitia dolor laborum reiciendis amet voluptas nihil excepturi.",
                            ISBN = 924892285,
                            PageCount = 929,
                            PublicationDate = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bashirian and Sons",
                            Title = "back up Accountability payment"
                        },
                        new
                        {
                            ID = 39,
                            Author = "Bradford Berge",
                            Category = "molestiae",
                            CoverPage = "https://picsum.photos/50/50/?image=377",
                            Description = "Corrupti omnis tempora totam consequatur impedit praesentium nesciunt eaque consequatur rerum reprehenderit odio error eaque est voluptatem distinctio in et.",
                            ISBN = 967572328,
                            PageCount = 283,
                            PublicationDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hane, Weissnat and Ullrich",
                            Title = "Berkshire optical haptic"
                        },
                        new
                        {
                            ID = 40,
                            Author = "Easton Witting",
                            Category = "tenetur",
                            CoverPage = "https://picsum.photos/50/50/?image=305",
                            Description = "Vel quaerat ea reiciendis nulla enim quia quae a sed eum dignissimos omnis vel aspernatur doloremque earum minima molestiae nam.",
                            ISBN = 689345858,
                            PageCount = 954,
                            PublicationDate = new DateTime(2023, 9, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Daugherty and Sons",
                            Title = "Points Executive frictionless"
                        },
                        new
                        {
                            ID = 41,
                            Author = "Dashawn Windler",
                            Category = "architecto",
                            CoverPage = "https://picsum.photos/50/50/?image=920",
                            Description = "Voluptate ab ad incidunt tempore illo consequatur temporibus sapiente quia mollitia veritatis ut et omnis est dolor ea fugiat sunt.",
                            ISBN = 652908508,
                            PageCount = 661,
                            PublicationDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ruecker, Schamberger and Kerluke",
                            Title = "Steel Court back-end"
                        },
                        new
                        {
                            ID = 42,
                            Author = "Lauryn Bode",
                            Category = "doloremque",
                            CoverPage = "https://picsum.photos/50/50/?image=472",
                            Description = "Est blanditiis distinctio dolores deleniti perferendis asperiores vero cupiditate quidem aut qui voluptatem et aut et est nam velit quibusdam.",
                            ISBN = 456006965,
                            PageCount = 239,
                            PublicationDate = new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schumm Inc",
                            Title = "value-added Mississippi Networked"
                        },
                        new
                        {
                            ID = 43,
                            Author = "Rozella Volkman",
                            Category = "adipisci",
                            CoverPage = "https://picsum.photos/50/50/?image=126",
                            Description = "Rerum rerum laboriosam quia mollitia ipsum et et et nisi occaecati quibusdam sed est eveniet incidunt doloremque ratione veritatis ea.",
                            ISBN = 385814869,
                            PageCount = 114,
                            PublicationDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hilpert - Emmerich",
                            Title = "driver mobile Russian Ruble"
                        },
                        new
                        {
                            ID = 44,
                            Author = "Timothy Lakin",
                            Category = "non",
                            CoverPage = "https://picsum.photos/50/50/?image=251",
                            Description = "Deserunt voluptatem voluptatum aperiam quod sit beatae consequuntur sunt magni dicta repudiandae omnis voluptatum perspiciatis consequatur laudantium ut officiis ad.",
                            ISBN = 278229548,
                            PageCount = 775,
                            PublicationDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Koss, Williamson and Marks",
                            Title = "Enhanced Loaf deposit"
                        },
                        new
                        {
                            ID = 45,
                            Author = "Jayne Boehm",
                            Category = "reiciendis",
                            CoverPage = "https://picsum.photos/50/50/?image=1083",
                            Description = "Doloremque quia ad fugiat in quod tenetur aut est voluptates cumque et quidem repellat aspernatur similique eligendi ex consequuntur aliquam.",
                            ISBN = 966961663,
                            PageCount = 118,
                            PublicationDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kassulke, Murphy and Swaniawski",
                            Title = "SQL core withdrawal"
                        },
                        new
                        {
                            ID = 46,
                            Author = "Jaycee Walker",
                            Category = "harum",
                            CoverPage = "https://picsum.photos/50/50/?image=425",
                            Description = "Animi rerum doloremque non nobis et qui ea aut omnis et quidem sit et aut minima quia debitis beatae omnis.",
                            ISBN = 326673108,
                            PageCount = 128,
                            PublicationDate = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Adams - Dach",
                            Title = "El Salvador haptic Garden"
                        },
                        new
                        {
                            ID = 47,
                            Author = "Marjory Morissette",
                            Category = "atque",
                            CoverPage = "https://picsum.photos/50/50/?image=1054",
                            Description = "Sint dolores numquam enim repudiandae quia optio minima magnam numquam ut tempora explicabo id eum mollitia officia voluptas minima rerum.",
                            ISBN = 942689508,
                            PageCount = 632,
                            PublicationDate = new DateTime(2023, 7, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Thompson Group",
                            Title = "Island Small Rubber Pants Plains"
                        },
                        new
                        {
                            ID = 48,
                            Author = "Ed Nolan",
                            Category = "dicta",
                            CoverPage = "https://picsum.photos/50/50/?image=657",
                            Description = "Reprehenderit commodi aut repellat iure velit esse sunt impedit rem neque et alias harum ipsam rem repellat omnis quidem quod.",
                            ISBN = 528054998,
                            PageCount = 286,
                            PublicationDate = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Corkery, Batz and Blick",
                            Title = "Licensed Plastic Tuna sexy Communications"
                        },
                        new
                        {
                            ID = 49,
                            Author = "Constance Harris",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=733",
                            Description = "Consequatur voluptatum praesentium perferendis dolorem laboriosam velit sed veritatis minima commodi placeat nostrum aspernatur quia qui voluptas corporis sed est.",
                            ISBN = 295601123,
                            PageCount = 51,
                            PublicationDate = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Legros, Gerlach and Blick",
                            Title = "Agent matrix deploy"
                        },
                        new
                        {
                            ID = 50,
                            Author = "Brice Ebert",
                            Category = "qui",
                            CoverPage = "https://picsum.photos/50/50/?image=441",
                            Description = "Debitis voluptatem eos minima voluptas quos aut sed maxime hic hic magni atque in labore veritatis sed omnis in eum.",
                            ISBN = 315042982,
                            PageCount = 129,
                            PublicationDate = new DateTime(2023, 11, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ward, Terry and Moen",
                            Title = "parsing Guinea Fundamental"
                        },
                        new
                        {
                            ID = 51,
                            Author = "April Thompson",
                            Category = "odit",
                            CoverPage = "https://picsum.photos/50/50/?image=1073",
                            Description = "Voluptatem quam ullam ipsa itaque velit sunt deleniti repellendus ullam sit vitae quos dolor repellendus numquam molestiae qui eligendi maiores.",
                            ISBN = 750123590,
                            PageCount = 513,
                            PublicationDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kulas - McCullough",
                            Title = "Practical Fresh Gloves Berkshire black"
                        },
                        new
                        {
                            ID = 52,
                            Author = "Baron Cole",
                            Category = "voluptatem",
                            CoverPage = "https://picsum.photos/50/50/?image=757",
                            Description = "Nemo quia sit cupiditate et debitis explicabo non saepe expedita perferendis consequatur dolores qui autem cum ea nam voluptas ad.",
                            ISBN = 603272044,
                            PageCount = 187,
                            PublicationDate = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Medhurst LLC",
                            Title = "Investment Account auxiliary Money Market Account"
                        },
                        new
                        {
                            ID = 53,
                            Author = "Amy Cronin",
                            Category = "ea",
                            CoverPage = "https://picsum.photos/50/50/?image=213",
                            Description = "Est accusantium maiores nihil consectetur illum nam fuga aut vero non tempora nesciunt nesciunt dolores quam doloremque temporibus voluptas soluta.",
                            ISBN = 623227603,
                            PageCount = 61,
                            PublicationDate = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bahringer - Turner",
                            Title = "channels card Optimization"
                        },
                        new
                        {
                            ID = 54,
                            Author = "Cordell Crona",
                            Category = "laboriosam",
                            CoverPage = "https://picsum.photos/50/50/?image=844",
                            Description = "Accusamus ad sit vel est eum cum recusandae numquam aut culpa tempore quisquam amet harum quaerat dolores delectus accusantium sint.",
                            ISBN = 822988323,
                            PageCount = 196,
                            PublicationDate = new DateTime(2023, 10, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Vandervort Group",
                            Title = "Auto Loan Account mobile bandwidth-monitored"
                        },
                        new
                        {
                            ID = 55,
                            Author = "Afton Armstrong",
                            Category = "dignissimos",
                            CoverPage = "https://picsum.photos/50/50/?image=311",
                            Description = "Ut dolor quo accusamus quidem accusantium modi ea alias quia exercitationem eligendi dolorem cum assumenda vitae aut beatae quo libero.",
                            ISBN = 617796888,
                            PageCount = 476,
                            PublicationDate = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Balistreri LLC",
                            Title = "dynamic Unbranded Rubber Salad Bahamian Dollar"
                        },
                        new
                        {
                            ID = 56,
                            Author = "Vincent Hyatt",
                            Category = "voluptas",
                            CoverPage = "https://picsum.photos/50/50/?image=505",
                            Description = "Asperiores voluptatem aut sapiente rem omnis corrupti facere veritatis veniam sint fuga placeat officiis in necessitatibus rerum sint odio rerum.",
                            ISBN = 308002227,
                            PageCount = 801,
                            PublicationDate = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bogan - Moore",
                            Title = "challenge Parkway Berkshire"
                        },
                        new
                        {
                            ID = 57,
                            Author = "Maurine Krajcik",
                            Category = "ea",
                            CoverPage = "https://picsum.photos/50/50/?image=148",
                            Description = "Nam non qui enim veniam quibusdam modi facilis reprehenderit et recusandae nam et molestias ipsa et cum neque aut magni.",
                            ISBN = 451720544,
                            PageCount = 805,
                            PublicationDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bradtke, Turcotte and Carroll",
                            Title = "fuchsia Face to face Savings Account"
                        },
                        new
                        {
                            ID = 58,
                            Author = "Merritt Skiles",
                            Category = "in",
                            CoverPage = "https://picsum.photos/50/50/?image=89",
                            Description = "Quaerat possimus tenetur blanditiis eveniet eius inventore totam officia nemo aut atque vel at quia aut laboriosam sit temporibus quis.",
                            ISBN = 205008178,
                            PageCount = 577,
                            PublicationDate = new DateTime(2023, 8, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Howell and Sons",
                            Title = "Cambridgeshire Organic International"
                        },
                        new
                        {
                            ID = 59,
                            Author = "Myrl Wuckert",
                            Category = "voluptas",
                            CoverPage = "https://picsum.photos/50/50/?image=242",
                            Description = "Perspiciatis molestias omnis sapiente perferendis vitae placeat qui sit porro atque blanditiis ab doloribus ut perspiciatis maxime repellat mollitia dolorem.",
                            ISBN = 251374798,
                            PageCount = 531,
                            PublicationDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Stokes - Koss",
                            Title = "leverage National conglomeration"
                        },
                        new
                        {
                            ID = 60,
                            Author = "Oswald Streich",
                            Category = "nobis",
                            CoverPage = "https://picsum.photos/50/50/?image=706",
                            Description = "Qui molestias eveniet ut voluptatem occaecati eum distinctio sit at cupiditate labore quod totam velit rerum sint deserunt quaerat dicta.",
                            ISBN = 999142781,
                            PageCount = 288,
                            PublicationDate = new DateTime(2023, 8, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Murray - Terry",
                            Title = "deposit Refined Principal"
                        },
                        new
                        {
                            ID = 61,
                            Author = "Alec Bailey",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=423",
                            Description = "Provident et aut porro molestias sed ea officiis excepturi quasi cupiditate vitae at rerum suscipit dolores similique sint minus aut.",
                            ISBN = 884050470,
                            PageCount = 746,
                            PublicationDate = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Klein - Botsford",
                            Title = "backing up Australia Legacy"
                        },
                        new
                        {
                            ID = 62,
                            Author = "Justus Cronin",
                            Category = "sequi",
                            CoverPage = "https://picsum.photos/50/50/?image=658",
                            Description = "Porro laboriosam placeat est modi quia aperiam totam omnis eveniet voluptas qui asperiores culpa ex ut nisi quibusdam fugit nobis.",
                            ISBN = 385354171,
                            PageCount = 352,
                            PublicationDate = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kozey, Vandervort and Yost",
                            Title = "Director hack National"
                        },
                        new
                        {
                            ID = 63,
                            Author = "Arely Heaney",
                            Category = "accusantium",
                            CoverPage = "https://picsum.photos/50/50/?image=473",
                            Description = "Reiciendis porro quas quia dicta voluptatibus ducimus impedit maxime corporis dolores voluptate illum aut ut perspiciatis ipsum quae rerum cum.",
                            ISBN = 101846816,
                            PageCount = 320,
                            PublicationDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Crooks, Kshlerin and Bernier",
                            Title = "Tasty Frozen Fish leverage deliverables"
                        },
                        new
                        {
                            ID = 64,
                            Author = "Kelton Collins",
                            Category = "molestiae",
                            CoverPage = "https://picsum.photos/50/50/?image=406",
                            Description = "Et voluptate vero consequatur et maxime itaque qui nulla quam voluptatem qui veritatis nihil similique autem qui a sit nostrum.",
                            ISBN = 923539324,
                            PageCount = 771,
                            PublicationDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hills Inc",
                            Title = "Rubber Checking Account District"
                        },
                        new
                        {
                            ID = 65,
                            Author = "Curtis Rath",
                            Category = "enim",
                            CoverPage = "https://picsum.photos/50/50/?image=841",
                            Description = "Aut numquam mollitia omnis ex sint provident ut est consequatur itaque quasi hic quae ipsam fugiat ea numquam nobis nihil.",
                            ISBN = 387070785,
                            PageCount = 994,
                            PublicationDate = new DateTime(2023, 7, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rodriguez - Larkin",
                            Title = "Borders Svalbard & Jan Mayen Islands Robust"
                        },
                        new
                        {
                            ID = 66,
                            Author = "Emanuel Collier",
                            Category = "incidunt",
                            CoverPage = "https://picsum.photos/50/50/?image=3",
                            Description = "Sit numquam sequi placeat quas sit officiis vel ea ducimus molestiae qui est ut qui cupiditate dignissimos tempore sunt est.",
                            ISBN = 458188196,
                            PageCount = 602,
                            PublicationDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Armstrong, Feil and Gutkowski",
                            Title = "Awesome Metal Sleek Steel Ball"
                        },
                        new
                        {
                            ID = 67,
                            Author = "Charley Balistreri",
                            Category = "ullam",
                            CoverPage = "https://picsum.photos/50/50/?image=136",
                            Description = "Eum libero quam dolorem repellendus quibusdam numquam nostrum ratione qui corrupti et voluptatem qui recusandae quo ipsam eum voluptatibus aspernatur.",
                            ISBN = 218111320,
                            PageCount = 298,
                            PublicationDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "McKenzie, Barrows and Smith",
                            Title = "dot-com connecting program"
                        },
                        new
                        {
                            ID = 68,
                            Author = "Oliver Sporer",
                            Category = "odit",
                            CoverPage = "https://picsum.photos/50/50/?image=106",
                            Description = "Debitis ut iste neque cupiditate quam consequatur tempora facere perferendis odit qui cum perferendis qui et molestiae a autem voluptatem.",
                            ISBN = 906122695,
                            PageCount = 781,
                            PublicationDate = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mitchell Inc",
                            Title = "Auto Loan Account Auto Loan Account local"
                        },
                        new
                        {
                            ID = 69,
                            Author = "Ova Wiegand",
                            Category = "qui",
                            CoverPage = "https://picsum.photos/50/50/?image=545",
                            Description = "Rerum culpa dolor repudiandae quia necessitatibus et error illo blanditiis minima quis sint voluptates rerum natus et fugiat ut ut.",
                            ISBN = 731376239,
                            PageCount = 448,
                            PublicationDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Cassin LLC",
                            Title = "hack efficient end-to-end"
                        },
                        new
                        {
                            ID = 70,
                            Author = "Hal Blick",
                            Category = "provident",
                            CoverPage = "https://picsum.photos/50/50/?image=546",
                            Description = "Quibusdam non consectetur itaque error quis porro voluptatem ipsam aut consequatur rerum voluptas non ut iure sequi reprehenderit tempora sit.",
                            ISBN = 239911048,
                            PageCount = 797,
                            PublicationDate = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rowe, Yundt and Vandervort",
                            Title = "Specialist Investment Account Alley"
                        },
                        new
                        {
                            ID = 71,
                            Author = "Jeanette Schneider",
                            Category = "assumenda",
                            CoverPage = "https://picsum.photos/50/50/?image=416",
                            Description = "Aut expedita omnis aut molestias sequi aut est tempore enim sit debitis et libero quis maxime iure eius veniam velit.",
                            ISBN = 439987411,
                            PageCount = 824,
                            PublicationDate = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Harvey - Muller",
                            Title = "Money Market Account Mission Incredible Frozen Chair"
                        },
                        new
                        {
                            ID = 72,
                            Author = "Mossie Rice",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=646",
                            Description = "Tempora ut autem accusamus ea dicta nostrum non deleniti eum quibusdam ab in illum enim dolorem dolor amet ut non.",
                            ISBN = 267924791,
                            PageCount = 881,
                            PublicationDate = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Runte LLC",
                            Title = "communities withdrawal Qatari Rial"
                        },
                        new
                        {
                            ID = 73,
                            Author = "Nathen Goodwin",
                            Category = "fuga",
                            CoverPage = "https://picsum.photos/50/50/?image=460",
                            Description = "Praesentium ullam est aut aut hic sequi beatae voluptate et enim possimus non cupiditate ut quia expedita reiciendis reiciendis eum.",
                            ISBN = 862807061,
                            PageCount = 774,
                            PublicationDate = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Flatley Inc",
                            Title = "Virginia override Kansas"
                        },
                        new
                        {
                            ID = 74,
                            Author = "Elvie McDermott",
                            Category = "voluptates",
                            CoverPage = "https://picsum.photos/50/50/?image=286",
                            Description = "Rerum itaque voluptas id accusamus quae animi optio amet ut et quo veritatis veritatis quo quia aperiam laborum praesentium labore.",
                            ISBN = 326749860,
                            PageCount = 841,
                            PublicationDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lebsack, Rippin and Padberg",
                            Title = "Product Plastic Licensed Frozen Car"
                        },
                        new
                        {
                            ID = 75,
                            Author = "Johnny Bernier",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=400",
                            Description = "Iusto voluptatibus dolor non eius nobis iure assumenda velit aut sed totam quae quia voluptatem qui vel cum autem reprehenderit.",
                            ISBN = 270883989,
                            PageCount = 331,
                            PublicationDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Sawayn LLC",
                            Title = "Gorgeous Concrete Keyboard Infrastructure ADP"
                        },
                        new
                        {
                            ID = 76,
                            Author = "Easton Sawayn",
                            Category = "nulla",
                            CoverPage = "https://picsum.photos/50/50/?image=704",
                            Description = "Quis assumenda aut ut numquam et ut deserunt assumenda nulla culpa eius consequatur cum nostrum sed quo vitae ipsa voluptas.",
                            ISBN = 609953850,
                            PageCount = 746,
                            PublicationDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schowalter Inc",
                            Title = "leading-edge Analyst Upgradable"
                        },
                        new
                        {
                            ID = 77,
                            Author = "Rylan Kirlin",
                            Category = "quasi",
                            CoverPage = "https://picsum.photos/50/50/?image=651",
                            Description = "Non nobis quod aut quos perferendis quo maiores debitis expedita architecto sit dolor doloremque incidunt quo ut quos quo aut.",
                            ISBN = 729782788,
                            PageCount = 570,
                            PublicationDate = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Jacobi, Harris and Monahan",
                            Title = "Unbranded functionalities Auto Loan Account"
                        },
                        new
                        {
                            ID = 78,
                            Author = "Luisa Quigley",
                            Category = "quod",
                            CoverPage = "https://picsum.photos/50/50/?image=1041",
                            Description = "Corporis amet soluta et et a maxime doloremque voluptatem et aut asperiores dolorem natus doloremque repellendus perferendis vel esse sunt.",
                            ISBN = 867671170,
                            PageCount = 490,
                            PublicationDate = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Vandervort, Daugherty and Barrows",
                            Title = "Bedfordshire contingency UIC-Franc"
                        },
                        new
                        {
                            ID = 79,
                            Author = "Mikayla Boyer",
                            Category = "cum",
                            CoverPage = "https://picsum.photos/50/50/?image=631",
                            Description = "Repellat labore omnis mollitia dicta nostrum eos minima quia quibusdam non distinctio fuga libero a aut ratione molestiae sed dolorem.",
                            ISBN = 952348641,
                            PageCount = 252,
                            PublicationDate = new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "O'Hara, Batz and Schulist",
                            Title = "quantifying streamline National"
                        },
                        new
                        {
                            ID = 80,
                            Author = "Barrett Sipes",
                            Category = "quaerat",
                            CoverPage = "https://picsum.photos/50/50/?image=501",
                            Description = "Id recusandae id vero perferendis est voluptate illum reiciendis omnis molestiae architecto voluptatem exercitationem officiis quia neque aperiam veritatis dolorem.",
                            ISBN = 827775810,
                            PageCount = 209,
                            PublicationDate = new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Morissette, Huels and Roob",
                            Title = "Accounts Credit Card Account Metal"
                        },
                        new
                        {
                            ID = 81,
                            Author = "Leonardo Zemlak",
                            Category = "et",
                            CoverPage = "https://picsum.photos/50/50/?image=937",
                            Description = "Atque dolorem praesentium dicta et quod et nostrum dignissimos explicabo quod eum sunt sit rerum suscipit dolor enim unde at.",
                            ISBN = 448230623,
                            PageCount = 797,
                            PublicationDate = new DateTime(2023, 9, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rippin - Keeling",
                            Title = "Frozen Credit Card Account communities"
                        },
                        new
                        {
                            ID = 82,
                            Author = "Mittie Powlowski",
                            Category = "occaecati",
                            CoverPage = "https://picsum.photos/50/50/?image=43",
                            Description = "Sapiente ratione sint maiores maiores dolores maiores dolor rerum quia nihil perferendis cupiditate quis aspernatur eveniet aut est in ipsum.",
                            ISBN = 676743446,
                            PageCount = 343,
                            PublicationDate = new DateTime(2023, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Williamson and Sons",
                            Title = "portals Ouguiya Central"
                        },
                        new
                        {
                            ID = 83,
                            Author = "Chaim Schultz",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=671",
                            Description = "Illum et aperiam et et nam omnis eum ab consequatur facere ea ducimus est modi qui nulla illo qui eum.",
                            ISBN = 199478769,
                            PageCount = 579,
                            PublicationDate = new DateTime(2023, 11, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kautzer - Robel",
                            Title = "Investor Rustic Metal Gloves Industrial, Grocery & Toys"
                        },
                        new
                        {
                            ID = 84,
                            Author = "Queen Barrows",
                            Category = "libero",
                            CoverPage = "https://picsum.photos/50/50/?image=213",
                            Description = "Dolores sit aliquid qui sed illum non sed sequi ut eos necessitatibus vel aut ratione consequuntur culpa earum ab aperiam.",
                            ISBN = 957440822,
                            PageCount = 266,
                            PublicationDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lebsack, Nienow and Rutherford",
                            Title = "Specialist Synergized PNG"
                        },
                        new
                        {
                            ID = 85,
                            Author = "Chadrick Thompson",
                            Category = "tempore",
                            CoverPage = "https://picsum.photos/50/50/?image=565",
                            Description = "Eum dolore debitis eos voluptatem aperiam reprehenderit provident enim amet officiis modi culpa blanditiis totam alias eos ea consequuntur omnis.",
                            ISBN = 252166184,
                            PageCount = 977,
                            PublicationDate = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hickle, Roob and Jerde",
                            Title = "e-services pink Soft"
                        },
                        new
                        {
                            ID = 86,
                            Author = "Megane Feest",
                            Category = "sint",
                            CoverPage = "https://picsum.photos/50/50/?image=526",
                            Description = "Dolor eos consequatur officia numquam eaque nulla natus ut veritatis debitis occaecati placeat ad at in tempora sapiente numquam iusto.",
                            ISBN = 969590767,
                            PageCount = 96,
                            PublicationDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "King, Windler and Lockman",
                            Title = "Avon Auto Loan Account Terrace"
                        },
                        new
                        {
                            ID = 87,
                            Author = "Lon Will",
                            Category = "asperiores",
                            CoverPage = "https://picsum.photos/50/50/?image=80",
                            Description = "Laboriosam molestias et veritatis quia praesentium et eum nihil dolores ab aut est quo hic sint itaque eos molestiae qui.",
                            ISBN = 853135604,
                            PageCount = 671,
                            PublicationDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Johnston Group",
                            Title = "Utah virtual program"
                        },
                        new
                        {
                            ID = 88,
                            Author = "Haven Conroy",
                            Category = "beatae",
                            CoverPage = "https://picsum.photos/50/50/?image=548",
                            Description = "Consectetur quo consequatur dignissimos in nesciunt consequatur dolor atque saepe vel perspiciatis eius id dolor placeat optio nihil atque sunt.",
                            ISBN = 458988991,
                            PageCount = 287,
                            PublicationDate = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Funk Group",
                            Title = "magenta Investor hard drive"
                        },
                        new
                        {
                            ID = 89,
                            Author = "Roxanne Carter",
                            Category = "aut",
                            CoverPage = "https://picsum.photos/50/50/?image=1036",
                            Description = "Aliquam pariatur voluptas autem asperiores omnis saepe ut ex alias soluta eos in sit ullam voluptatem corrupti sint omnis provident.",
                            ISBN = 836110580,
                            PageCount = 265,
                            PublicationDate = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kuhic - Lueilwitz",
                            Title = "generating content killer"
                        },
                        new
                        {
                            ID = 90,
                            Author = "Declan Schulist",
                            Category = "possimus",
                            CoverPage = "https://picsum.photos/50/50/?image=514",
                            Description = "Adipisci asperiores rerum atque fugiat architecto aut qui et dignissimos officiis sed suscipit ab et est temporibus atque est voluptatem.",
                            ISBN = 733239327,
                            PageCount = 856,
                            PublicationDate = new DateTime(2023, 9, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kertzmann Inc",
                            Title = "SCSI interactive Isle"
                        },
                        new
                        {
                            ID = 91,
                            Author = "Randal Gerlach",
                            Category = "aliquid",
                            CoverPage = "https://picsum.photos/50/50/?image=49",
                            Description = "Necessitatibus odit totam odio et vitae doloribus voluptatem nulla quis distinctio accusamus ut rem modi laboriosam porro eveniet aliquid sed.",
                            ISBN = 391118516,
                            PageCount = 600,
                            PublicationDate = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lang, Weissnat and Bartell",
                            Title = "Overpass coherent niches"
                        },
                        new
                        {
                            ID = 92,
                            Author = "Sanford Tromp",
                            Category = "omnis",
                            CoverPage = "https://picsum.photos/50/50/?image=164",
                            Description = "Fugiat minima consequatur incidunt explicabo ut at labore aut facere accusamus eveniet ut quod voluptas ut dolores nihil placeat alias.",
                            ISBN = 321545648,
                            PageCount = 439,
                            PublicationDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Fadel Inc",
                            Title = "navigating Tasty circuit"
                        },
                        new
                        {
                            ID = 93,
                            Author = "Ivy VonRueden",
                            Category = "accusantium",
                            CoverPage = "https://picsum.photos/50/50/?image=878",
                            Description = "Fugit reprehenderit sequi et qui ad consequatur ducimus consectetur consequatur eaque et vel placeat ab autem ipsa aperiam aut saepe.",
                            ISBN = 388769637,
                            PageCount = 58,
                            PublicationDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Olson and Sons",
                            Title = "Via bandwidth pixel"
                        },
                        new
                        {
                            ID = 94,
                            Author = "Ezequiel Kemmer",
                            Category = "explicabo",
                            CoverPage = "https://picsum.photos/50/50/?image=792",
                            Description = "Minus autem asperiores alias dolores eum veniam quo sit atque dignissimos alias velit temporibus id officiis expedita ut repudiandae rerum.",
                            ISBN = 884444004,
                            PageCount = 955,
                            PublicationDate = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kilback and Sons",
                            Title = "SQL Forges yellow"
                        },
                        new
                        {
                            ID = 95,
                            Author = "Matteo Goldner",
                            Category = "rerum",
                            CoverPage = "https://picsum.photos/50/50/?image=350",
                            Description = "In aut sequi iste dicta ea quia et excepturi ducimus autem aperiam qui aliquid laboriosam nam placeat qui non accusamus.",
                            ISBN = 553284259,
                            PageCount = 634,
                            PublicationDate = new DateTime(2023, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bergnaum - Kshlerin",
                            Title = "deposit Human Unbranded Steel Bacon"
                        },
                        new
                        {
                            ID = 96,
                            Author = "Breanna Anderson",
                            Category = "quis",
                            CoverPage = "https://picsum.photos/50/50/?image=810",
                            Description = "Aut vel unde officia modi non dolores saepe quod ut quaerat quis adipisci occaecati dolores voluptate aut eligendi pariatur rerum.",
                            ISBN = 844180651,
                            PageCount = 411,
                            PublicationDate = new DateTime(2024, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Considine Group",
                            Title = "Peru cutting-edge Principal"
                        },
                        new
                        {
                            ID = 97,
                            Author = "Eloise Koss",
                            Category = "id",
                            CoverPage = "https://picsum.photos/50/50/?image=277",
                            Description = "Ut quia natus amet et quam porro commodi sunt ex culpa ex aut modi magnam enim eum eligendi omnis ipsum.",
                            ISBN = 732461167,
                            PageCount = 552,
                            PublicationDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "McLaughlin, Prosacco and Satterfield",
                            Title = "Denar Synchronised overriding"
                        },
                        new
                        {
                            ID = 98,
                            Author = "Colton Jaskolski",
                            Category = "est",
                            CoverPage = "https://picsum.photos/50/50/?image=81",
                            Description = "Occaecati eos illo quo tenetur quo aut qui iure eveniet ex nam hic voluptas porro officia est incidunt sapiente quidem.",
                            ISBN = 386064541,
                            PageCount = 986,
                            PublicationDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Howe, Halvorson and Cronin",
                            Title = "AI Ohio aggregate"
                        },
                        new
                        {
                            ID = 99,
                            Author = "Braden Kertzmann",
                            Category = "beatae",
                            CoverPage = "https://picsum.photos/50/50/?image=689",
                            Description = "Est consequatur facilis rerum ducimus quas in aut sit velit in deserunt quia est ipsum similique consequatur nam necessitatibus ipsam.",
                            ISBN = 863253150,
                            PageCount = 894,
                            PublicationDate = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lindgren LLC",
                            Title = "South Carolina Jersey Rustic Frozen Computer"
                        },
                        new
                        {
                            ID = 100,
                            Author = "Donnie Schinner",
                            Category = "magni",
                            CoverPage = "https://picsum.photos/50/50/?image=271",
                            Description = "Voluptatum necessitatibus vel facilis est velit maiores libero sunt ducimus voluptatem velit enim quia repellat ut totam voluptatibus autem sint.",
                            ISBN = 591758949,
                            PageCount = 250,
                            PublicationDate = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Botsford and Sons",
                            Title = "5th generation 24 hour Cuban Peso"
                        });
                });

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.UserAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ROLE");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("ID");

                    b.ToTable("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
