// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalAssessmentRokov.Data;

#nullable disable

namespace TechnicalAssessmentRokov.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240615043328_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUTHOR");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("CoverPage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COVER_PAGE");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("ISBN")
                        .HasColumnType("int")
                        .HasColumnName("ISBN");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("PAGE_COUNT");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PUBLICATION_DATE");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PUBLISHER");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Johathan Mayert",
                            Category = "omnis",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Similique voluptatem quo magni in quis voluptate doloremque rerum quia vel ut tenetur aspernatur eum tenetur repellat perspiciatis sint aliquid.",
                            ISBN = 337858267,
                            PageCount = 162,
                            PublicationDate = new DateTime(2023, 6, 26, 0, 42, 40, 852, DateTimeKind.Local).AddTicks(3930),
                            Publisher = "Abernathy - Murphy"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Phyllis Cremin",
                            Category = "aut",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Aliquam sit et nemo tempora natus qui itaque deleniti magni nesciunt aut dignissimos minima nihil soluta est asperiores quasi nam.",
                            ISBN = 832865458,
                            PageCount = 269,
                            PublicationDate = new DateTime(2023, 8, 5, 21, 32, 7, 27, DateTimeKind.Local).AddTicks(4843),
                            Publisher = "Wisoky and Sons"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Daija Collier",
                            Category = "temporibus",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Eveniet quidem quia autem amet ipsam id amet minima consectetur ea laborum aliquid odio laborum dicta nemo quia et voluptates.",
                            ISBN = 120918662,
                            PageCount = 412,
                            PublicationDate = new DateTime(2023, 8, 14, 21, 36, 48, 195, DateTimeKind.Local).AddTicks(1517),
                            Publisher = "Fahey - Kertzmann"
                        },
                        new
                        {
                            ID = 4,
                            Author = "Dayne Huel",
                            Category = "qui",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Repellat ut cumque veniam ea blanditiis et ipsum ut qui cum laudantium et labore est animi sed at iusto quo.",
                            ISBN = 634849498,
                            PageCount = 863,
                            PublicationDate = new DateTime(2024, 2, 7, 8, 5, 10, 837, DateTimeKind.Local).AddTicks(1639),
                            Publisher = "Schulist, Ward and Kemmer"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Sasha Kerluke",
                            Category = "porro",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Animi ad eum eligendi doloribus possimus dolore in amet amet beatae expedita totam incidunt quas vel molestiae eum ipsum libero.",
                            ISBN = 283181214,
                            PageCount = 496,
                            PublicationDate = new DateTime(2023, 8, 20, 6, 8, 42, 840, DateTimeKind.Local).AddTicks(4166),
                            Publisher = "Roob - Emmerich"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Abraham Lemke",
                            Category = "velit",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Architecto doloribus dolor voluptatibus aut corrupti sed et iure facilis totam laboriosam doloribus nulla possimus distinctio ipsum non quasi ut.",
                            ISBN = 261138113,
                            PageCount = 932,
                            PublicationDate = new DateTime(2024, 2, 14, 7, 13, 44, 999, DateTimeKind.Local).AddTicks(3827),
                            Publisher = "Howe LLC"
                        },
                        new
                        {
                            ID = 7,
                            Author = "Billy Cormier",
                            Category = "provident",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Est enim sint qui consequatur ea qui aperiam incidunt enim qui saepe sit et sit eos ipsam provident officia qui.",
                            ISBN = 460841448,
                            PageCount = 377,
                            PublicationDate = new DateTime(2023, 11, 20, 11, 31, 9, 572, DateTimeKind.Local).AddTicks(816),
                            Publisher = "Jerde, Hodkiewicz and Schamberger"
                        },
                        new
                        {
                            ID = 8,
                            Author = "Vicky Berge",
                            Category = "illo",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Ratione et eum magnam ipsa sunt vel ut ut nostrum saepe ad earum natus adipisci eos pariatur architecto sint aut.",
                            ISBN = 787101472,
                            PageCount = 942,
                            PublicationDate = new DateTime(2024, 2, 21, 7, 48, 28, 156, DateTimeKind.Local).AddTicks(4542),
                            Publisher = "Mills, Schulist and Weimann"
                        },
                        new
                        {
                            ID = 9,
                            Author = "Emil Romaguera",
                            Category = "quisquam",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Esse accusamus quidem laudantium nam a labore beatae ducimus enim culpa iure quasi enim cupiditate fugit qui repellendus dolorem odit.",
                            ISBN = 166555776,
                            PageCount = 873,
                            PublicationDate = new DateTime(2024, 2, 2, 6, 48, 40, 54, DateTimeKind.Local).AddTicks(9767),
                            Publisher = "Weissnat, Watsica and Hane"
                        },
                        new
                        {
                            ID = 10,
                            Author = "Carleton Hagenes",
                            Category = "velit",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Rem provident eius autem commodi corrupti perspiciatis quo voluptas earum rerum rerum sed voluptatem in velit facilis minima quia autem.",
                            ISBN = 343511952,
                            PageCount = 952,
                            PublicationDate = new DateTime(2023, 10, 31, 0, 29, 35, 966, DateTimeKind.Local).AddTicks(269),
                            Publisher = "Howell - Cremin"
                        },
                        new
                        {
                            ID = 11,
                            Author = "Ernest Pacocha",
                            Category = "eaque",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Voluptas repellendus est asperiores in iusto corporis voluptatem nemo et quis autem et ex minus aperiam debitis labore maiores sed.",
                            ISBN = 563557638,
                            PageCount = 967,
                            PublicationDate = new DateTime(2023, 8, 27, 17, 33, 46, 631, DateTimeKind.Local).AddTicks(799),
                            Publisher = "Harvey LLC"
                        },
                        new
                        {
                            ID = 12,
                            Author = "Elvera Cartwright",
                            Category = "aut",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Consequatur aperiam quibusdam unde cum et nostrum fugiat ut ea quibusdam voluptatem non expedita ut quo aliquam et rerum explicabo.",
                            ISBN = 772543864,
                            PageCount = 69,
                            PublicationDate = new DateTime(2023, 10, 18, 0, 54, 7, 237, DateTimeKind.Local).AddTicks(2508),
                            Publisher = "Ortiz, Bartoletti and Stanton"
                        },
                        new
                        {
                            ID = 13,
                            Author = "Jordan Stamm",
                            Category = "recusandae",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Et ullam consequatur omnis delectus molestiae eveniet earum amet voluptatem dolorem molestiae iusto ullam earum quia sed molestiae et explicabo.",
                            ISBN = 787296053,
                            PageCount = 457,
                            PublicationDate = new DateTime(2023, 9, 4, 0, 21, 0, 988, DateTimeKind.Local).AddTicks(2779),
                            Publisher = "Tromp and Sons"
                        },
                        new
                        {
                            ID = 14,
                            Author = "Peter Bashirian",
                            Category = "ducimus",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Dolores non vitae et earum blanditiis vitae praesentium quos porro eveniet deleniti beatae voluptatem ad voluptatum sed qui perferendis qui.",
                            ISBN = 177169724,
                            PageCount = 517,
                            PublicationDate = new DateTime(2023, 8, 13, 11, 46, 15, 317, DateTimeKind.Local).AddTicks(9652),
                            Publisher = "Tillman - Gislason"
                        },
                        new
                        {
                            ID = 15,
                            Author = "Brook Feest",
                            Category = "autem",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Voluptatem fuga modi et voluptatem earum qui reiciendis totam illum itaque cupiditate aliquid vero et iste ut non ut laudantium.",
                            ISBN = 608372290,
                            PageCount = 970,
                            PublicationDate = new DateTime(2023, 10, 16, 2, 20, 6, 306, DateTimeKind.Local).AddTicks(1662),
                            Publisher = "Mraz, Botsford and Jaskolski"
                        },
                        new
                        {
                            ID = 16,
                            Author = "Jevon Williamson",
                            Category = "corporis",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Aut adipisci ullam est expedita vitae vel et sed adipisci est distinctio veniam voluptas iure officia eum sit est eaque.",
                            ISBN = 453956261,
                            PageCount = 419,
                            PublicationDate = new DateTime(2023, 8, 30, 17, 55, 31, 613, DateTimeKind.Local).AddTicks(81),
                            Publisher = "Hammes, Langosh and Wiza"
                        },
                        new
                        {
                            ID = 17,
                            Author = "Antwan Wuckert",
                            Category = "veniam",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Earum nesciunt iusto iusto id necessitatibus labore quia fugit repudiandae quisquam voluptatum fuga assumenda numquam ut non reiciendis sapiente voluptas.",
                            ISBN = 309992702,
                            PageCount = 621,
                            PublicationDate = new DateTime(2023, 11, 11, 12, 35, 30, 245, DateTimeKind.Local).AddTicks(221),
                            Publisher = "Reinger - Weissnat"
                        },
                        new
                        {
                            ID = 18,
                            Author = "Angelo Walsh",
                            Category = "accusantium",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Repellendus praesentium aut neque aperiam est dolorem cupiditate maxime dicta placeat aut qui aut libero quam repellat omnis iusto recusandae.",
                            ISBN = 150040109,
                            PageCount = 434,
                            PublicationDate = new DateTime(2023, 10, 20, 23, 32, 8, 332, DateTimeKind.Local).AddTicks(2633),
                            Publisher = "Stehr Inc"
                        },
                        new
                        {
                            ID = 19,
                            Author = "Giles Reichert",
                            Category = "eligendi",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Eum dolorem sequi amet doloribus laboriosam sint vitae rerum harum id natus autem necessitatibus harum recusandae cumque quae neque quo.",
                            ISBN = 325349025,
                            PageCount = 913,
                            PublicationDate = new DateTime(2024, 3, 17, 15, 41, 26, 37, DateTimeKind.Local).AddTicks(6683),
                            Publisher = "Bernhard - Powlowski"
                        },
                        new
                        {
                            ID = 20,
                            Author = "Elvie Monahan",
                            Category = "omnis",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Labore minima est et consectetur voluptatem ullam provident ad est et nulla fugiat quaerat dolores deserunt aut explicabo ex blanditiis.",
                            ISBN = 325519142,
                            PageCount = 325,
                            PublicationDate = new DateTime(2024, 2, 14, 0, 6, 33, 968, DateTimeKind.Local).AddTicks(4078),
                            Publisher = "Bernier Group"
                        },
                        new
                        {
                            ID = 21,
                            Author = "Hiram Schaefer",
                            Category = "fugiat",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Doloribus natus voluptatem sint consequatur exercitationem exercitationem commodi quia corporis fugit neque totam eos et tempore sint suscipit voluptas cumque.",
                            ISBN = 547388664,
                            PageCount = 741,
                            PublicationDate = new DateTime(2023, 12, 16, 23, 9, 14, 280, DateTimeKind.Local).AddTicks(1199),
                            Publisher = "Daugherty, Botsford and Altenwerth"
                        },
                        new
                        {
                            ID = 22,
                            Author = "Laron Goldner",
                            Category = "quod",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Et placeat quia ea in consequatur unde optio tempora repudiandae accusamus voluptas exercitationem accusamus et voluptas a ratione ipsam earum.",
                            ISBN = 205599035,
                            PageCount = 267,
                            PublicationDate = new DateTime(2023, 8, 9, 19, 22, 54, 900, DateTimeKind.Local).AddTicks(7534),
                            Publisher = "Pfeffer - Hettinger"
                        },
                        new
                        {
                            ID = 23,
                            Author = "Dejuan Waters",
                            Category = "neque",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Delectus magnam aut error dolor exercitationem qui debitis aut eum nostrum alias maiores repudiandae eum et nemo exercitationem recusandae sit.",
                            ISBN = 437039200,
                            PageCount = 551,
                            PublicationDate = new DateTime(2023, 6, 26, 22, 20, 34, 272, DateTimeKind.Local).AddTicks(7766),
                            Publisher = "Bauch - Hegmann"
                        },
                        new
                        {
                            ID = 24,
                            Author = "Eliza Mann",
                            Category = "veniam",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Quod quas ab incidunt ea ullam reiciendis velit dignissimos corrupti repellendus error natus nam ut quidem ducimus officiis ut debitis.",
                            ISBN = 525302048,
                            PageCount = 656,
                            PublicationDate = new DateTime(2024, 5, 12, 16, 14, 46, 12, DateTimeKind.Local).AddTicks(9010),
                            Publisher = "Jerde LLC"
                        },
                        new
                        {
                            ID = 25,
                            Author = "Elwyn White",
                            Category = "ut",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Possimus suscipit quia dolores sint nihil et saepe est reiciendis atque modi qui qui exercitationem hic quam eum ipsum qui.",
                            ISBN = 789992300,
                            PageCount = 933,
                            PublicationDate = new DateTime(2023, 9, 15, 16, 3, 7, 715, DateTimeKind.Local).AddTicks(3743),
                            Publisher = "Weissnat Inc"
                        },
                        new
                        {
                            ID = 26,
                            Author = "Elmer Hettinger",
                            Category = "adipisci",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Ipsam fugiat ducimus omnis est aliquid quo veniam autem molestias alias repellendus quia veniam et cupiditate error enim asperiores autem.",
                            ISBN = 151794424,
                            PageCount = 649,
                            PublicationDate = new DateTime(2024, 4, 20, 7, 52, 12, 827, DateTimeKind.Local).AddTicks(1712),
                            Publisher = "Effertz, Nicolas and Block"
                        },
                        new
                        {
                            ID = 27,
                            Author = "Letitia Larkin",
                            Category = "accusamus",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Similique ab rerum quis omnis nostrum et et enim minima voluptate dolor architecto repellat ex consequatur fugiat non quod explicabo.",
                            ISBN = 817086741,
                            PageCount = 81,
                            PublicationDate = new DateTime(2023, 10, 16, 10, 50, 19, 297, DateTimeKind.Local).AddTicks(661),
                            Publisher = "Franecki - Grant"
                        },
                        new
                        {
                            ID = 28,
                            Author = "Jaquan Toy",
                            Category = "suscipit",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Alias ipsum occaecati facere quia sit quaerat dolores qui corporis sed voluptates officiis enim quidem doloribus quia neque corporis qui.",
                            ISBN = 910346169,
                            PageCount = 151,
                            PublicationDate = new DateTime(2023, 12, 7, 11, 28, 43, 895, DateTimeKind.Local).AddTicks(3406),
                            Publisher = "Torp, Olson and Ledner"
                        },
                        new
                        {
                            ID = 29,
                            Author = "Conrad Wiegand",
                            Category = "vero",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Facilis voluptatibus ipsum velit sed deserunt doloribus placeat fugit nemo nisi a eos ut quidem est harum ratione sit quia.",
                            ISBN = 779361781,
                            PageCount = 152,
                            PublicationDate = new DateTime(2023, 10, 29, 1, 20, 14, 216, DateTimeKind.Local).AddTicks(7561),
                            Publisher = "Shanahan - Sawayn"
                        },
                        new
                        {
                            ID = 30,
                            Author = "Hassan Kuhn",
                            Category = "facilis",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Corporis quisquam repellendus eaque voluptates id quo necessitatibus aliquid eius porro exercitationem sit aliquid vitae praesentium nisi quod sit molestias.",
                            ISBN = 381911763,
                            PageCount = 119,
                            PublicationDate = new DateTime(2024, 5, 13, 14, 8, 55, 813, DateTimeKind.Local).AddTicks(4462),
                            Publisher = "Rosenbaum - Howe"
                        },
                        new
                        {
                            ID = 31,
                            Author = "Jules Wiegand",
                            Category = "accusantium",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Blanditiis libero accusantium nisi possimus sequi quam molestias aliquid modi ad ut recusandae est explicabo qui consequuntur qui iusto aperiam.",
                            ISBN = 996401248,
                            PageCount = 801,
                            PublicationDate = new DateTime(2023, 11, 1, 17, 27, 56, 818, DateTimeKind.Local).AddTicks(7020),
                            Publisher = "Aufderhar - Gorczany"
                        },
                        new
                        {
                            ID = 32,
                            Author = "Ruthie Howe",
                            Category = "aliquam",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Molestiae vel quibusdam voluptas accusantium sit autem velit at cumque suscipit reprehenderit illum dolor molestiae maiores omnis nostrum fugiat laudantium.",
                            ISBN = 302739295,
                            PageCount = 514,
                            PublicationDate = new DateTime(2023, 9, 27, 12, 17, 22, 705, DateTimeKind.Local).AddTicks(7852),
                            Publisher = "Cormier LLC"
                        },
                        new
                        {
                            ID = 33,
                            Author = "Aniya Welch",
                            Category = "delectus",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Quasi minus adipisci iure sit est sit reiciendis voluptatem minima a quis natus magnam aliquam numquam animi exercitationem et praesentium.",
                            ISBN = 369094778,
                            PageCount = 583,
                            PublicationDate = new DateTime(2024, 1, 3, 22, 23, 2, 373, DateTimeKind.Local).AddTicks(1339),
                            Publisher = "Turcotte, Konopelski and Turner"
                        },
                        new
                        {
                            ID = 34,
                            Author = "Roxanne Thompson",
                            Category = "repellendus",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Sint voluptas molestias sint aut voluptatum rerum ipsa omnis quidem saepe rerum provident cumque facere sequi quasi et aut sunt.",
                            ISBN = 991058835,
                            PageCount = 684,
                            PublicationDate = new DateTime(2024, 2, 16, 2, 53, 9, 449, DateTimeKind.Local).AddTicks(669),
                            Publisher = "Mosciski and Sons"
                        },
                        new
                        {
                            ID = 35,
                            Author = "Salvatore Ondricka",
                            Category = "qui",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Aut omnis ad voluptatem et qui assumenda sed aut molestias consequuntur recusandae totam voluptatum dicta aut suscipit sequi autem dolor.",
                            ISBN = 467198733,
                            PageCount = 366,
                            PublicationDate = new DateTime(2024, 2, 17, 23, 20, 0, 40, DateTimeKind.Local).AddTicks(6370),
                            Publisher = "Waelchi and Sons"
                        },
                        new
                        {
                            ID = 36,
                            Author = "Elinore Little",
                            Category = "optio",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Ullam consequatur molestias est minima laboriosam omnis similique magnam optio illum magni nesciunt sequi quasi vitae maiores corrupti et similique.",
                            ISBN = 899437181,
                            PageCount = 995,
                            PublicationDate = new DateTime(2023, 11, 21, 18, 56, 56, 823, DateTimeKind.Local).AddTicks(9824),
                            Publisher = "Wilderman, Wilderman and Luettgen"
                        },
                        new
                        {
                            ID = 37,
                            Author = "Cristina Kunde",
                            Category = "tempore",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Est id quia at rem dolore enim est perspiciatis nisi in qui provident assumenda quia iure voluptates perspiciatis ullam in.",
                            ISBN = 837092921,
                            PageCount = 769,
                            PublicationDate = new DateTime(2023, 8, 10, 23, 16, 35, 62, DateTimeKind.Local).AddTicks(6326),
                            Publisher = "Sanford - Schiller"
                        },
                        new
                        {
                            ID = 38,
                            Author = "Daren Denesik",
                            Category = "incidunt",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Veritatis consequuntur ut ut dicta maiores cumque exercitationem voluptas quibusdam nihil dicta odio saepe consequatur nesciunt dolor et atque molestiae.",
                            ISBN = 717883923,
                            PageCount = 538,
                            PublicationDate = new DateTime(2023, 8, 20, 5, 4, 20, 434, DateTimeKind.Local).AddTicks(3797),
                            Publisher = "Kessler, Simonis and Kshlerin"
                        },
                        new
                        {
                            ID = 39,
                            Author = "Audrey Wilkinson",
                            Category = "enim",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Praesentium ut nostrum consequatur quo saepe sunt aut quia ex enim alias laudantium et magni laboriosam eligendi aperiam rerum consequatur.",
                            ISBN = 328631835,
                            PageCount = 664,
                            PublicationDate = new DateTime(2023, 7, 22, 16, 4, 49, 934, DateTimeKind.Local).AddTicks(7671),
                            Publisher = "Jenkins - Haley"
                        },
                        new
                        {
                            ID = 40,
                            Author = "Helmer Kuhlman",
                            Category = "aut",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Explicabo qui ducimus cupiditate rerum quia itaque accusantium quaerat rem ex odio dolor et dolorem et sit ea odio placeat.",
                            ISBN = 498607606,
                            PageCount = 923,
                            PublicationDate = new DateTime(2023, 9, 19, 14, 36, 19, 740, DateTimeKind.Local).AddTicks(5490),
                            Publisher = "Reinger, Green and Bins"
                        },
                        new
                        {
                            ID = 41,
                            Author = "Veda Mraz",
                            Category = "eum",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Quasi est illum unde temporibus beatae omnis iste natus quisquam non optio voluptate quisquam maiores recusandae reiciendis dolorem qui commodi.",
                            ISBN = 818103179,
                            PageCount = 624,
                            PublicationDate = new DateTime(2023, 10, 30, 9, 52, 58, 141, DateTimeKind.Local).AddTicks(1337),
                            Publisher = "Legros - Effertz"
                        },
                        new
                        {
                            ID = 42,
                            Author = "Devin Wunsch",
                            Category = "culpa",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Et ducimus ut nisi et repudiandae a assumenda consequatur cupiditate minima voluptatem laborum rerum qui sint qui totam unde ipsum.",
                            ISBN = 336758362,
                            PageCount = 197,
                            PublicationDate = new DateTime(2023, 11, 25, 20, 6, 36, 189, DateTimeKind.Local).AddTicks(282),
                            Publisher = "Blick, Ruecker and Mayer"
                        },
                        new
                        {
                            ID = 43,
                            Author = "Marques Tromp",
                            Category = "voluptas",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Sed voluptatem in accusantium officia voluptatem sit autem esse minus non sed atque tempora ut deleniti dolores excepturi ipsa ea.",
                            ISBN = 899316811,
                            PageCount = 161,
                            PublicationDate = new DateTime(2023, 12, 28, 20, 16, 10, 985, DateTimeKind.Local).AddTicks(5545),
                            Publisher = "Waters, Langosh and Wisoky"
                        },
                        new
                        {
                            ID = 44,
                            Author = "Dejuan Tromp",
                            Category = "consequatur",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Exercitationem soluta molestiae vero veritatis similique voluptatem voluptas similique rem maiores vel eos veritatis est et quis vero vel nam.",
                            ISBN = 533180930,
                            PageCount = 410,
                            PublicationDate = new DateTime(2023, 12, 16, 14, 43, 25, 730, DateTimeKind.Local).AddTicks(4052),
                            Publisher = "Block Inc"
                        },
                        new
                        {
                            ID = 45,
                            Author = "Jordi Heller",
                            Category = "quos",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Quae alias officia quae laborum veniam nobis aut qui suscipit omnis exercitationem totam dolores et qui ut tempora et accusantium.",
                            ISBN = 812235245,
                            PageCount = 461,
                            PublicationDate = new DateTime(2024, 1, 10, 16, 29, 58, 983, DateTimeKind.Local).AddTicks(1077),
                            Publisher = "Kautzer and Sons"
                        },
                        new
                        {
                            ID = 46,
                            Author = "Julie Rempel",
                            Category = "deserunt",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Eos similique earum accusantium tempore consequatur ut debitis laborum tempora consectetur animi iure culpa unde qui est consequuntur nesciunt eos.",
                            ISBN = 905743485,
                            PageCount = 226,
                            PublicationDate = new DateTime(2023, 7, 2, 13, 54, 47, 327, DateTimeKind.Local).AddTicks(8577),
                            Publisher = "Hodkiewicz Inc"
                        },
                        new
                        {
                            ID = 47,
                            Author = "Freeman Reilly",
                            Category = "iste",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Beatae minus ut repudiandae officia autem vitae beatae id culpa deleniti qui blanditiis nam dignissimos quo repellat odit nihil voluptatem.",
                            ISBN = 149516215,
                            PageCount = 996,
                            PublicationDate = new DateTime(2024, 3, 12, 1, 35, 0, 348, DateTimeKind.Local).AddTicks(6231),
                            Publisher = "Rempel - Murray"
                        },
                        new
                        {
                            ID = 48,
                            Author = "Verona Kulas",
                            Category = "architecto",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Voluptas itaque rerum esse soluta maiores ab quo sint consequuntur occaecati in error animi numquam sint voluptatibus est sapiente qui.",
                            ISBN = 885359883,
                            PageCount = 189,
                            PublicationDate = new DateTime(2023, 9, 29, 22, 30, 13, 875, DateTimeKind.Local).AddTicks(2674),
                            Publisher = "Witting, Sawayn and Christiansen"
                        },
                        new
                        {
                            ID = 49,
                            Author = "Dameon Jacobi",
                            Category = "eum",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Expedita ut ratione vel iure quis nesciunt ut aut delectus tenetur dolorem quibusdam eaque repellat reiciendis et nostrum quis architecto.",
                            ISBN = 443754219,
                            PageCount = 379,
                            PublicationDate = new DateTime(2024, 3, 23, 4, 1, 10, 665, DateTimeKind.Local).AddTicks(3492),
                            Publisher = "Nicolas and Sons"
                        },
                        new
                        {
                            ID = 50,
                            Author = "Ivy Casper",
                            Category = "provident",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Sunt ipsum quis perspiciatis dolorum accusantium dolorem qui dolor et magni non asperiores saepe eos voluptatum sed recusandae est nisi.",
                            ISBN = 691729683,
                            PageCount = 694,
                            PublicationDate = new DateTime(2024, 4, 20, 3, 13, 37, 66, DateTimeKind.Local).AddTicks(1069),
                            Publisher = "Bahringer and Sons"
                        },
                        new
                        {
                            ID = 51,
                            Author = "Jimmy Kling",
                            Category = "pariatur",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Sed harum laudantium cupiditate dolores laudantium eligendi et quam et reiciendis explicabo sint itaque nemo fuga et est quibusdam repudiandae.",
                            ISBN = 176426366,
                            PageCount = 588,
                            PublicationDate = new DateTime(2023, 6, 25, 11, 57, 45, 717, DateTimeKind.Local).AddTicks(5546),
                            Publisher = "Cartwright, Hand and Heathcote"
                        },
                        new
                        {
                            ID = 52,
                            Author = "Stacy Stoltenberg",
                            Category = "cum",
                            CoverPage = "http://lorempixel.com/640/480/technics",
                            Description = "Illum consequatur magni ducimus ab necessitatibus eius totam animi expedita optio cupiditate et rerum veritatis sint sunt et ut est.",
                            ISBN = 344861615,
                            PageCount = 476,
                            PublicationDate = new DateTime(2024, 1, 31, 18, 1, 35, 673, DateTimeKind.Local).AddTicks(6061),
                            Publisher = "Miller, Reilly and Feest"
                        },
                        new
                        {
                            ID = 53,
                            Author = "Mozell Hessel",
                            Category = "corrupti",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Nam voluptatem nobis ut qui et et quam consequuntur quibusdam voluptates ut in animi eum eos tenetur voluptate cum culpa.",
                            ISBN = 374689772,
                            PageCount = 831,
                            PublicationDate = new DateTime(2023, 8, 12, 11, 16, 29, 543, DateTimeKind.Local).AddTicks(7152),
                            Publisher = "Marquardt and Sons"
                        },
                        new
                        {
                            ID = 54,
                            Author = "Beth Steuber",
                            Category = "soluta",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Deserunt laboriosam nobis quibusdam iure nobis et similique consectetur explicabo aut et qui quo nobis distinctio fugiat error ea aut.",
                            ISBN = 734286898,
                            PageCount = 887,
                            PublicationDate = new DateTime(2023, 9, 27, 4, 5, 37, 353, DateTimeKind.Local).AddTicks(8654),
                            Publisher = "Jaskolski - Borer"
                        },
                        new
                        {
                            ID = 55,
                            Author = "Heath Schulist",
                            Category = "quasi",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Aut sequi cupiditate dignissimos eum veniam et fugiat necessitatibus voluptas vitae porro voluptate velit praesentium blanditiis fugit soluta aut voluptas.",
                            ISBN = 366113326,
                            PageCount = 597,
                            PublicationDate = new DateTime(2024, 3, 23, 15, 57, 27, 784, DateTimeKind.Local).AddTicks(9917),
                            Publisher = "Robel - McCullough"
                        },
                        new
                        {
                            ID = 56,
                            Author = "Bruce Ryan",
                            Category = "in",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Repudiandae illum alias odio nulla voluptatibus voluptatum inventore ut occaecati esse mollitia natus eos quasi recusandae distinctio voluptates vel et.",
                            ISBN = 494723568,
                            PageCount = 242,
                            PublicationDate = new DateTime(2024, 4, 8, 20, 17, 3, 133, DateTimeKind.Local).AddTicks(8290),
                            Publisher = "Jast Group"
                        },
                        new
                        {
                            ID = 57,
                            Author = "Alycia Cruickshank",
                            Category = "esse",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Blanditiis nisi cumque dolor est consequatur eos error tempora ratione impedit quibusdam quia est unde consectetur quia nulla tempore numquam.",
                            ISBN = 676686782,
                            PageCount = 984,
                            PublicationDate = new DateTime(2023, 10, 18, 18, 47, 9, 771, DateTimeKind.Local).AddTicks(7750),
                            Publisher = "Hayes - Hand"
                        },
                        new
                        {
                            ID = 58,
                            Author = "Kyler Pouros",
                            Category = "laboriosam",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Placeat ipsam magni quia voluptates illum qui eos quisquam itaque explicabo cumque ut quisquam consequatur dicta dolor consectetur totam doloribus.",
                            ISBN = 418335231,
                            PageCount = 916,
                            PublicationDate = new DateTime(2023, 10, 22, 12, 0, 16, 44, DateTimeKind.Local).AddTicks(2456),
                            Publisher = "Pacocha - MacGyver"
                        },
                        new
                        {
                            ID = 59,
                            Author = "Dewitt Hammes",
                            Category = "aut",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Voluptatem qui atque provident tempore sit perferendis sed et necessitatibus atque tempora sunt corrupti eos odit sunt voluptas repellat explicabo.",
                            ISBN = 552131495,
                            PageCount = 262,
                            PublicationDate = new DateTime(2023, 9, 9, 0, 38, 0, 804, DateTimeKind.Local).AddTicks(2425),
                            Publisher = "Hermiston and Sons"
                        },
                        new
                        {
                            ID = 60,
                            Author = "Emmie Muller",
                            Category = "quas",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Qui vero omnis ipsa labore totam eligendi reiciendis rerum rerum ab laboriosam molestiae ratione dolor est iure dolorem itaque rem.",
                            ISBN = 415776534,
                            PageCount = 554,
                            PublicationDate = new DateTime(2024, 1, 7, 6, 6, 8, 139, DateTimeKind.Local).AddTicks(4498),
                            Publisher = "Sauer LLC"
                        },
                        new
                        {
                            ID = 61,
                            Author = "Cleveland Welch",
                            Category = "nisi",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Voluptate nulla quas in deleniti ex sed eum et veritatis et accusamus asperiores sapiente architecto minus libero nobis reiciendis et.",
                            ISBN = 840594304,
                            PageCount = 163,
                            PublicationDate = new DateTime(2024, 2, 21, 6, 58, 52, 469, DateTimeKind.Local).AddTicks(2753),
                            Publisher = "Kuhn Group"
                        },
                        new
                        {
                            ID = 62,
                            Author = "Kendall Braun",
                            Category = "possimus",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Fugit vel sunt esse impedit eius deserunt accusantium magni ab fugiat non et qui et nihil similique dolores aliquid qui.",
                            ISBN = 436642244,
                            PageCount = 151,
                            PublicationDate = new DateTime(2024, 6, 3, 14, 17, 40, 462, DateTimeKind.Local).AddTicks(8050),
                            Publisher = "Lowe Inc"
                        },
                        new
                        {
                            ID = 63,
                            Author = "Barry Monahan",
                            Category = "esse",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Cupiditate culpa mollitia omnis ut est facere voluptatem id dignissimos et voluptas non fugiat dignissimos mollitia expedita quidem delectus veritatis.",
                            ISBN = 614451971,
                            PageCount = 400,
                            PublicationDate = new DateTime(2023, 9, 3, 20, 47, 38, 593, DateTimeKind.Local).AddTicks(3824),
                            Publisher = "Barrows, Spinka and Moen"
                        },
                        new
                        {
                            ID = 64,
                            Author = "Amelie Macejkovic",
                            Category = "et",
                            CoverPage = "http://lorempixel.com/640/480/technics",
                            Description = "Atque omnis tempora molestiae odit numquam cupiditate sunt totam atque qui non vitae molestias deleniti maiores consequatur impedit non optio.",
                            ISBN = 148488973,
                            PageCount = 630,
                            PublicationDate = new DateTime(2023, 8, 11, 17, 56, 1, 52, DateTimeKind.Local).AddTicks(3448),
                            Publisher = "Medhurst, Dietrich and Schmeler"
                        },
                        new
                        {
                            ID = 65,
                            Author = "Albert Wilkinson",
                            Category = "eaque",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Distinctio et nemo doloremque pariatur sit odio enim et omnis fugiat nostrum impedit unde labore qui sit sunt quia quas.",
                            ISBN = 142893242,
                            PageCount = 863,
                            PublicationDate = new DateTime(2023, 7, 7, 16, 13, 56, 854, DateTimeKind.Local).AddTicks(9788),
                            Publisher = "Fadel - Mueller"
                        },
                        new
                        {
                            ID = 66,
                            Author = "Francesco Morar",
                            Category = "aut",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Dicta omnis necessitatibus et qui facere totam quo sint aut non dolorem amet iste error odit sit perspiciatis voluptas ut.",
                            ISBN = 922446586,
                            PageCount = 915,
                            PublicationDate = new DateTime(2023, 10, 24, 14, 33, 37, 409, DateTimeKind.Local).AddTicks(7505),
                            Publisher = "Thiel, White and Mayert"
                        },
                        new
                        {
                            ID = 67,
                            Author = "Vena Krajcik",
                            Category = "voluptatibus",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Libero hic dolorem ea et eligendi quasi ab illum fugit quod et minima optio nihil ipsum numquam sit at laudantium.",
                            ISBN = 278040285,
                            PageCount = 313,
                            PublicationDate = new DateTime(2023, 9, 8, 18, 34, 29, 373, DateTimeKind.Local).AddTicks(8215),
                            Publisher = "Davis, Waters and Champlin"
                        },
                        new
                        {
                            ID = 68,
                            Author = "Sasha Bogan",
                            Category = "cum",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Ut pariatur consequatur ipsam nihil in velit voluptatum iste enim ut recusandae perferendis ut nihil voluptas sint laboriosam sapiente hic.",
                            ISBN = 670963916,
                            PageCount = 146,
                            PublicationDate = new DateTime(2023, 12, 4, 0, 35, 52, 819, DateTimeKind.Local).AddTicks(4205),
                            Publisher = "Bradtke - Bradtke"
                        },
                        new
                        {
                            ID = 69,
                            Author = "Delphine Ondricka",
                            Category = "reiciendis",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Atque corporis maxime dolorem pariatur amet labore ipsa vel velit consequatur molestias id autem accusantium sapiente vel eos deleniti cumque.",
                            ISBN = 944718754,
                            PageCount = 167,
                            PublicationDate = new DateTime(2023, 12, 11, 3, 47, 37, 413, DateTimeKind.Local).AddTicks(2376),
                            Publisher = "Mills - Satterfield"
                        },
                        new
                        {
                            ID = 70,
                            Author = "Lorenza Luettgen",
                            Category = "doloremque",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Nam expedita ratione similique esse autem perferendis cupiditate qui minus harum blanditiis eaque et qui recusandae dicta quasi in adipisci.",
                            ISBN = 270051331,
                            PageCount = 289,
                            PublicationDate = new DateTime(2023, 8, 23, 2, 49, 8, 644, DateTimeKind.Local).AddTicks(3268),
                            Publisher = "Hintz - Swaniawski"
                        },
                        new
                        {
                            ID = 71,
                            Author = "Sylvia Herzog",
                            Category = "magnam",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Mollitia fugit quam consequatur perspiciatis maiores voluptatem corporis sunt dolores sunt magnam sapiente et impedit neque molestiae qui dolorem vitae.",
                            ISBN = 639111344,
                            PageCount = 550,
                            PublicationDate = new DateTime(2023, 9, 3, 8, 15, 57, 642, DateTimeKind.Local).AddTicks(4209),
                            Publisher = "Kutch - Wiegand"
                        },
                        new
                        {
                            ID = 72,
                            Author = "Georgianna Johnston",
                            Category = "non",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Deleniti dolorem saepe magni eaque dolorem harum voluptate nostrum officia quaerat qui dolorem voluptate rerum cum qui nobis eveniet dignissimos.",
                            ISBN = 244431985,
                            PageCount = 914,
                            PublicationDate = new DateTime(2024, 5, 20, 17, 18, 4, 467, DateTimeKind.Local).AddTicks(4236),
                            Publisher = "Rogahn - Dare"
                        },
                        new
                        {
                            ID = 73,
                            Author = "Cedrick Quitzon",
                            Category = "ea",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Quo non exercitationem enim blanditiis rem eos assumenda facilis voluptatem velit perspiciatis fuga aliquam et sit ipsum voluptatem quia aspernatur.",
                            ISBN = 704805735,
                            PageCount = 385,
                            PublicationDate = new DateTime(2023, 9, 6, 0, 28, 14, 636, DateTimeKind.Local).AddTicks(4584),
                            Publisher = "Howell, Weissnat and Jones"
                        },
                        new
                        {
                            ID = 74,
                            Author = "Lina Larkin",
                            Category = "amet",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Consequatur architecto ab non iure et numquam eveniet saepe vero ut eius nisi repellat quos quas laborum consequatur porro voluptates.",
                            ISBN = 403879274,
                            PageCount = 535,
                            PublicationDate = new DateTime(2023, 7, 1, 23, 5, 46, 104, DateTimeKind.Local).AddTicks(5067),
                            Publisher = "Konopelski - Hartmann"
                        },
                        new
                        {
                            ID = 75,
                            Author = "Jesse Deckow",
                            Category = "quis",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Ipsa tempora quasi temporibus voluptatibus sunt ipsam veritatis dolore maxime mollitia aliquid placeat dicta et accusantium soluta rerum officia ab.",
                            ISBN = 223688917,
                            PageCount = 534,
                            PublicationDate = new DateTime(2023, 8, 28, 8, 52, 18, 683, DateTimeKind.Local).AddTicks(7472),
                            Publisher = "Cole, Hayes and Veum"
                        },
                        new
                        {
                            ID = 76,
                            Author = "Samir Turcotte",
                            Category = "saepe",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Aut ut suscipit provident voluptatem esse quia unde debitis dicta minus et odio reiciendis deleniti facere qui id aut mollitia.",
                            ISBN = 175394973,
                            PageCount = 152,
                            PublicationDate = new DateTime(2023, 9, 19, 6, 24, 27, 994, DateTimeKind.Local).AddTicks(7479),
                            Publisher = "Hagenes - Kihn"
                        },
                        new
                        {
                            ID = 77,
                            Author = "Brandy Murphy",
                            Category = "similique",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Qui reprehenderit id est sint quae optio totam et omnis eveniet minima rerum necessitatibus consectetur sunt nisi inventore occaecati quo.",
                            ISBN = 568024228,
                            PageCount = 581,
                            PublicationDate = new DateTime(2023, 12, 28, 22, 8, 9, 622, DateTimeKind.Local).AddTicks(9067),
                            Publisher = "Pfannerstill, Barrows and Hessel"
                        },
                        new
                        {
                            ID = 78,
                            Author = "Harold Collins",
                            Category = "aliquid",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Temporibus et et non aliquid et est et non modi aut quo pariatur et nulla ut quia quidem fugiat aliquam.",
                            ISBN = 461539763,
                            PageCount = 357,
                            PublicationDate = new DateTime(2023, 9, 3, 3, 40, 26, 875, DateTimeKind.Local).AddTicks(3717),
                            Publisher = "Pfeffer - Nikolaus"
                        },
                        new
                        {
                            ID = 79,
                            Author = "Kenny Bradtke",
                            Category = "illum",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Voluptatibus et sint et commodi dolor labore libero culpa qui aperiam pariatur non quaerat nobis voluptatem voluptas explicabo et quaerat.",
                            ISBN = 641651659,
                            PageCount = 74,
                            PublicationDate = new DateTime(2024, 1, 12, 11, 54, 9, 311, DateTimeKind.Local).AddTicks(4653),
                            Publisher = "Grant - Wyman"
                        },
                        new
                        {
                            ID = 80,
                            Author = "Cristina Hegmann",
                            Category = "odit",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Est dolor rerum quod nisi rem repudiandae illo mollitia fugit deserunt quo aut voluptatem repellendus hic quia ut quia voluptatem.",
                            ISBN = 135728408,
                            PageCount = 301,
                            PublicationDate = new DateTime(2023, 9, 12, 6, 8, 16, 915, DateTimeKind.Local).AddTicks(9637),
                            Publisher = "Swaniawski Group"
                        },
                        new
                        {
                            ID = 81,
                            Author = "Jeffrey Huel",
                            Category = "sint",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Et nulla consequuntur quae atque eos accusantium dolor quis numquam numquam autem nihil delectus qui dolores dolores quo et autem.",
                            ISBN = 139987759,
                            PageCount = 494,
                            PublicationDate = new DateTime(2024, 4, 16, 21, 36, 21, 229, DateTimeKind.Local).AddTicks(9696),
                            Publisher = "Hyatt - Bergnaum"
                        },
                        new
                        {
                            ID = 82,
                            Author = "Quentin Johns",
                            Category = "est",
                            CoverPage = "http://lorempixel.com/640/480/technics",
                            Description = "Quo velit et quae totam quaerat exercitationem et rem temporibus omnis incidunt ut officia cupiditate rerum sit sed illo facilis.",
                            ISBN = 255445364,
                            PageCount = 215,
                            PublicationDate = new DateTime(2024, 2, 17, 16, 22, 6, 942, DateTimeKind.Local).AddTicks(1189),
                            Publisher = "Lockman, Hane and Kulas"
                        },
                        new
                        {
                            ID = 83,
                            Author = "Betsy Gutkowski",
                            Category = "explicabo",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Sed deserunt et totam ut qui rerum praesentium autem ducimus ex quibusdam est dolorem delectus dolorem praesentium aut ea quos.",
                            ISBN = 886873545,
                            PageCount = 254,
                            PublicationDate = new DateTime(2023, 7, 30, 17, 12, 57, 646, DateTimeKind.Local).AddTicks(3522),
                            Publisher = "Mitchell Group"
                        },
                        new
                        {
                            ID = 84,
                            Author = "Raymond Torphy",
                            Category = "quo",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Repudiandae quia hic rerum aliquid aspernatur nobis aut numquam rerum amet provident deserunt aut officia dicta dicta hic eius similique.",
                            ISBN = 484825689,
                            PageCount = 943,
                            PublicationDate = new DateTime(2023, 9, 20, 13, 43, 30, 671, DateTimeKind.Local).AddTicks(9933),
                            Publisher = "Stark, Hamill and DuBuque"
                        },
                        new
                        {
                            ID = 85,
                            Author = "Martina Crona",
                            Category = "veniam",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Non qui et vel est quidem voluptas voluptate harum labore corrupti nobis rem dolorum ut ut vel esse quia consequatur.",
                            ISBN = 746481693,
                            PageCount = 935,
                            PublicationDate = new DateTime(2023, 9, 16, 19, 36, 7, 27, DateTimeKind.Local).AddTicks(349),
                            Publisher = "Ernser, Corkery and Jast"
                        },
                        new
                        {
                            ID = 86,
                            Author = "Faye Renner",
                            Category = "occaecati",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Aut cupiditate facere at consequatur amet reprehenderit dolorum perspiciatis maiores totam iusto autem magni velit et vel labore magni sint.",
                            ISBN = 201512373,
                            PageCount = 505,
                            PublicationDate = new DateTime(2023, 6, 20, 1, 14, 42, 855, DateTimeKind.Local).AddTicks(9051),
                            Publisher = "Schinner LLC"
                        },
                        new
                        {
                            ID = 87,
                            Author = "Jan Bergnaum",
                            Category = "earum",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Unde sit velit dolor sint veniam voluptas quasi quae ea corporis qui ut cum aspernatur aut quod voluptas voluptatem totam.",
                            ISBN = 920328111,
                            PageCount = 637,
                            PublicationDate = new DateTime(2023, 10, 16, 12, 44, 54, 780, DateTimeKind.Local).AddTicks(2660),
                            Publisher = "Mosciski - Bailey"
                        },
                        new
                        {
                            ID = 88,
                            Author = "Cade Bayer",
                            Category = "inventore",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Eaque quas inventore molestias reiciendis est harum et atque voluptatem ad atque nihil quaerat optio quod dolor eaque accusantium illo.",
                            ISBN = 470325144,
                            PageCount = 971,
                            PublicationDate = new DateTime(2023, 12, 27, 2, 45, 18, 982, DateTimeKind.Local).AddTicks(3281),
                            Publisher = "Bernhard, Fahey and Cartwright"
                        },
                        new
                        {
                            ID = 89,
                            Author = "Bernie Schmeler",
                            Category = "eligendi",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Recusandae voluptatem rem et ipsa provident nemo aut exercitationem quaerat consequatur id expedita quaerat neque temporibus corrupti quibusdam consectetur ratione.",
                            ISBN = 248269937,
                            PageCount = 687,
                            PublicationDate = new DateTime(2024, 1, 13, 13, 48, 28, 289, DateTimeKind.Local).AddTicks(9859),
                            Publisher = "Hermann, Hyatt and Hyatt"
                        },
                        new
                        {
                            ID = 90,
                            Author = "Burnice Volkman",
                            Category = "corrupti",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Odit delectus omnis similique ex praesentium voluptas qui deserunt rerum excepturi odit vel et quasi molestiae saepe ea ut et.",
                            ISBN = 268647512,
                            PageCount = 862,
                            PublicationDate = new DateTime(2023, 9, 13, 4, 19, 21, 383, DateTimeKind.Local).AddTicks(7429),
                            Publisher = "Christiansen Group"
                        },
                        new
                        {
                            ID = 91,
                            Author = "Jerod Nolan",
                            Category = "error",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Aut illum debitis saepe mollitia qui perspiciatis facere commodi vitae molestiae quia cum dolores autem eum omnis dolore id quia.",
                            ISBN = 568804717,
                            PageCount = 173,
                            PublicationDate = new DateTime(2023, 7, 15, 9, 30, 42, 998, DateTimeKind.Local).AddTicks(3659),
                            Publisher = "Kuvalis, Casper and Schaefer"
                        },
                        new
                        {
                            ID = 92,
                            Author = "Hal Cartwright",
                            Category = "maxime",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Animi et repellat quidem eos debitis eaque mollitia commodi dolorum qui eveniet molestiae debitis ut quia possimus molestiae vel ratione.",
                            ISBN = 101168636,
                            PageCount = 229,
                            PublicationDate = new DateTime(2024, 6, 3, 17, 43, 28, 78, DateTimeKind.Local).AddTicks(277),
                            Publisher = "Lakin, Reynolds and Parker"
                        },
                        new
                        {
                            ID = 93,
                            Author = "Princess Legros",
                            Category = "voluptatibus",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Dolores voluptatum delectus porro aut qui recusandae ea laborum expedita voluptas eaque sit et nobis et maiores optio est voluptas.",
                            ISBN = 625603896,
                            PageCount = 606,
                            PublicationDate = new DateTime(2024, 4, 6, 14, 36, 0, 65, DateTimeKind.Local).AddTicks(1381),
                            Publisher = "Williamson Group"
                        },
                        new
                        {
                            ID = 94,
                            Author = "Buster Collins",
                            Category = "totam",
                            CoverPage = "http://lorempixel.com/640/480/technics",
                            Description = "Ab tenetur eos nihil non minus et maiores tenetur voluptatibus eligendi laudantium et ipsum blanditiis rem molestias harum officiis dolorum.",
                            ISBN = 680140906,
                            PageCount = 597,
                            PublicationDate = new DateTime(2023, 10, 15, 19, 29, 59, 702, DateTimeKind.Local).AddTicks(9027),
                            Publisher = "Moen - Mosciski"
                        },
                        new
                        {
                            ID = 95,
                            Author = "Hailey Medhurst",
                            Category = "magnam",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Voluptatem odio consequatur consequuntur temporibus voluptates sed dolor voluptatem autem vel nihil ab sed cumque inventore perferendis saepe ut doloribus.",
                            ISBN = 544175228,
                            PageCount = 581,
                            PublicationDate = new DateTime(2024, 1, 13, 17, 52, 50, 978, DateTimeKind.Local).AddTicks(3837),
                            Publisher = "Fahey - Kassulke"
                        },
                        new
                        {
                            ID = 96,
                            Author = "Brook Ankunding",
                            Category = "distinctio",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Aut qui odit optio aut aut explicabo et at fuga aut placeat harum neque magni repudiandae enim sunt ducimus culpa.",
                            ISBN = 404937735,
                            PageCount = 650,
                            PublicationDate = new DateTime(2024, 5, 18, 1, 2, 2, 160, DateTimeKind.Local).AddTicks(8973),
                            Publisher = "Bayer - Barton"
                        },
                        new
                        {
                            ID = 97,
                            Author = "Willis Bartell",
                            Category = "optio",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Id quidem eveniet blanditiis porro id consequatur hic cumque unde itaque temporibus similique vitae ratione aspernatur sapiente dolorem quaerat dolor.",
                            ISBN = 722670085,
                            PageCount = 209,
                            PublicationDate = new DateTime(2023, 12, 7, 2, 23, 30, 55, DateTimeKind.Local).AddTicks(8598),
                            Publisher = "Armstrong Inc"
                        },
                        new
                        {
                            ID = 98,
                            Author = "Kraig Pagac",
                            Category = "eligendi",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Ut est asperiores esse in ea nihil amet minima facilis et enim quia quasi dolor error laborum labore ut sit.",
                            ISBN = 280544257,
                            PageCount = 989,
                            PublicationDate = new DateTime(2024, 4, 10, 1, 36, 11, 136, DateTimeKind.Local).AddTicks(8796),
                            Publisher = "Kerluke LLC"
                        },
                        new
                        {
                            ID = 99,
                            Author = "Victoria Frami",
                            Category = "suscipit",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Assumenda beatae ut minus voluptatum aut excepturi modi ut rerum vel nobis quo sint ut delectus eaque qui assumenda possimus.",
                            ISBN = 193000125,
                            PageCount = 731,
                            PublicationDate = new DateTime(2024, 6, 5, 23, 47, 40, 353, DateTimeKind.Local).AddTicks(3602),
                            Publisher = "Cruickshank, Thiel and Heller"
                        },
                        new
                        {
                            ID = 100,
                            Author = "Rupert Oberbrunner",
                            Category = "nobis",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Accusantium officia non est voluptas ut ratione est sapiente ad omnis modi ea inventore nisi debitis voluptas eveniet qui facere.",
                            ISBN = 717451259,
                            PageCount = 968,
                            PublicationDate = new DateTime(2024, 5, 31, 13, 30, 1, 788, DateTimeKind.Local).AddTicks(4202),
                            Publisher = "Lueilwitz, Deckow and Turcotte"
                        });
                });

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.UserAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ROLE");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("ID");

                    b.ToTable("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
