// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalAssessmentRokov.Data;

#nullable disable

namespace TechnicalAssessmentRokov.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240615050834_BookTitle")]
    partial class BookTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUTHOR");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("CoverPage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COVER_PAGE");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("ISBN")
                        .HasColumnType("int")
                        .HasColumnName("ISBN");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("PAGE_COUNT");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PUBLICATION_DATE");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PUBLISHER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Chaya Ebert",
                            Category = "voluptatem",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Velit libero et ea quia atque omnis illum id voluptatem in id est sunt qui porro ducimus ut qui facere.",
                            ISBN = 719112186,
                            PageCount = 285,
                            PublicationDate = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schinner and Sons",
                            Title = "SMS Future Fantastic Fresh Mouse"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Toni Dibbert",
                            Category = "est",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Ducimus reprehenderit eligendi consequuntur ut minima incidunt facere ducimus tempora et quis asperiores sed assumenda quasi est iste doloribus veritatis.",
                            ISBN = 620981663,
                            PageCount = 709,
                            PublicationDate = new DateTime(2023, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Reichert, Rice and Fay",
                            Title = "North Korean Won Assistant Triple-buffered"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Cecilia Toy",
                            Category = "tempora",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Hic est possimus quo sunt magni nostrum non asperiores illum rem porro illum iure quia neque nihil sequi saepe corporis.",
                            ISBN = 156016180,
                            PageCount = 664,
                            PublicationDate = new DateTime(2023, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lakin LLC",
                            Title = "Synchronised Customer generate"
                        },
                        new
                        {
                            ID = 4,
                            Author = "Rebeka Feeney",
                            Category = "ab",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Voluptas eum quam quis cupiditate quos itaque quia temporibus molestiae eligendi eius alias dolorem laboriosam quis aliquid quos necessitatibus quae.",
                            ISBN = 186794475,
                            PageCount = 565,
                            PublicationDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schaefer, Fritsch and Wehner",
                            Title = "Washington synthesizing capacitor"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Kay Hirthe",
                            Category = "et",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Voluptate sed dolores inventore consequatur autem modi velit fugiat praesentium assumenda qui iste minus est sint dolorem voluptatibus hic necessitatibus.",
                            ISBN = 447083779,
                            PageCount = 781,
                            PublicationDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schmitt, Mosciski and Daugherty",
                            Title = "International Borders Checking Account"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Shany Schamberger",
                            Category = "est",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Nihil in sint ea rerum dolorem dolorum et ut et consequuntur autem accusamus omnis sequi odio laborum sed asperiores sit.",
                            ISBN = 832943868,
                            PageCount = 273,
                            PublicationDate = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Raynor and Sons",
                            Title = "Myanmar ability Tasty Plastic Ball"
                        },
                        new
                        {
                            ID = 7,
                            Author = "Arturo Bednar",
                            Category = "odit",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Minus dicta eius illum maiores assumenda repellendus corporis molestias enim molestiae qui velit ipsa tenetur itaque molestiae perferendis sit eligendi.",
                            ISBN = 703592172,
                            PageCount = 592,
                            PublicationDate = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kutch, Harvey and Little",
                            Title = "Corners Regional Home & Industrial"
                        },
                        new
                        {
                            ID = 8,
                            Author = "Ulises Lockman",
                            Category = "expedita",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Dolor sint sit enim sit facilis fuga consequatur magni tenetur inventore ipsum eius est sed distinctio nostrum quia ab dolorem.",
                            ISBN = 478710962,
                            PageCount = 451,
                            PublicationDate = new DateTime(2023, 8, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kuphal - McGlynn",
                            Title = "metrics Neck violet"
                        },
                        new
                        {
                            ID = 9,
                            Author = "Berneice Runolfsdottir",
                            Category = "distinctio",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Reiciendis et repudiandae sed repellendus debitis alias consequuntur et exercitationem et cum molestiae officiis dignissimos et vel in accusantium et.",
                            ISBN = 407407585,
                            PageCount = 436,
                            PublicationDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gorczany - Kuphal",
                            Title = "Awesome Concrete Shirt Refined open-source"
                        },
                        new
                        {
                            ID = 10,
                            Author = "Geovanni Stokes",
                            Category = "ab",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Temporibus suscipit sit iure vitae ipsa veritatis non magni aut corporis nam autem natus aut totam dolore sunt non fuga.",
                            ISBN = 820533879,
                            PageCount = 501,
                            PublicationDate = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Johnson, Krajcik and Breitenberg",
                            Title = "Zimbabwe Stand-alone Producer"
                        },
                        new
                        {
                            ID = 11,
                            Author = "Mathias King",
                            Category = "unde",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Necessitatibus dolorem inventore similique in quaerat adipisci fugit saepe quia sit placeat distinctio molestiae repellendus quam vero saepe in natus.",
                            ISBN = 814037030,
                            PageCount = 125,
                            PublicationDate = new DateTime(2023, 11, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hansen, Legros and Jerde",
                            Title = "Fork card Group"
                        },
                        new
                        {
                            ID = 12,
                            Author = "Viviane Emard",
                            Category = "ut",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Dolor omnis praesentium est aut possimus iste tenetur nemo nostrum aut ab deleniti repellendus sint odio qui voluptas eos eligendi.",
                            ISBN = 716425415,
                            PageCount = 686,
                            PublicationDate = new DateTime(2023, 11, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Goyette, Will and Fay",
                            Title = "Cliffs functionalities overriding"
                        },
                        new
                        {
                            ID = 13,
                            Author = "Britney Parker",
                            Category = "impedit",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Voluptas magnam eos consequatur quisquam perferendis eaque eveniet quos voluptatem et eum iste aut voluptatem modi ut tempora et est.",
                            ISBN = 724375439,
                            PageCount = 91,
                            PublicationDate = new DateTime(2023, 7, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ziemann LLC",
                            Title = "generate programming Ways"
                        },
                        new
                        {
                            ID = 14,
                            Author = "Ulices Keeling",
                            Category = "quia",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Culpa et est asperiores eum dolorum dignissimos veniam expedita repellat reiciendis fuga reiciendis aut autem quasi at neque est est.",
                            ISBN = 553362131,
                            PageCount = 988,
                            PublicationDate = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Parker - Prohaska",
                            Title = "Cape Verde Escudo uniform Rupiah"
                        },
                        new
                        {
                            ID = 15,
                            Author = "Neha Cartwright",
                            Category = "suscipit",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Debitis culpa neque ducimus deleniti quis perspiciatis occaecati temporibus et non occaecati a voluptas eum maiores cum et et cum.",
                            ISBN = 291730208,
                            PageCount = 827,
                            PublicationDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Walter Group",
                            Title = "productize SMS Implementation"
                        },
                        new
                        {
                            ID = 16,
                            Author = "Jarred Durgan",
                            Category = "facere",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Qui saepe est eum iure dignissimos nam facilis sequi odio praesentium rerum soluta deleniti ut hic consequatur distinctio ex eum.",
                            ISBN = 540684635,
                            PageCount = 849,
                            PublicationDate = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Batz and Sons",
                            Title = "4th generation Turnpike Home & Outdoors"
                        },
                        new
                        {
                            ID = 17,
                            Author = "Mattie Bayer",
                            Category = "voluptate",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Maiores in sit ad et doloribus eveniet dicta iusto et eaque delectus ut non quidem numquam dolorem eaque dolore voluptates.",
                            ISBN = 676104445,
                            PageCount = 189,
                            PublicationDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Beier Inc",
                            Title = "Course open-source Chief"
                        },
                        new
                        {
                            ID = 18,
                            Author = "Heber Balistreri",
                            Category = "veritatis",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Aut nulla facilis quas quae doloremque est soluta aperiam qui provident aut asperiores ab optio consequatur numquam maxime nihil illo.",
                            ISBN = 536269419,
                            PageCount = 273,
                            PublicationDate = new DateTime(2023, 7, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Donnelly, Torphy and Bogisich",
                            Title = "ADP synergize seize"
                        },
                        new
                        {
                            ID = 19,
                            Author = "Delia Considine",
                            Category = "quisquam",
                            CoverPage = "http://lorempixel.com/640/480/technics",
                            Description = "Sunt est numquam est aut voluptas fuga tempora repellat deleniti impedit asperiores similique a corrupti ullam sit labore debitis illo.",
                            ISBN = 717254092,
                            PageCount = 74,
                            PublicationDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gerlach Inc",
                            Title = "technologies Borders e-business"
                        },
                        new
                        {
                            ID = 20,
                            Author = "Brianne Goodwin",
                            Category = "quo",
                            CoverPage = "http://lorempixel.com/640/480/technics",
                            Description = "Itaque totam dicta vel harum dicta occaecati beatae quisquam veritatis accusantium ipsum dolorem facilis dolore id porro nobis quis architecto.",
                            ISBN = 710968872,
                            PageCount = 720,
                            PublicationDate = new DateTime(2023, 10, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Fritsch, Farrell and Weimann",
                            Title = "Handcrafted Plastic Gloves Supervisor Rustic Soft Shirt"
                        },
                        new
                        {
                            ID = 21,
                            Author = "Chelsie Anderson",
                            Category = "reiciendis",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Minima voluptate aut esse aut ut voluptate accusamus sed et ducimus vitae et excepturi corrupti magnam explicabo est et quia.",
                            ISBN = 379662337,
                            PageCount = 810,
                            PublicationDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Becker, Schiller and Schinner",
                            Title = "International Switchable Ranch"
                        },
                        new
                        {
                            ID = 22,
                            Author = "Berneice Strosin",
                            Category = "aut",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Non sequi quia qui fugit explicabo facilis impedit ut harum nisi eum eos quae unde accusantium qui laborum est necessitatibus.",
                            ISBN = 805785502,
                            PageCount = 313,
                            PublicationDate = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bergnaum Inc",
                            Title = "Industrial, Sports & Music Organic Intelligent Concrete Bacon"
                        },
                        new
                        {
                            ID = 23,
                            Author = "Yoshiko Herzog",
                            Category = "exercitationem",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Tempore deleniti ut similique qui ex totam vel laboriosam fugit sint beatae laborum saepe sit et non laborum ipsum quia.",
                            ISBN = 802578984,
                            PageCount = 893,
                            PublicationDate = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Armstrong, Strosin and Hamill",
                            Title = "firewall Intelligent Rubber Soap Borders"
                        },
                        new
                        {
                            ID = 24,
                            Author = "Turner Kirlin",
                            Category = "laboriosam",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Quo tenetur et porro et autem cum cum ea quia labore voluptatibus corrupti id vitae voluptatibus molestias ad vitae distinctio.",
                            ISBN = 176480398,
                            PageCount = 925,
                            PublicationDate = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Langworth, Swift and Pfeffer",
                            Title = "COM Regional THX"
                        },
                        new
                        {
                            ID = 25,
                            Author = "Juliet Collins",
                            Category = "minima",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Tempore repellat harum sequi non beatae corporis reiciendis hic corrupti odio corrupti laboriosam doloribus soluta et dolore molestiae laudantium provident.",
                            ISBN = 676026729,
                            PageCount = 123,
                            PublicationDate = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kunde - Schimmel",
                            Title = "Buckinghamshire out-of-the-box SQL"
                        },
                        new
                        {
                            ID = 26,
                            Author = "Madeline Grady",
                            Category = "doloribus",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Et praesentium voluptatem et sit id quasi beatae dignissimos provident occaecati aut enim consequuntur at error beatae maiores aut culpa.",
                            ISBN = 520297380,
                            PageCount = 88,
                            PublicationDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lesch, Reinger and McLaughlin",
                            Title = "deposit Customer bluetooth"
                        },
                        new
                        {
                            ID = 27,
                            Author = "Deven Smith",
                            Category = "saepe",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Esse aut et et consequuntur suscipit similique qui aperiam voluptate fugiat sed illum rerum blanditiis asperiores iure eum dolorum et.",
                            ISBN = 428713386,
                            PageCount = 877,
                            PublicationDate = new DateTime(2023, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "McKenzie - Donnelly",
                            Title = "sensor 24/365 cyan"
                        },
                        new
                        {
                            ID = 28,
                            Author = "Lourdes Boyer",
                            Category = "sed",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "A optio praesentium ducimus consequatur esse tempora velit ab aut ex veritatis quia unde voluptatibus ullam labore accusantium exercitationem suscipit.",
                            ISBN = 117226115,
                            PageCount = 807,
                            PublicationDate = new DateTime(2024, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Trantow, Schmitt and Tromp",
                            Title = "white Handmade Plastic"
                        },
                        new
                        {
                            ID = 29,
                            Author = "Bart Borer",
                            Category = "vero",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Error iusto ex dolores autem dolores doloremque rerum officiis ipsam corrupti dicta cum sed a ab aut delectus id ex.",
                            ISBN = 698019180,
                            PageCount = 870,
                            PublicationDate = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Boyer LLC",
                            Title = "maroon Money Market Account Gorgeous"
                        },
                        new
                        {
                            ID = 30,
                            Author = "Gayle Watsica",
                            Category = "minus",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Dolorem laboriosam aperiam accusamus molestias hic hic quo reprehenderit et laborum dolores velit et vero rerum voluptatem quisquam aspernatur voluptatem.",
                            ISBN = 535610386,
                            PageCount = 358,
                            PublicationDate = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Nader LLC",
                            Title = "connect Sierra Leone Berkshire"
                        },
                        new
                        {
                            ID = 31,
                            Author = "Rene Lakin",
                            Category = "officia",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Illum tempora iusto veritatis provident ipsa optio sint quia quo nesciunt magnam ea praesentium illo sed perspiciatis eum sint aut.",
                            ISBN = 396372741,
                            PageCount = 913,
                            PublicationDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kautzer - Gerhold",
                            Title = "Tenge scalable Garden"
                        },
                        new
                        {
                            ID = 32,
                            Author = "Deron Konopelski",
                            Category = "praesentium",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Quia illum et asperiores iste corporis et et quia doloremque nam eos culpa dolor molestias temporibus natus veniam sunt magni.",
                            ISBN = 807562640,
                            PageCount = 559,
                            PublicationDate = new DateTime(2023, 11, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schamberger, Trantow and Flatley",
                            Title = "recontextualize wireless platforms"
                        },
                        new
                        {
                            ID = 33,
                            Author = "Jasper Rolfson",
                            Category = "cumque",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Dolore dolores commodi voluptate nisi cumque quia dolorem illum odio molestiae saepe est iure et necessitatibus consequatur eveniet unde et.",
                            ISBN = 763292021,
                            PageCount = 111,
                            PublicationDate = new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Terry, Kerluke and Emmerich",
                            Title = "Cambridgeshire Kids, Music & Electronics Rubber"
                        },
                        new
                        {
                            ID = 34,
                            Author = "Tianna Balistreri",
                            Category = "nam",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Ullam inventore quod mollitia qui non veritatis consectetur corporis sit in non tempore doloremque maiores eum adipisci optio fugit nobis.",
                            ISBN = 349484663,
                            PageCount = 463,
                            PublicationDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Pouros - Klein",
                            Title = "application Unbranded Cotton Car Freeway"
                        },
                        new
                        {
                            ID = 35,
                            Author = "Lucinda Paucek",
                            Category = "veniam",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Dicta minus quia maiores iusto sapiente est dolores deserunt ut veniam qui ut qui magnam libero rem quae dolorem sunt.",
                            ISBN = 239865901,
                            PageCount = 764,
                            PublicationDate = new DateTime(2023, 9, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Dooley - Klein",
                            Title = "bottom-line Awesome Wooden Shoes Buckinghamshire"
                        },
                        new
                        {
                            ID = 36,
                            Author = "Vince Zieme",
                            Category = "necessitatibus",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Sequi temporibus consequatur omnis eos atque consequatur earum ut qui ut similique quo aut et incidunt et totam quod laboriosam.",
                            ISBN = 114993966,
                            PageCount = 266,
                            PublicationDate = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schneider - Wolf",
                            Title = "Sleek Steel Chips Reactive Monitored"
                        },
                        new
                        {
                            ID = 37,
                            Author = "Moises Cronin",
                            Category = "corrupti",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Id temporibus quam delectus natus expedita aut eos eos nihil asperiores laborum minima dolorem quos enim deleniti velit debitis laboriosam.",
                            ISBN = 556990950,
                            PageCount = 479,
                            PublicationDate = new DateTime(2023, 11, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Metz - Lubowitz",
                            Title = "Cotton Small Cotton Pizza Re-engineered"
                        },
                        new
                        {
                            ID = 38,
                            Author = "Bianka O'Hara",
                            Category = "necessitatibus",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Tempora fuga sapiente quia quia quia nihil qui quae eveniet sint et autem quo enim non voluptatem excepturi expedita sint.",
                            ISBN = 463273859,
                            PageCount = 487,
                            PublicationDate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schaden and Sons",
                            Title = "calculating Naira Viaduct"
                        },
                        new
                        {
                            ID = 39,
                            Author = "Oliver Abshire",
                            Category = "a",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Qui facilis alias aut sit quae voluptas quo animi incidunt vel voluptates rem alias est qui natus nobis in sequi.",
                            ISBN = 754517515,
                            PageCount = 963,
                            PublicationDate = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Carter Group",
                            Title = "Architect capability disintermediate"
                        },
                        new
                        {
                            ID = 40,
                            Author = "Jaquelin Heidenreich",
                            Category = "qui",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Consequatur fuga quia commodi consequatur quos asperiores et nobis velit doloribus error voluptas expedita hic natus totam ut animi et.",
                            ISBN = 317043668,
                            PageCount = 188,
                            PublicationDate = new DateTime(2023, 11, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ward, Tillman and Bogisich",
                            Title = "Incredible Rubber Cheese reboot Yuan Renminbi"
                        },
                        new
                        {
                            ID = 41,
                            Author = "Sierra Marvin",
                            Category = "sed",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Aliquid molestiae ut commodi voluptatem pariatur dignissimos aut officia iure mollitia doloremque qui rerum ea pariatur vel in voluptatem aut.",
                            ISBN = 907083923,
                            PageCount = 909,
                            PublicationDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gerlach - Reinger",
                            Title = "deliver seize olive"
                        },
                        new
                        {
                            ID = 42,
                            Author = "Samara Jacobs",
                            Category = "eaque",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Asperiores ut natus aspernatur repudiandae enim voluptas ut illum aut in rerum ut tenetur necessitatibus reprehenderit modi rem rerum aut.",
                            ISBN = 232775405,
                            PageCount = 903,
                            PublicationDate = new DateTime(2023, 9, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gutkowski, Roberts and Schaden",
                            Title = "Director Rupiah Architect"
                        },
                        new
                        {
                            ID = 43,
                            Author = "Zelda Braun",
                            Category = "et",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Facere ducimus perferendis quia eius odio molestiae maxime cumque sint error dolore vitae enim dignissimos omnis tenetur soluta eveniet sapiente.",
                            ISBN = 163841941,
                            PageCount = 66,
                            PublicationDate = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kunze Group",
                            Title = "interface Automotive ADP"
                        },
                        new
                        {
                            ID = 44,
                            Author = "Isaac Beahan",
                            Category = "cupiditate",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Ab quisquam et error et ipsa odit id quia omnis voluptas deleniti dolorem tenetur et iure dicta reiciendis voluptas amet.",
                            ISBN = 549325615,
                            PageCount = 223,
                            PublicationDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Braun - Vandervort",
                            Title = "empowering Reactive clear-thinking"
                        },
                        new
                        {
                            ID = 45,
                            Author = "Hallie Jaskolski",
                            Category = "deserunt",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Qui labore voluptas autem cupiditate occaecati debitis consectetur voluptatem corrupti consequatur voluptatibus eaque quo numquam nesciunt odio fugiat quidem quia.",
                            ISBN = 222289591,
                            PageCount = 159,
                            PublicationDate = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Auer - Hintz",
                            Title = "withdrawal hack Lempira"
                        },
                        new
                        {
                            ID = 46,
                            Author = "Lauretta Bergnaum",
                            Category = "neque",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Perspiciatis doloribus fugiat esse et voluptatem voluptas et dolore eos libero quos accusantium commodi qui perferendis numquam nesciunt aut aut.",
                            ISBN = 616903458,
                            PageCount = 469,
                            PublicationDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Torphy - Braun",
                            Title = "Security Stravenue Intelligent"
                        },
                        new
                        {
                            ID = 47,
                            Author = "Winifred Lockman",
                            Category = "ducimus",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Quasi animi sit maxime labore blanditiis fugiat tenetur aliquid error dolores aliquid odit dolorum saepe adipisci fuga quia corporis earum.",
                            ISBN = 652168087,
                            PageCount = 886,
                            PublicationDate = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Jacobson, Rohan and Roberts",
                            Title = "Home Loan Account payment Dong"
                        },
                        new
                        {
                            ID = 48,
                            Author = "Quinten Boehm",
                            Category = "corporis",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Consequatur laudantium eveniet fugit necessitatibus ut reiciendis aut perferendis velit a adipisci autem mollitia nam placeat quae ut vero hic.",
                            ISBN = 674175642,
                            PageCount = 673,
                            PublicationDate = new DateTime(2023, 11, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Fay, Hilll and Muller",
                            Title = "migration orchid Kansas"
                        },
                        new
                        {
                            ID = 49,
                            Author = "Estella Wisoky",
                            Category = "dolore",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Est voluptate enim sint culpa dolores sit quas est dignissimos dolor sint quia possimus inventore ipsam molestiae nobis reiciendis fuga.",
                            ISBN = 114120102,
                            PageCount = 641,
                            PublicationDate = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lynch, O'Reilly and Klocko",
                            Title = "Brazil core New Zealand Dollar"
                        },
                        new
                        {
                            ID = 50,
                            Author = "Stanley Collins",
                            Category = "dignissimos",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Numquam minima quos voluptate ea quaerat pariatur earum maxime voluptatem et non nostrum eveniet et natus velit nam id voluptas.",
                            ISBN = 786641385,
                            PageCount = 711,
                            PublicationDate = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Fadel, Skiles and Schmeler",
                            Title = "Handcrafted Rubber Fish Progressive North Dakota"
                        },
                        new
                        {
                            ID = 51,
                            Author = "Lucas Herzog",
                            Category = "laudantium",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Sint eaque et dolor qui deleniti aut nulla quia quos aut officia alias odit eaque voluptatem esse eum veniam dolorem.",
                            ISBN = 445282609,
                            PageCount = 900,
                            PublicationDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Macejkovic LLC",
                            Title = "Tenge mobile Factors"
                        },
                        new
                        {
                            ID = 52,
                            Author = "Amelia Satterfield",
                            Category = "impedit",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Doloremque in quo praesentium non velit soluta in aut nemo est autem temporibus dignissimos iusto eum beatae laudantium amet qui.",
                            ISBN = 863811214,
                            PageCount = 532,
                            PublicationDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Zulauf - Prosacco",
                            Title = "quantify Licensed Fresh Tuna Buckinghamshire"
                        },
                        new
                        {
                            ID = 53,
                            Author = "Saul Metz",
                            Category = "sapiente",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Et eaque omnis inventore quia quis rem facilis explicabo non illo adipisci corrupti dolorem soluta architecto enim ut ullam blanditiis.",
                            ISBN = 951528129,
                            PageCount = 143,
                            PublicationDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Jacobson and Sons",
                            Title = "Shoes bandwidth Jewelery & Sports"
                        },
                        new
                        {
                            ID = 54,
                            Author = "Deontae Franecki",
                            Category = "placeat",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Voluptas voluptas et nobis ut iste corrupti tempora adipisci nesciunt enim omnis nesciunt sit alias nisi officia cupiditate ab quos.",
                            ISBN = 715762020,
                            PageCount = 104,
                            PublicationDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Huel - Brown",
                            Title = "TCP Handmade Wooden Computer Uganda"
                        },
                        new
                        {
                            ID = 55,
                            Author = "Leo Bartoletti",
                            Category = "fugiat",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Eum iure rerum eos quia laudantium dolores et ut cupiditate quis qui et necessitatibus quis nihil iusto ut dolorem ratione.",
                            ISBN = 613588416,
                            PageCount = 92,
                            PublicationDate = new DateTime(2023, 11, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hagenes - Kris",
                            Title = "envisioneer Architect Fresh"
                        },
                        new
                        {
                            ID = 56,
                            Author = "Maude Koss",
                            Category = "sed",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Aut omnis consequatur et officiis a sit et tempore laudantium quia qui non odio tempora quia aut et deleniti tempore.",
                            ISBN = 656550390,
                            PageCount = 523,
                            PublicationDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Grant, Weimann and Beatty",
                            Title = "intermediate Spur interfaces"
                        },
                        new
                        {
                            ID = 57,
                            Author = "Norris Miller",
                            Category = "quam",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "A qui doloribus voluptates ipsa quisquam provident vel minus illum voluptatibus impedit voluptatum dolor praesentium libero et est voluptates quia.",
                            ISBN = 318921706,
                            PageCount = 735,
                            PublicationDate = new DateTime(2023, 9, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Nitzsche - Cruickshank",
                            Title = "Money Market Account calculating Home"
                        },
                        new
                        {
                            ID = 58,
                            Author = "Nyasia Barrows",
                            Category = "quam",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Dolores nulla qui expedita dolor dolorem id quisquam dolores doloremque id dolore sint assumenda quod quas consequatur quam et nostrum.",
                            ISBN = 627748767,
                            PageCount = 317,
                            PublicationDate = new DateTime(2023, 7, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Paucek LLC",
                            Title = "Sleek Granite Keyboard calculating Garden & Shoes"
                        },
                        new
                        {
                            ID = 59,
                            Author = "Ian Wiza",
                            Category = "dolores",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Ut quaerat placeat quo unde non eaque delectus laudantium officiis consequatur vel aut nemo explicabo dolorem consectetur qui dolor nostrum.",
                            ISBN = 395841452,
                            PageCount = 961,
                            PublicationDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Ferry, Hickle and Weimann",
                            Title = "Division gold optical"
                        },
                        new
                        {
                            ID = 60,
                            Author = "Keeley Hayes",
                            Category = "rerum",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Omnis est animi aut est rem veniam accusamus aliquid hic quibusdam error ad commodi necessitatibus vel culpa soluta magni beatae.",
                            ISBN = 465684500,
                            PageCount = 793,
                            PublicationDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bergnaum - Heaney",
                            Title = "e-services Reunion mission-critical"
                        },
                        new
                        {
                            ID = 61,
                            Author = "Marcellus Leuschke",
                            Category = "voluptas",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Eveniet eum est quasi ullam assumenda ab delectus cum voluptatem aspernatur quo sunt mollitia voluptates iste et illum asperiores voluptatum.",
                            ISBN = 263578942,
                            PageCount = 937,
                            PublicationDate = new DateTime(2023, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Weimann LLC",
                            Title = "Generic Concrete Mouse Grocery, Garden & Outdoors invoice"
                        },
                        new
                        {
                            ID = 62,
                            Author = "Cody Crist",
                            Category = "et",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Molestiae numquam laboriosam fugiat aut tempora vero excepturi quas commodi molestiae dolores perferendis eos eaque culpa sed deserunt itaque accusantium.",
                            ISBN = 481227787,
                            PageCount = 338,
                            PublicationDate = new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Dickens, Raynor and Walsh",
                            Title = "frictionless Tuvalu Visionary"
                        },
                        new
                        {
                            ID = 63,
                            Author = "Ignacio Moore",
                            Category = "perferendis",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Enim occaecati est labore quia nihil modi qui voluptatibus assumenda et asperiores ut quidem libero est molestiae ad praesentium facere.",
                            ISBN = 836350094,
                            PageCount = 487,
                            PublicationDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Gleason LLC",
                            Title = "Kids, Computers & Beauty monitor Regional"
                        },
                        new
                        {
                            ID = 64,
                            Author = "Hollie Farrell",
                            Category = "rem",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Molestiae reiciendis blanditiis ut totam fuga soluta debitis omnis aliquid quo aut officia a excepturi et pariatur sit nulla excepturi.",
                            ISBN = 779508067,
                            PageCount = 336,
                            PublicationDate = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Cormier - D'Amore",
                            Title = "6th generation Dynamic quantify"
                        },
                        new
                        {
                            ID = 65,
                            Author = "Delbert Erdman",
                            Category = "aut",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Officia hic totam quia ipsam earum vel saepe unde molestiae recusandae saepe ratione enim voluptas ab laborum quia excepturi possimus.",
                            ISBN = 340443796,
                            PageCount = 906,
                            PublicationDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schinner - Breitenberg",
                            Title = "strategic Intelligent purple"
                        },
                        new
                        {
                            ID = 66,
                            Author = "Verna Blick",
                            Category = "ratione",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Excepturi sed sed voluptatem maiores doloremque tempora nam iusto pariatur aperiam qui ullam sunt sunt tempore itaque vel aperiam praesentium.",
                            ISBN = 686344468,
                            PageCount = 147,
                            PublicationDate = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Crist and Sons",
                            Title = "Health action-items complexity"
                        },
                        new
                        {
                            ID = 67,
                            Author = "Ruthe Gusikowski",
                            Category = "consequuntur",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Aliquam quis dolore sint esse non facilis optio nobis saepe consequuntur voluptas itaque consequuntur sapiente et eum nobis quas ducimus.",
                            ISBN = 265981181,
                            PageCount = 118,
                            PublicationDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Beahan, Hyatt and Smitham",
                            Title = "Nebraska emulation Squares"
                        },
                        new
                        {
                            ID = 68,
                            Author = "Burdette Weimann",
                            Category = "odit",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Quibusdam beatae totam pariatur dignissimos quisquam ut ut reprehenderit quae qui corrupti qui labore doloremque optio in sed quidem et.",
                            ISBN = 453820603,
                            PageCount = 607,
                            PublicationDate = new DateTime(2023, 9, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Schimmel - Kuhic",
                            Title = "Licensed Soft Shoes Cape Verde Escudo Unbranded"
                        },
                        new
                        {
                            ID = 69,
                            Author = "Manley Schoen",
                            Category = "reiciendis",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Dolor neque dolorem nihil nam non quam sunt qui provident illum quas porro optio natus sequi ad ipsam ipsam minus.",
                            ISBN = 274544916,
                            PageCount = 622,
                            PublicationDate = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hills, Lang and Botsford",
                            Title = "convergence auxiliary Bedfordshire"
                        },
                        new
                        {
                            ID = 70,
                            Author = "Vincenza Bayer",
                            Category = "quos",
                            CoverPage = "http://lorempixel.com/640/480/technics",
                            Description = "Veniam numquam eos fugit voluptatum repudiandae dolore eaque doloribus eum officiis excepturi alias non explicabo et cupiditate harum qui ducimus.",
                            ISBN = 679078032,
                            PageCount = 501,
                            PublicationDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Nader, Lebsack and Fritsch",
                            Title = "Curve Delaware Camp"
                        },
                        new
                        {
                            ID = 71,
                            Author = "Emilia Dickinson",
                            Category = "ut",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Nesciunt aut maiores velit aut rerum occaecati nostrum repudiandae enim doloremque enim nihil laboriosam vero voluptas ipsam vel officia ipsum.",
                            ISBN = 713521141,
                            PageCount = 589,
                            PublicationDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Barton, Dibbert and Mayer",
                            Title = "Florida approach Plastic"
                        },
                        new
                        {
                            ID = 72,
                            Author = "Dillon Jacobi",
                            Category = "praesentium",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Eveniet consequatur id quidem sunt et incidunt et deserunt esse enim maiores odit inventore explicabo laboriosam voluptatem nemo eaque unde.",
                            ISBN = 205164007,
                            PageCount = 293,
                            PublicationDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Yost Group",
                            Title = "Licensed Intelligent Concrete Chair Factors"
                        },
                        new
                        {
                            ID = 73,
                            Author = "Ryder Kilback",
                            Category = "soluta",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Iusto mollitia numquam laborum autem molestiae voluptatem et doloremque tempora enim voluptatem non officia sint rem pariatur itaque sed voluptatum.",
                            ISBN = 960753123,
                            PageCount = 486,
                            PublicationDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Barrows Group",
                            Title = "compressing interfaces alarm"
                        },
                        new
                        {
                            ID = 74,
                            Author = "Kenya Weissnat",
                            Category = "odio",
                            CoverPage = "http://lorempixel.com/640/480/sports",
                            Description = "Qui explicabo harum qui non repudiandae numquam quasi reiciendis ullam consectetur ut ab in nam velit aut praesentium doloribus excepturi.",
                            ISBN = 516007143,
                            PageCount = 845,
                            PublicationDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Conn LLC",
                            Title = "Research Unbranded parsing"
                        },
                        new
                        {
                            ID = 75,
                            Author = "Pablo Wuckert",
                            Category = "et",
                            CoverPage = "http://lorempixel.com/640/480/people",
                            Description = "Sint omnis qui ipsam est aut optio est maxime explicabo eum temporibus qui dolore tempora eum rerum et dolorum alias.",
                            ISBN = 530839004,
                            PageCount = 423,
                            PublicationDate = new DateTime(2024, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bernhard - Gerhold",
                            Title = "Home Loan Account Lead Computers & Computers"
                        },
                        new
                        {
                            ID = 76,
                            Author = "Zoila Marvin",
                            Category = "sapiente",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Accusamus distinctio saepe cupiditate corrupti et est totam quibusdam molestias qui qui sint dolor itaque ipsa voluptas odio iusto repudiandae.",
                            ISBN = 452921682,
                            PageCount = 819,
                            PublicationDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hirthe LLC",
                            Title = "International Fantastic Cotton Fish wireless"
                        },
                        new
                        {
                            ID = 77,
                            Author = "Hilario Douglas",
                            Category = "inventore",
                            CoverPage = "http://lorempixel.com/640/480/nightlife",
                            Description = "Et rerum eligendi quisquam quo aliquam est ipsam reiciendis blanditiis sequi eius eum est iusto saepe beatae ut et dolores.",
                            ISBN = 878992635,
                            PageCount = 595,
                            PublicationDate = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Christiansen, Little and Schumm",
                            Title = "repurpose Extensions systematic"
                        },
                        new
                        {
                            ID = 78,
                            Author = "Neil Prosacco",
                            Category = "laudantium",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Tempore nulla quaerat voluptatibus voluptate consequatur dolores omnis eum expedita modi quis molestiae id ipsum placeat quis nihil omnis culpa.",
                            ISBN = 630589943,
                            PageCount = 343,
                            PublicationDate = new DateTime(2023, 9, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kiehn LLC",
                            Title = "Health & Toys Creative blue"
                        },
                        new
                        {
                            ID = 79,
                            Author = "Loyal Rempel",
                            Category = "nemo",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Delectus atque qui quidem recusandae numquam at dolorum nisi dolor ipsum ab eos veritatis delectus qui dolor corporis incidunt corporis.",
                            ISBN = 299409901,
                            PageCount = 883,
                            PublicationDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Price Group",
                            Title = "Cove virtual benchmark"
                        },
                        new
                        {
                            ID = 80,
                            Author = "Sophia McDermott",
                            Category = "hic",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Et autem voluptates in itaque quisquam repellat quia quibusdam pariatur maxime iste aut esse odit sed in et est esse.",
                            ISBN = 226502370,
                            PageCount = 917,
                            PublicationDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Wisoky, Hand and Sawayn",
                            Title = "Personal Loan Account Graphical User Interface Legacy"
                        },
                        new
                        {
                            ID = 81,
                            Author = "Jamar O'Connell",
                            Category = "in",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Voluptas labore iure aspernatur provident fugiat et molestias corrupti sunt dicta voluptates hic ullam odit est rerum accusantium quo sapiente.",
                            ISBN = 553140621,
                            PageCount = 827,
                            PublicationDate = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Swaniawski, Marks and Wolff",
                            Title = "card service-desk Handcrafted"
                        },
                        new
                        {
                            ID = 82,
                            Author = "Jody Lowe",
                            Category = "eveniet",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Quas maiores error unde reprehenderit facilis soluta fuga in sint doloribus ipsam cum natus alias aut voluptate occaecati dolores dolor.",
                            ISBN = 260630870,
                            PageCount = 468,
                            PublicationDate = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Renner, Satterfield and Brown",
                            Title = "Guyana Dollar synthesize Division"
                        },
                        new
                        {
                            ID = 83,
                            Author = "Reynold Langworth",
                            Category = "a",
                            CoverPage = "http://lorempixel.com/640/480/animals",
                            Description = "Optio et ex doloribus vel atque nobis tempora libero explicabo ut aut id voluptatem aliquid numquam eum qui quod eaque.",
                            ISBN = 427086821,
                            PageCount = 950,
                            PublicationDate = new DateTime(2024, 4, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kessler and Sons",
                            Title = "Rustic payment Research"
                        },
                        new
                        {
                            ID = 84,
                            Author = "Beverly Hilll",
                            Category = "aut",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Incidunt sed ducimus sit sit iste non fuga soluta repudiandae odit adipisci earum aut reiciendis voluptatem molestiae labore eaque officia.",
                            ISBN = 532070236,
                            PageCount = 470,
                            PublicationDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Frami, Zemlak and Ullrich",
                            Title = "Supervisor Sleek Concrete Ball Port"
                        },
                        new
                        {
                            ID = 85,
                            Author = "Timmothy Lindgren",
                            Category = "hic",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Eos atque est excepturi est veritatis culpa quos minima aliquam dicta id beatae asperiores commodi eum consequatur nam rerum nesciunt.",
                            ISBN = 110730983,
                            PageCount = 514,
                            PublicationDate = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Kirlin Inc",
                            Title = "withdrawal Lodge Solutions"
                        },
                        new
                        {
                            ID = 86,
                            Author = "Izabella Russel",
                            Category = "dolorem",
                            CoverPage = "http://lorempixel.com/640/480/nature",
                            Description = "Perferendis vel possimus aut quia exercitationem cupiditate aut dicta omnis nihil repellendus voluptas officia qui facere laborum qui quis est.",
                            ISBN = 329213297,
                            PageCount = 269,
                            PublicationDate = new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Hammes - Windler",
                            Title = "Money Market Account International navigating"
                        },
                        new
                        {
                            ID = 87,
                            Author = "Minnie Gislason",
                            Category = "nihil",
                            CoverPage = "http://lorempixel.com/640/480/technics",
                            Description = "Eius reprehenderit cupiditate eum qui vel sequi quis neque animi accusamus id molestiae adipisci porro nisi magni quia esse nesciunt.",
                            ISBN = 523053116,
                            PageCount = 859,
                            PublicationDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Grant and Sons",
                            Title = "Georgia Som Turkey"
                        },
                        new
                        {
                            ID = 88,
                            Author = "Domenico Mueller",
                            Category = "non",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Porro non qui aut eos dolores incidunt delectus doloremque ab eos labore est saepe similique est accusantium ipsum illum qui.",
                            ISBN = 697743226,
                            PageCount = 666,
                            PublicationDate = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lueilwitz, Macejkovic and Koch",
                            Title = "Awesome Plastic Keyboard Developer plug-and-play"
                        },
                        new
                        {
                            ID = 89,
                            Author = "Judson Sporer",
                            Category = "et",
                            CoverPage = "http://lorempixel.com/640/480/cats",
                            Description = "Eligendi est aut amet laborum numquam eos ea autem rem sit molestias tempore doloribus eligendi voluptatibus qui numquam expedita laborum.",
                            ISBN = 184651025,
                            PageCount = 754,
                            PublicationDate = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Pagac LLC",
                            Title = "web services Checking Account Awesome"
                        },
                        new
                        {
                            ID = 90,
                            Author = "Tierra Crist",
                            Category = "repudiandae",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Maiores necessitatibus eum possimus in omnis suscipit praesentium doloremque nisi optio dolorum perferendis sed cum et sunt consequatur hic similique.",
                            ISBN = 384304442,
                            PageCount = 251,
                            PublicationDate = new DateTime(2023, 8, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Steuber - Cartwright",
                            Title = "Savings Account Books & Home strategy"
                        },
                        new
                        {
                            ID = 91,
                            Author = "Kurt Robel",
                            Category = "aut",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Dolores officia aut quidem cum et nihil dolorem soluta et quae eos placeat laborum dolores consequatur ad voluptatum debitis nemo.",
                            ISBN = 946533462,
                            PageCount = 555,
                            PublicationDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Rempel Inc",
                            Title = "Investment Account quantify violet"
                        },
                        new
                        {
                            ID = 92,
                            Author = "Lia Runolfsson",
                            Category = "quia",
                            CoverPage = "http://lorempixel.com/640/480/fashion",
                            Description = "Voluptas earum rerum commodi consequatur molestiae illo debitis est odio excepturi voluptas dolorem quia eos hic molestiae rem recusandae nemo.",
                            ISBN = 213797872,
                            PageCount = 76,
                            PublicationDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Conn - Tremblay",
                            Title = "Optimized Personal Loan Account Automotive & Beauty"
                        },
                        new
                        {
                            ID = 93,
                            Author = "Jose McGlynn",
                            Category = "nam",
                            CoverPage = "http://lorempixel.com/640/480/abstract",
                            Description = "Ut officiis id aspernatur error expedita et pariatur iusto eligendi provident labore velit vel reprehenderit aut mollitia suscipit ut illum.",
                            ISBN = 973088440,
                            PageCount = 139,
                            PublicationDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Bosco LLC",
                            Title = "Virgin Islands, British clicks-and-mortar needs-based"
                        },
                        new
                        {
                            ID = 94,
                            Author = "Alejandrin Schoen",
                            Category = "aspernatur",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Labore id natus est nesciunt architecto dignissimos rerum voluptas consequuntur aut qui aspernatur et dolor ad ad et voluptatem accusamus.",
                            ISBN = 390685149,
                            PageCount = 544,
                            PublicationDate = new DateTime(2023, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Reichert, O'Keefe and Rolfson",
                            Title = "Practical Handmade Frozen Mouse Licensed Fresh Pizza"
                        },
                        new
                        {
                            ID = 95,
                            Author = "Elyssa Haley",
                            Category = "nisi",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Eveniet minus quam veritatis eaque omnis enim eaque et adipisci corporis ipsam in voluptatem ab facilis quidem sunt accusamus in.",
                            ISBN = 225201544,
                            PageCount = 220,
                            PublicationDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Mayert, Goyette and Mraz",
                            Title = "digital Analyst Junction"
                        },
                        new
                        {
                            ID = 96,
                            Author = "Alf Keebler",
                            Category = "quis",
                            CoverPage = "http://lorempixel.com/640/480/city",
                            Description = "Ea est ullam qui incidunt quaerat aperiam quibusdam aliquam et molestiae harum tenetur qui incidunt eligendi voluptatem dolores temporibus enim.",
                            ISBN = 388546645,
                            PageCount = 996,
                            PublicationDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Sauer - Fay",
                            Title = "monitor virtual Solutions"
                        },
                        new
                        {
                            ID = 97,
                            Author = "Madonna Hintz",
                            Category = "distinctio",
                            CoverPage = "http://lorempixel.com/640/480/business",
                            Description = "Officiis libero repellat sint modi ea veritatis ullam quo praesentium autem ullam consequatur rerum voluptas ratione aspernatur magni qui provident.",
                            ISBN = 580229814,
                            PageCount = 769,
                            PublicationDate = new DateTime(2023, 7, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Conroy - Smitham",
                            Title = "Refined Steel Mouse Games, Clothing & Electronics engineer"
                        },
                        new
                        {
                            ID = 98,
                            Author = "Felton Wintheiser",
                            Category = "dicta",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Voluptatum ipsum ratione reiciendis facere quia ea sed fugiat sit sequi vero sequi officiis error et qui eius molestias rem.",
                            ISBN = 481081967,
                            PageCount = 584,
                            PublicationDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Spencer - Ankunding",
                            Title = "Outdoors approach Tasty"
                        },
                        new
                        {
                            ID = 99,
                            Author = "Kaitlin Zulauf",
                            Category = "pariatur",
                            CoverPage = "http://lorempixel.com/640/480/transport",
                            Description = "Et magni autem quia est praesentium natus officia at officiis maiores error quia molestiae et amet alias vel soluta fuga.",
                            ISBN = 353139407,
                            PageCount = 498,
                            PublicationDate = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Towne Inc",
                            Title = "Forward Granite Security"
                        },
                        new
                        {
                            ID = 100,
                            Author = "Nigel Crona",
                            Category = "dicta",
                            CoverPage = "http://lorempixel.com/640/480/food",
                            Description = "Expedita corporis sit perferendis ut eum aut ea architecto quasi et aut ut quisquam assumenda est est a consectetur et.",
                            ISBN = 200273540,
                            PageCount = 801,
                            PublicationDate = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Publisher = "Lowe, Rohan and Dickens",
                            Title = "Spur New Hampshire Jersey"
                        });
                });

            modelBuilder.Entity("TechnicalAssessmentRokov.Entities.UserAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ROLE");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("ID");

                    b.ToTable("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
